Repository erigontech/erigon, pull requests merged in 2021-12, with the labels that each got.

#3066 Reverse order of arguments in eth_createAccessList
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta

#3068 More info about remote RPC Daemon state cache + eth_createAccessList
  cmd/rpcdaemon/README.md
Labels: beta

#3067 [beta] Reverse order of arguments in eth_createAccessList
  cmd/rpcdaemon/README.md
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta-cherry-pick

#3069 [EIP-4399] Remove newly added Header.Random (reuse mixHash instead)
  core/evm.go
  core/types/block.go
  core/types/block_test.go
  eth/stagedsync/stage_difficulty.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3070 Remove deduplication in NodeInfo response
  eth/backend.go
  eth/backend_test.go
  go.mod
  go.sum
Labels: beta

#3074 Update Engine API to v1.0.0-alpha.5
  cmd/rpcdaemon/commands/engine_api.go
Labels: proof-of-stake

#3076 fixed SpawnStageHeader not passing the test
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_headers.go
Labels: proof-of-stake

#3073 [beta] admin_nodeInfo implementation
  cmd/rpcdaemon/commands/admin_api.go
  cmd/rpcdaemon/commands/daemon.go
  cmd/rpcdaemon/commands/erigon_api.go
  cmd/rpcdaemon/commands/erigon_nodeInfo.go
  cmd/rpcdaemon/services/eth_backend.go
  cmd/sentry/download/sentry.go
  eth/backend.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3075 Fixed Proof-of-stake transition
  cmd/integration/commands/stages.go
  core/rawdb/accessors_chain.go
  core/rawdb/accessors_chain_test.go
  core/types/transaction.go
  eth/backend.go
  eth/stagedsync/stage_difficulty.go
  eth/stagedsync/stage_difficulty_test.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/sync.go
  eth/stagedsync/sync_test.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/headerdownload/header_algo_test.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3079 eth_getLogs to start from latest by default
  cmd/rpcdaemon/commands/eth_receipts.go
Labels: beta

#3082 [beta] Fix NodeInfo protocols decoding
  cmd/rpcdaemon/services/eth_backend.go
Labels: beta-cherry-pick

#3084 [beta] eth_getLogs to start from latest by default
  cmd/rpcdaemon/commands/eth_receipts.go
Labels: beta-cherry-pick

#3094 Dropped more ETH65 Code
  cmd/sentry/download/downloader.go
Labels: enhancement

#3096 trace_ include subtraces to precompiles with value > 0
  cmd/rpcdaemon/commands/trace_adhoc.go
Labels: beta

#3100 Take RLP fixes from erigon-lib
  go.mod
  go.sum
Labels: beta

#3098 [beta] trace_ include subtraces to precompiles with value > 0
  cmd/rpcdaemon/commands/trace_adhoc.go
Labels: beta-cherry-pick

#3101 [beta] RLP fix from Erigon-lib
  go.mod
  go.sum
Labels: beta-cherry-pick

#3083 Implementing basic unwind process for Proof-of-stake
  eth/stagedsync/stage_headers.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3114 DockerCompose: add --txpool.api.addr flag to rpcdaemon
  docker-compose.yml
Labels: beta

#3115 DockerCompose: add --txpool.api.addr flag to rpcdaemon
  docker-compose.yml
Labels: beta-cherry-pick

#3109 [beta] Grpc healtcheck
  cmd/cons/commands/clique.go
  cmd/integration/commands/testing.go
  cmd/rpcdaemon/cli/config.go
  cmd/sentry/commands/sentry.go
  cmd/sentry/download/sentry.go
  cmd/utils/flags.go
  eth/backend.go
  ethdb/privateapi/all.go
  go.mod
  go.sum
  node/config.go
  node/defaults.go
  turbo/cli/default_flags.go
  turbo/cli/flags.go
Labels: beta-cherry-pick

#3092 Added reversed for proof-of-stake syncing
  cmd/sentry/download/downloader.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3112 Serenity engine: fall back to eth1 engine before the Merge
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/errors.go
  consensus/ethash/consensus.go
  consensus/ethash/fake.go
  consensus/parlia/parlia.go
  consensus/serenity/serenity.go
  consensus/serenity/serenity_test.go
  core/block_validator_test.go
  core/chain_makers.go
  eth/ethconfig/config.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_headers.go
  params/protocol_params.go
Labels: proof-of-stake

#3123 [beta] Remove eth/65 support
  cmd/sentry/download/downloader.go
  cmd/sentry/download/sentry.go
  cmd/utils/flags.go
  eth/backend.go
  turbo/cli/default_flags.go
Labels: beta-cherry-pick

#3113 Txpool tracing by sender addresses
  cmd/utils/flags.go
  core/tx_pool.go
  eth/backend.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
Labels: beta

#3127 [beta] Txpool tracing by sender addresses
  cmd/utils/flags.go
  core/tx_pool.go
  eth/backend.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
Labels: beta-cherry-pick

#3134 [beta] Check upgrade/downgrade of database schema version to prevent accidental upgrade, remove migrations
  cmd/hack/hack.go
  migrations/fix_sequences.go
  migrations/header_prefix.go
  migrations/header_prefix_test.go
  migrations/migrations.go
  migrations/prune.go
  migrations/receipt_cbor.go
  migrations/receipt_repair.go
  migrations/remove_clique.go
  migrations/set_prune_type.go
Labels: beta-cherry-pick

#3135 Txpool: broadcast transaction along with announcements
  cmd/sentry/sentry/downloader.go
  cmd/sentry/sentry/sentry.go
  go.mod
  go.sum
Labels: beta

#3138 [beta] TxPool broadcast fixes
  cmd/sentry/download/downloader.go
  cmd/sentry/download/sentry.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3142 [beta] Fix for RPC filters, remove mined transactions
  cmd/rpcdaemon/commands/eth_filters.go
  cmd/rpcdaemon/filters/filters.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3118 Engine GetPayloadBodiesV1
  cmd/rpcdaemon/commands/engine_api.go
Labels: proof-of-stake

#3155 RLP: base error - allows skip them if need
  go.mod
  go.sum
Labels: beta

#3157 Make waitingPosHeaders atomic since it's accessed concurrently
  eth/backend.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3151 Verify PoS headers before inserting them into DB
  cmd/rpcdaemon/commands/engine_api.go
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_difficulty.go
  eth/stagedsync/stage_difficulty_test.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stages/stages.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/headerdownload/header_algo_test.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3168 Rule guard linter enable
  .golangci.yml
  Makefile
  cmd/rpcdaemon/commands/eth_call.go
  common/hasher.go
  common/path.go
  eth/stagedsync/stage_call_traces.go
  eth/stagedsync/stage_hashstate.go
  eth/stagedsync/stage_headers.go
  rules.go
Labels: beta

#3170 fix nil pointer in senders stage
  eth/stagedsync/stage_senders.go
Labels: beta

#3171 Fix sender nil pointer stable
  .gitignore
  eth/stagedsync/stage_senders.go
Labels: beta-cherry-pick

#3169 Rule guard linter enable
  .golangci.yml
  eth/stagedsync/stage_call_traces.go
Labels: beta-cherry-pick

#3175 RLP base error, part2
  go.mod
  go.sum
Labels: beta

#3148 fix debug_storageRangeAt
  turbo/transactions/tracing.go
Labels: beta

#3174 Support for syncing on mergemock
  .gitignore
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/services/eth_backend.go
  eth/backend.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake
