Repository erigontech/erigon, pull requests merged in 2021-11, with the labels that each got.

#2941 Check existence before write - because WriteRawBody isn't idempotent
  eth/stagedsync/stage_bodies.go
Labels: beta

#2945 Fix header skeleton
  turbo/stages/headerdownload/header_algos.go
Labels: beta

#2946 Fix SendHeaderRequest peer minBlock
  cmd/sentry/download/sentry_api.go
Labels: beta

#2948 RPC: don't save nil's to blocksLRU (#2937)
  cmd/rpcdaemon/commands/eth_api.go
Labels: beta-cherry-pick

#2949 Check existence before write - because WriteRawBody isn't idempotent (it allocates new sequence range for transactions on every call) (#2941)
  eth/stagedsync/stage_bodies.go
Labels: beta-cherry-pick

#2962 [EIP4399 part 1] added random field to block type
  core/types/block.go
  core/types/block_test.go
Labels: beta

#2956 mdbx: revert augument limit
  go.mod
  go.sum
Labels: beta-cherry-pick

#2963 Increase default txpool size
  core/tx_pool.go
Labels: beta-cherry-pick

#2965 Pool: PooledTransactions to produce correct rlp for non-legacy txs
  go.mod
  go.sum
Labels: beta

#2968 Run CI actions on PRs and pushes for stable branch
  .github/workflows/ci.yml
Labels: beta

#2970 Run CI actions on PRs and pushes for stable branch
  .github/workflows/ci.yml
  params/version.go
Labels: beta-cherry-pick

#2971 [stable] `eth_getTransactionCount` to work with `pending` from txpool
  cmd/rpcdaemon/commands/eth_accounts.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#2972 [beta] Fixes to sentry and downloader
  cmd/sentry/commands/sentry.go
  cmd/sentry/download/sentry.go
  cmd/sentry/download/sentry_api.go
  cmd/utils/flags.go
  turbo/cli/default_flags.go
  turbo/stages/headerdownload/header_algo_test.go
  turbo/stages/headerdownload/header_algos.go
Labels: beta-cherry-pick

#2964 [EIP-4399 2/3] Added total difficulty stage and transition logic
  cmd/integration/commands/stages.go
  core/rawdb/accessors_chain.go
  core/rawdb/accessors_chain_test.go
  eth/backend.go
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_difficulty.go
  eth/stagedsync/stage_difficulty_test.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stages/stages.go
  go.mod
  turbo/stages/headerdownload/header_algo_test.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: enhancement

#2989 Fix for eth_getLogs with zero fromBlock and toBlock
  cmd/rpcdaemon/commands/eth_receipts.go
Labels: beta

#2990 [beta] Fix for eth_getLogs with zero fromBlock and toBlock
  cmd/rpcdaemon/commands/eth_receipts.go
Labels: beta-cherry-pick

#3002 trace_block to return empty result for genesis
  cmd/rpcdaemon/commands/trace_filtering.go
Labels: beta

#3001 eth_getTransactionReceipt not to return unrelated different tx receipts
  cmd/rpcdaemon/commands/eth_receipts.go
  core/state/database_test.go
  eth/stagedsync/stage_txlookup.go
Labels: beta-cherry-pick

#3003 [beta] trace_block to return empty result for genesis
  cmd/rpcdaemon/commands/trace_filtering.go
Labels: beta-cherry-pick

#3004 Bump stable version to 2021.11.04
  params/version.go
Labels: beta

#3006 eth_estimateGas to correctly recap to balance for London txs
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta

#3005 Pool: reject low nonce and low balance txs
  go.mod
  go.sum
Labels: beta

#3009 Update skip_analysis.go
  core/skip_analysis.go
Labels: beta

#3008 Fix Sentry server initialization
  cmd/sentry/download/sentry.go
  cmd/sentry/download/sentry_test.go
  p2p/server.go
Labels: beta

#3012 [beta] Fix sentry server initialisation
  cmd/sentry/download/sentry.go
  cmd/sentry/download/sentry_test.go
  p2p/server.go
Labels: beta-cherry-pick

#3007 [beta] eth_estimateGas to correctly recap to balance for London txs
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta-cherry-pick

#3016 Pool: reject low nonce and low balance txs
  go.mod
  go.sum
Labels: beta-cherry-pick

#3023 [beta] Peer height stable fix
  cmd/sentry/download/sentry.go
Labels: beta-cherry-pick

#3025 Pool: fix validate order
  go.mod
  go.sum
Labels: beta-cherry-pick

#3032 [beta] Enable receipt responses
  cmd/sentry/download/sentry.go
Labels: beta-cherry-pick

#3037 [beta] Not try to create temporary file with enode
  p2p/server.go
Labels: beta-cherry-pick

#3039 [txpool] Introduce PriceBump, change tx replacement logic, add test
  cmd/txpool/main.go
  cmd/utils/flags.go
  eth/backend.go
  go.mod
  go.sum
Labels: beta

#3040 [beta] [txpool] Introduce PriceBump, change tx replacement logic, add test
  cmd/txpool/main.go
  cmd/utils/flags.go
  eth/backend.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3048 Create access list
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
  eth/tracers/logger/access_list_tracer.go
  internal/ethapi/api.go
Labels: beta

#3052 Create access list (#3048)
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
  eth/tracers/logger/access_list_tracer.go
  internal/ethapi/api.go
Labels: beta-cherry-pick

#3055 [beta] Update GitHub actions to MacOS 11
  .github/workflows/ci.yml
Labels: beta-cherry-pick

#3057 MDBX: Increase hard limit to 3Tb
  go.mod
  go.sum
Labels: beta

#3058 mdbx: 3tb hard limit
  go.mod
  go.sum
Labels: beta-cherry-pick

#3059 Integration fix - to produce correct genesis body
  cmd/integration/commands/reset_state.go
  core/genesis.go
Labels: beta-cherry-pick

#3060 Fix genesis generation in integration tool
  cmd/integration/commands/reset_state.go
  core/genesis.go
Labels: beta

#3046 Add NodeInfo implementation
  cmd/rpcdaemon/commands/admin_api.go
  cmd/rpcdaemon/commands/daemon.go
  cmd/rpcdaemon/commands/erigon_api.go
  cmd/rpcdaemon/commands/erigon_nodeInfo.go
  cmd/rpcdaemon/services/eth_backend.go
  cmd/sentry/download/sentry.go
  eth/backend.go
  eth/backend_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
Labels: beta
