Repository erigontech/erigon, pull requests merged in 2022-04, with the labels that each got.

#3806 Prefer forkchoice head as latest block in RPC
  cmd/rpcdaemon/commands/rpc_block.go
  core/rawdb/accessors_chain.go
  eth/stagedsync/stage_headers.go
  go.mod
  go.sum
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
Labels: proof-of-stake

#3802 fix nil pointer in fetch.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3826 Check TerminalTotalDifficulty for NewPayload & ForkChoice
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3824 [stable] Fix 'all defaults' case for eth_estimateGas (#3790)
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/eth_call_test.go
Labels: beta-cherry-pick

#3827 Prohibit EIP-2718 txn wrapped as RLP strings
  core/types/transaction.go
  core/types/transaction_test.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3839 Check that safe & finalized blocks are ancestors of head block
  core/rawdb/accessors_chain.go
  eth/stagedsync/stage_headers.go
Labels: proof-of-stake

#3846 ExchangeTransitionConfiguration: allow non-zero TerminalBlockNumber
  cmd/rpcdaemon/commands/engine_api.go
Labels: proof-of-stake

#3888 RPC: return latest available block rather than forkchoice head
  cmd/rpcdaemon/commands/rpc_block.go
Labels: proof-of-stake

#3893 Change libmdbx submodule origin
  .gitmodules
Labels: beta

#3894 Change libmdbx submodule origin
  .gitmodules
Labels: beta-cherry-pick

#3895 [stable] Fix for MDBX assert
  go.mod
  go.sum
Labels: beta-cherry-pick

#3896 Bump beta version to 2022.04.02
  params/version.go
Labels: beta-cherry-pick

#3897 Update skip_analysis.go
  core/skip_analysis.go
Labels: beta

#3898 [stable] Update skip_analysis.go (#3897)
  core/skip_analysis.go
Labels: beta-cherry-pick

#3902 print short panic in main, but exit with error code 1
  cmd/erigon/main.go
Labels: beta

#3904 print short panic in main, but exit with error code 1 #3902
  cmd/erigon/main.go
Labels: beta-cherry-pick

#3913 Fixes in header downloader
  turbo/stages/headerdownload/header_algos.go
Labels: beta

#3911 [stable] Fixes for header download
  turbo/stages/headerdownload/header_algos.go
Labels: beta-cherry-pick

#3931 Added Ethstats service
  cmd/integration/commands/stages.go
  cmd/utils/flags.go
  core/rawdb/accessors_chain.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_finish.go
  ethstats/ethstats.go
  turbo/cli/default_flags.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: alpha

#3936 Add alpha branch to CI
  .github/workflows/ci.yml
Labels: alpha

#3935 [alpha] Ethstats + documentation fixes + go1.18 requirement refactoring
  Makefile
  README.md
  cmd/integration/commands/stages.go
  cmd/utils/flags.go
  core/rawdb/accessors_chain.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_finish.go
  ethstats/ethstats.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: alpha-cherry-pick

#3938 [alpha] add PRs to CI
  .github/workflows/ci.yml
Labels: alpha-cherry-pick

#3978 Forgot to check err status
  eth/stagedsync/stage_headers.go
Labels: proof-of-stake

#3962 Potential fix for verification
  turbo/stages/headerdownload/header_algos.go
Labels: beta, alpha

#3990 [alpha] Sweep latest changes from devel to alpha
  README.md
  cmd/utils/flags.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_txlookup.go
  p2p/discover/v4_udp.go
  p2p/discover/v4_udp_test.go
  p2p/discover/v4wire/v4wire.go
  p2p/discover/v4wire/v4wire_test.go
  rlp/decode.go
  rlp/decode_test.go
  rlp/doc.go
  rlp/encode.go
  rlp/encode_test.go
  rlp/typecache.go
  turbo/snapshotsync/snapshotsynccli/flags.go
  turbo/stages/headerdownload/header_algos.go
Labels: alpha-cherry-pick

#3996 [alpha] TxLookup fix 2 (#3994)
  eth/stagedsync/stage_txlookup.go
Labels: alpha-cherry-pick

#3997 Check that safe & finalized blocks are canonical for no-op forkChoice
  eth/stagedsync/stage_headers.go
Labels: proof-of-stake

#4018 Add override.terminaltotaldifficulty flag
  cmd/utils/customflags.go
  cmd/utils/flags.go
  turbo/cli/default_flags.go
Labels: proof-of-stake
