Repository erigontech/erigon, pull requests merged in 2022-08, with the labels that each got.

#4885 cmd: make sure regular rpc server start is reachable
  cmd/rpcdaemon/cli/config.go
Labels: proof-of-stake

#4887 Don't start engine API in standalone rpcdaemon
  cmd/devnettest/rpcdaemon/daemon.go
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/main.go
Labels: proof-of-stake

#4890 Rename engine.* flags to authrpc.* for consistency with geth
  README.md
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/cli/httpcfg/http_cfg.go
  cmd/rpcdaemon22/cli/config.go
  cmd/utils/flags.go
  node/nodecfg/defaults.go
  turbo/cli/default_flags.go
  turbo/cli/flags.go
Labels: proof-of-stake

#4931 Remove authrpc.* flags from rpcdaemon
  README.md
  cmd/rpcdaemon/cli/config.go
  docker-compose.yml
  turbo/cli/default_flags.go
  turbo/cli/flags.go
Labels: proof-of-stake

#4944 removed incarnation updates and removed side forks past fcu
  turbo/engineapi/fork_validator.go
Labels: proof-of-stake

#4955 UX improvement for pre-merge sync with Teku
  ethdb/privateapi/ethbackend.go
  turbo/engineapi/fork_validator.go
Labels: proof-of-stake

#5020 Mainnet Terminal Total Difficulty
  params/chainspecs/mainnet.json
Labels: proof-of-stake

#5048 Added Full Validation for PoS Terminal blocks
  turbo/engineapi/fork_validator.go
  turbo/stages/headerdownload/header_algos.go
Labels: proof-of-stake

#5106 Access to EthBackendServer.builders should be protected by lock
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#5107 Log RLP of built PoS blocks
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#5124 Optimized backend pre-checks and fixed FCU deadlock
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
Labels: bug, proof-of-stake

#5149 Small fix: log block RLP as hex
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#5165 Amend log message and level
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#5172 Disable PoW sync for networks that have already passed through the Merge
  cmd/sentry/sentry/sentry_multi_client.go
  eth/stagedsync/stage_headers.go
  params/chainspecs/goerli.json
  params/chainspecs/kiln-devnet.json
  params/chainspecs/ropsten.json
  params/chainspecs/sepolia.json
  params/config.go
Labels: proof-of-stake

#5195 Prevent slice bounds out of range on invalid payload.LogsBloom
  cmd/rpcdaemon22/commands/engine_api.go
Labels: proof-of-stake

#5205 Fixed Invalid block production with invalid txpool txs.
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
Labels: proof-of-stake

#5235 added VerkleProof field to header.
  core/types/block.go
  go.mod
  go.sum
Labels: verkle-tree
