Repository erigontech/erigon, pull requests merged in 2022-02, with the labels that each got.

#3396 penalize peer for invalid rlp
  rlp/decode.go
Labels: beta-cherry-pick

#3399 Pool: hotfix for slow "new txs notifications"
  go.mod
  go.sum
Labels: beta-cherry-pick

#3402 pool: fix race in async broadcast
  go.mod
  go.sum
Labels: beta

#3404 pool: fix race in async broadcast
  go.mod
  go.sum
Labels: beta-cherry-pick

#3409 fix compatibility of getting tx by number
  cmd/rpcdaemon/commands/eth_txs.go
Labels: beta

#3410 [stable] fix compatibility of getting tx by number
  cmd/rpcdaemon/commands/eth_txs.go
Labels: beta-cherry-pick

#3419 [stable] Fix txpool memory leak
  go.mod
  go.sum
Labels: beta-cherry-pick

#3424 close nodes db on server start error
  cmd/sentry/sentry/downloader.go
  cmd/sentry/sentry/sentry.go
  p2p/enode/nodedb.go
  p2p/server.go
Labels: beta

#3425 close nodes db on server start error (#3424)
  cmd/sentry/download/downloader.go
  cmd/sentry/download/sentry.go
  p2p/enode/nodedb.go
  p2p/server.go
Labels: beta-cherry-pick

#3447 Cherrypick/parity list
  DEV_CHAIN.md
  cmd/devnettest/commands/account.go
  cmd/devnettest/commands/block.go
  cmd/devnettest/commands/parity.go
  cmd/devnettest/commands/root.go
  cmd/devnettest/commands/tx.go
  cmd/devnettest/main.go
  cmd/devnettest/requests/request_generator.go
  cmd/devnettest/requests/requests.go
  cmd/devnettest/requests/utils.go
  cmd/rpcdaemon/commands/parity_api.go
  cmd/rpcdaemon/commands/parity_api_test.go
  cmd/rpctest/rpctest/type.go
Labels: beta-cherry-pick

#3340 New Engine API semantics (Kiln v1)
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/rpcdaemontest/test_util.go
  cmd/rpcdaemon/services/eth_backend.go
  eth/backend.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3464 eth_GetTransactionByHash: to return nil pending txn by hash
  cmd/rpcdaemon/commands/eth_txs.go
Labels: beta-cherry-pick

#3466 state and newHead: 1 goroutine per subscriber
  cmd/rpcdaemon/commands/eth_subscribe_test.go
  eth/protocols/eth/discovery.go
  eth/protocols/eth/handler.go
  eth/protocols/eth/protocol.go
  eth/stagedsync/stage_finish.go
  eth/stagedsync/stagebuilder.go
  ethdb/privateapi/ethbackend.go
  ethdb/privateapi/events.go
  ethdb/snapshotdb/kv_snapshot_property_test.go
  go.mod
  go.sum
  turbo/stages/stageloop.go
Labels: beta-cherry-pick

#3468 Revert "Inverted lowestNum and highestNum in header downloader (#3301)"
  turbo/stages/headerdownload/header_algos.go
Labels: beta

#3469 Revert "Inverted lowestNum and highestNum in header downloader (#3301…
  turbo/stages/headerdownload/header_algos.go
Labels: beta-cherry-pick

#3456 Update instead of SaveStageProgress for stages.Header
  eth/stagedsync/stage_headers.go
  turbo/stages/headerdownload/header_algos.go
Labels: beta

#3458 Update instead of SaveStageProgress for stages.Header
  eth/stagedsync/stage_headers.go
  turbo/stages/headerdownload/header_algos.go
Labels: beta-cherry-pick

#3482 Add Beacon payloads to body downloader prefetch
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3486 RPCDaemon: can start when txpool disabled
  eth/backend.go
  go.mod
  go.sum
Labels: beta-cherry-pick

#3498 Atomic close 2 channels
  cmd/sentry/sentry/sentry.go
Labels: beta

#3502 Fix/wsfix stable
  Makefile
  cmd/devnettest/commands/block.go
  cmd/devnettest/commands/requests.go
  cmd/devnettest/requests/mock_requests.go
  cmd/devnettest/requests/request_generator.go
  cmd/devnettest/requests/requests.go
  cmd/rpcdaemon/cli/config.go
Labels: beta-cherry-pick

#3489 [header downloader] introduce queues instead of insertList
  turbo/app/import.go
  turbo/stages/bodydownload/body_algos.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
Labels: beta

#3453 Optimized eth_createAccessList
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta

#3454 adding engine_ExchangeTransitionConfigurationV1
  cmd/rpcdaemon/commands/engine_api.go
  params/config.go
Labels: proof-of-stake

#3526 Bump beta release version to 2022.02.03
  params/version.go
Labels: beta-cherry-pick

#3524 Optimized eth_createAccessList (#3453)
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
Labels: beta-cherry-pick

#3525 [header downloader] introduce queues instead of insertList (#3489)
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
Labels: beta-cherry-pick

#3533 fix some nil on shutdown
  eth/backend.go
Labels: beta-cherry-pick

#3536 Fix stall on unwind in handleForkChoice
  cmd/rpcdaemon/README.md
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/filters/filters.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
Labels: proof-of-stake

#3540 RPCDaemon start with disabled txpool
  go.mod
  go.sum
Labels: beta-cherry-pick

#3561 added sleep for NewPayloadV1 and Forkchoice
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3564 Fix coinbase in stage_mining_exec
  cmd/rpcdaemon/commands/engine_api.go
  eth/backend.go
  ethdb/privateapi/ethbackend.go
  params/config.go
  turbo/stages/headerdownload/header_algos.go
Labels: proof-of-stake

#3569 close channel by producer
  cmd/sentry/sentry/sentry.go
Labels: beta

#3568 Close channel by producer
  cmd/sentry/download/sentry.go
Labels: beta-cherry-pick

#3570 Fixes to access list and state overrides
  cmd/rpcdaemon/commands/eth_call.go
  core/state/state_object.go
Labels: beta

#3575 Fixed get-payload and Hanging ForkChoice
  cmd/rpcdaemon/filters/filters.go
  cmd/rpcdaemon/services/eth_backend.go
  crypto/crypto.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_mining_create_block.go
  internal/build/archive.go
  rlp/decode.go
  rlp/encode_test.go
  rpc/json.go
  turbo/app/import.go
  turbo/trie/witness.go
Labels: proof-of-stake

#3580 Optimise eth_getStorageAt for current state
  cmd/rpcdaemon/commands/eth_accounts.go
  turbo/rpchelper/helper.go
  turbo/transactions/call.go
Labels: beta

#3586 Fixes to access list and state overrides (#3570)
  cmd/rpcdaemon/commands/eth_call.go
  core/state/state_object.go
Labels: beta-cherry-pick

#3587 Optimise eth_getStorageAt for current state (#3580)
  cmd/rpcdaemon/commands/eth_accounts.go
  turbo/rpchelper/helper.go
  turbo/transactions/call.go
Labels: beta-cherry-pick

#3591 new bootnodes
  params/bootnodes.go
Labels: beta

#3592 Refactor payload building
  cmd/rpcdaemon/commands/engine_api.go
  core/block_proposer.go
  core/chain_makers.go
  core/types/block.go
  eth/backend.go
  eth/stagedsync/stage_mining_create_block.go
  ethdb/privateapi/ethbackend.go
  rpc/errors.go
Labels: proof-of-stake

#3597 storage override revert support
  core/state/journal.go
  core/state/state_object.go
Labels: beta

#3598 Auto detect latest block for optimal use of plain state and state cache
  cmd/rpcdaemon/commands/eth_accounts.go
  cmd/rpcdaemon/commands/eth_api_test.go
  cmd/rpcdaemon/commands/eth_block.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/starknet_accounts.go
  cmd/rpcdaemon/commands/trace_adhoc.go
  cmd/rpcdaemon/commands/tracing.go
  turbo/rpchelper/helper.go
  turbo/transactions/call.go
Labels: beta

#3601 [stable] Auto detect latest block for optimal use of plain state and cache
  cmd/rpcdaemon/commands/eth_accounts.go
  cmd/rpcdaemon/commands/eth_api_test.go
  cmd/rpcdaemon/commands/eth_block.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/trace_adhoc.go
  cmd/rpcdaemon/commands/tracing.go
  turbo/rpchelper/helper.go
  turbo/transactions/call.go
Labels: beta-cherry-pick

#3599 [stable] debug_traceBlockByNumber and debug_traceBlockByHash
  cmd/rpcdaemon/README.md
  cmd/rpcdaemon/commands/debug_api.go
  cmd/rpcdaemon/commands/debug_api_test.go
  cmd/rpcdaemon/commands/tracing.go
  cmd/rpctest/main.go
  cmd/rpctest/rpctest/bench_tracetransaction.go
  cmd/rpctest/rpctest/request_generator.go
Labels: beta-cherry-pick

#3594 Skip analysis update
  core/skip_analysis.go
Labels: beta

#3600 [stable] storage override revert support
  core/state/journal.go
  core/state/state_object.go
Labels: beta-cherry-pick

#3604 [stable][txpool] Poke transactions that cannot be replaced
  go.mod
  go.sum
Labels: beta-cherry-pick

#3616 PrevRandao Renaming
  cmd/rpcdaemon/commands/engine_api.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
Labels: proof-of-stake

#3617 block by timestamp for stable
  cmd/rpcdaemon/README.md
  cmd/rpcdaemon/commands/erigon_api.go
  cmd/rpcdaemon/commands/erigon_block.go
  cmd/rpcdaemon/commands/eth_call_test.go
  rpc/types.go
Labels: beta-cherry-pick

#3620 Add timings of forward stages to logs
  eth/stagedsync/sync.go
Labels: beta

#3621 Add timings of forward stages to logs
  eth/stagedsync/sync.go
Labels: beta-cherry-pick

#3627 deleted bor and starknet from doc
  cmd/rpcdaemon/README.md
Labels: beta-cherry-pick

#3531 Added Engine Authentication [JWT]
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/cli/httpcfg/http_cfg.go
  go.mod
  go.sum
Labels: proof-of-stake
