Repository erigontech/erigon, pull requests merged in 2022-03, with the labels that each got.

#3633 Expose eth API on the same ports as engine API
  Dockerfile
  README.md
  cmd/rpcdaemon/cli/config.go
  docker-compose.yml
Labels: proof-of-stake

#3640 Handle a corner case in forkchoiceUpdated
  cmd/rpcdaemon/commands/call_traces_test.go
  cmd/rpcdaemon/commands/eth_subscribe_test.go
  cmd/rpcdaemon/commands/send_transaction_test.go
  cmd/rpcdaemon/commands/txpool_api_test.go
  consensus/clique/snapshot_test.go
  core/block_validator_test.go
  core/chain_makers.go
  docs/evm_semantics.md
  docs/merry-go-round-sync.md
  eth/stagedsync/stage_hashstate.go
  eth/stagedsync/stage_headers.go
  turbo/stages/blockchain_test.go
  turbo/stages/mock_sentry.go
  turbo/stages/sentry_mock_test.go
Labels: proof-of-stake

#3653 add nosqlite tag
  Makefile
Labels: beta-cherry-pick

#3652 add nosqlite tag
  Makefile
Labels: beta

#3665 allow use both flags: --miner.sigfile and --miner.etherbase
  cmd/utils/flags.go
Labels: beta-cherry-pick

#3662 allow any call origin to /debug/metrics/prometheus
  internal/debug/flags.go
  metrics/exp/exp.go
Labels: beta

#3663 allow any call origin to /debug/metrics/prometheus
  internal/debug/flags.go
  metrics/exp/exp.go
Labels: beta-cherry-pick

#3673 linter up (#3672)
  .github/workflows/ci.yml
  Makefile
  p2p/discover/v4_udp_test.go
  p2p/discover/v5_udp_test.go
  p2p/simulations/adapters/exec.go
Labels: beta-cherry-pick

#3686 Fixed forkid for mergeBlock
  cmd/rpcdaemon/commands/engine_api.go
  params/config.go
Labels: proof-of-stake

#3687 fixed transition warning in Prysm
  cmd/rpcdaemon/commands/engine_api.go
Labels: proof-of-stake

#3689 fixed JWT authentication port
  cmd/rpcdaemon/cli/config.go
Labels: proof-of-stake

#3693 [stable] Fixes for state overrides in RPC
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/tracing.go
  core/state_transition.go
  eth/tracers/api.go
  internal/ethapi/state_overrides.go
  turbo/transactions/call.go
Labels: beta-cherry-pick

#3695 [stable] new bootnodes (#3591)
  params/bootnodes.go
Labels: beta-cherry-pick

#3712 More Merge logging
  cmd/rpcdaemon/commands/engine_api.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3713 Pick up erigon-lib fix for h2048 (#367)
  go.mod
  go.sum
Labels: proof-of-stake

#3716 rpcdaemon: fix TxContext in traceBlock
  cmd/rpcdaemon/commands/tracing.go
Labels: beta-cherry-pick

#3718 rpcdaemon: fix TxContext in traceBlock (#3716)
  cmd/rpcdaemon/commands/tracing.go
Labels: beta

#3666 Logs sub
  eth/stagedsync/stage_finish.go
  eth/stagedsync/stagebuilder.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  ethdb/privateapi/events.go
  ethdb/privateapi/logsfilter.go
  interfaces.go
Labels: question, beta, draft

#3714 Mdbx: WriteMap fallback on error
  go.mod
  go.sum
Labels: beta-cherry-pick

#3726 Pool cost fix
  go.mod
  go.sum
Labels: beta

#3725 Pool cost fix
  go.mod
  go.sum
Labels: beta-cherry-pick

#3742 Added kiln devnet
  cmd/utils/flags.go
  core/allocs/kiln-devnet.json
  core/genesis.go
  params/bootnodes.go
  params/config.go
  params/networkname/network_name.go
Labels: proof-of-stake

#3751 Feat/rpcdaemon logs sub
  cmd/rpcdaemon/commands/eth_filters.go
  cmd/rpcdaemon/filters/filters.go
  cmd/rpcdaemon/services/eth_backend.go
Labels: question, beta, draft

#3753 Demoted logs for PoS downloader
  cmd/rpcdaemon/commands/engine_api.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#3752 added Websocket support and authentication to Engine API
  cmd/rpcdaemon/cli/config.go
  node/rpcstack.go
  rpc/client_test.go
  rpc/http.go
  rpc/websocket.go
  rpc/websocket_test.go
Labels: proof-of-stake

#3757 Fixed Erigon README for Authentication API and jwt.hex generates in Datadir
  README.md
  cmd/utils/flags.go
  turbo/cli/flags.go
Labels: proof-of-stake

#3773 [stable] Event log subscription
  cmd/rpcdaemon/commands/eth_filters.go
  cmd/rpcdaemon/filters/filters.go
  cmd/rpcdaemon/filters/logsfilter.go
  cmd/rpcdaemon/services/eth_backend.go
  eth/stagedsync/stage_finish.go
  eth/stagedsync/stagebuilder.go
  ethdb/privateapi/ethbackend.go
  ethdb/privateapi/events.go
  ethdb/privateapi/logsfilter.go
  go.mod
  go.sum
  interfaces.go
Labels: beta-cherry-pick

#3783 Integration: reset StageFinish also
  cmd/integration/commands/state_stages.go
Labels: beta-cherry-pick

#3782 Integration: update StageFinish too
  cmd/integration/commands/state_stages.go
Labels: beta

#3781 docker hub - fetch git tags before build
  hooks/post_checkout
Labels: beta-cherry-pick

#3780 docker hub - fetch git tags before build
  hooks/post_checkout
Labels: beta

#3785 Small Merge-related clarifications & improvements
  cmd/sentry/sentry/downloader.go
  eth/stagedsync/stage_headers.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
Labels: proof-of-stake

#3790 Fix 'all defaults' case for eth_estimateGas
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_call.go
  cmd/rpcdaemon/commands/eth_call_test.go
Labels: beta-cherry-pick
