Repository erigontech/erigon, pull requests merged in 2022-01, with the labels that each got.

#3197 Sanity check p2p block
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/interfaces/interfaces.go
  cmd/sentry/sentry/downloader.go
  core/rawdb/accessors_chain.go
  eth/backend.go
  eth/protocols/eth/handler.go
  eth/protocols/eth/handlers.go
  eth/protocols/eth/peer.go
  eth/protocols/eth/peer_test.go
  eth/protocols/eth/protocol.go
  turbo/snapshotsync/block_reader.go
  turbo/snapshotsync/block_snapshots.go
  turbo/stages/mock_sentry.go
Labels: beta

#3187 Added mining for POS
  cmd/integration/commands/stages.go
  cmd/integration/commands/state_stages.go
  cmd/rpcdaemon/rpcdaemontest/test_util.go
  cmd/utils/flags.go
  eth/backend.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_finish.go
  ethdb/privateapi/all.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  params/mining.go
  turbo/cli/default_flags.go
  turbo/stages/mock_sentry.go
Labels: proof-of-stake

#3208 RLP: suspend parse errors from logs
  go.mod
  go.sum
Labels: beta

#3207 RLP: suspend parse errors from logs
  go.mod
  go.sum
Labels: beta-cherry-pick

#3212 Report Valid ExecutionStatus only after all stages
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/commands/eth_subscribe_test.go
  cmd/rpcdaemon/commands/send_transaction_test.go
  core/gen_genesis.go
  core/genesis.go
  eth/backend.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/ethbackend.go
  params/config.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
  turbo/stages/sentry_mock_test.go
  turbo/stages/stageloop.go
Labels: proof-of-stake

#3220 Eip4399 state test in cmd/evm
  cmd/evm/internal/t8ntool/execution.go
  cmd/evm/internal/t8ntool/gen_stenv.go
  cmd/evm/internal/t8ntool/transition.go
  cmd/evm/testdata/9/alloc.json
  cmd/evm/testdata/9/env.json
  cmd/evm/testdata/9/txs.json
Labels: proof-of-stake

#3217 Increase body download timeout
  eth/backend.go
  eth/ethconfig/config.go
Labels: beta

#3229 mdbx: fix gc "retry" issue (slowness of gc during commit)
  go.mod
  go.sum
Labels: beta

#3230 mdbx: fix gc "retry" issue (slowness of gc during commit)
  go.mod
  go.sum
Labels: beta-cherry-pick

#3237 Increase body download timeout
  eth/backend.go
  eth/ethconfig/config.go
Labels: beta-cherry-pick

#3238 Update stable version to 2022.01.1
  params/version.go
Labels: beta-cherry-pick

#3246 [stable] Switch to erigon-lib stable
  go.mod
  go.sum
Labels: beta-cherry-pick

#3253 don't interrup stage bodies on first cycle
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_bodies.go
Labels: beta

#3242 Penalize for invalid rlp
  cmd/sentry/download/downloader.go
  rlp/decode.go
  turbo/txpool/p2p.go
Labels: beta-cherry-pick

#3232 [wip] penalize peer for invalid rlp
  cmd/sentry/sentry/downloader.go
  rlp/decode.go
Labels: beta

#3252 don't interrup stage bodies on first cycle
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_bodies.go
Labels: beta-cherry-pick

#3268 [stable] No empty RLPs in TxPacket messages, consistent parsing of Tx…
  go.mod
  go.sum
Labels: beta-cherry-pick

#3270 re-add line that was dropped from PR 3148
  turbo/transactions/tracing.go
Labels: beta-cherry-pick

#3271 [stable] Implement parity_listStorageKeys for current state
  cmd/rpcdaemon/commands/daemon.go
  cmd/rpcdaemon/commands/parity_api.go
  cmd/rpcdaemon/commands/parity_api_test.go
Labels: beta-cherry-pick

#3274 [stable] Simplify miner gas limit post EIP-1559. Default to 30M (#3205)
  cmd/integration/commands/flags.go
  cmd/utils/flags.go
  core/block_validator.go
  core/chain_makers.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_mining_create_block.go
  params/mining.go
  turbo/cli/default_flags.go
Labels: beta-cherry-pick

#3276 [stable] Update PriceBump, change tx replacement logic, update test
  go.mod
  go.sum
Labels: beta-cherry-pick

#3273 Transaction is nil
  cmd/rpcdaemon/commands/eth_txs.go
Labels: beta

#3301 Inverted lowestNum and highestNum in header downloader
  turbo/stages/headerdownload/header_algos.go
Labels: beta

#3303 [stable] Inverted lowestNum and highestNum in header downloader (#3301)
  turbo/stages/headerdownload/header_algos.go
Labels: beta-cherry-pick

#3305 [stable] Intersection mode for trace_filter
  cmd/rpcdaemon/commands/call_traces_test.go
  cmd/rpcdaemon/commands/trace_filtering.go
Labels: beta-cherry-pick

#3317 Enable Sentry to send "peer disconnected" event
  cmd/sentry/sentry/sentry.go
Labels: beta

#3320 [stable] Enable Sentry to send "peer disconnected" event (#3317)
  cmd/sentry/download/sentry.go
Labels: beta-cherry-pick

#3319 Enabled proposer by default
  cmd/utils/flags.go
  eth/backend.go
  ethdb/privateapi/ethbackend.go
  turbo/cli/default_flags.go
Labels: proof-of-stake

#3337 MDBX: Add recommendations to corruption error message
  go.mod
  go.sum
Labels: beta

#3338 MDBX: Add recommendations to corruption error message
  go.mod
  go.sum
Labels: beta-cherry-pick

#3343 Mdbx: configurable corrupt error recommendations
  go.mod
  go.sum
Labels: beta-cherry-pick

#3321 Add blockGasLimit to the state stream
  go.mod
  go.sum
  turbo/shards/state_change_accumulator.go
  turbo/stages/stageloop.go
Labels: beta

#3332 Separate Server For Engine API
  Dockerfile
  README.md
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/main.go
  docker-compose.yml
  node/defaults.go
Labels: proof-of-stake

#3346 Better downloader and txpool docs, support --txpool.trace.senders in external pool
  cmd/downloader/readme.md
  cmd/txpool/main.go
  cmd/txpool/readme.md
Labels: beta

#3347 Better downloader and txpool docs, support --txpool.trace.senders in external pool
  cmd/txpool/main.go
  cmd/txpool/readme.md
Labels: beta-cherry-pick

#3345 Added WatchTheBurn Stage and RPC Call to beta
  README.md
  cmd/rpcdaemon/commands/erigon_api.go
  cmd/rpcdaemon/commands/erigon_issuance.go
  cmd/utils/flags.go
  core/rawdb/accessors_chain.go
  eth/ethconfig/config.go
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_issuance.go
  eth/stagedsync/stage_issuance_test.go
  eth/stagedsync/stages/stages.go
  turbo/cli/default_flags.go
  turbo/stages/mock_sentry.go
  turbo/stages/stageloop.go
Labels: beta-cherry-pick

#3350 Fix sending transactions via txpool
  go.mod
  go.sum
  turbo/snapshotsync/block_snapshots.go
Labels: beta

#3370 fixed watchTheBurn output format
  cmd/rpcdaemon/commands/erigon_issuance.go
Labels: beta
