Repository erigontech/erigon, pull requests merged in 2023-07, with the labels that each got.

#7821 Separation of Engine from Ethbackend
  Makefile
  cl/phase1/execution_client/execution_client.go
  cl/phase1/execution_client/execution_engine.go
  cmd/caplin-phase1/main.go
  cmd/erigon-el-mock/server.go
  cmd/erigon-el/backend/backend.go
  cmd/erigon-el/backend/node.go
  cmd/erigon-el/eth1/execution.go
  cmd/erigon-el/main.go
  cmd/erigon-el/stages/stages.go
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/commands/corner_cases_support_test.go
  cmd/rpcdaemon/commands/daemon.go
  cmd/rpcdaemon/commands/debug_api_test.go
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/commands/engine_api_test.go
  cmd/rpcdaemon/commands/erigon_receipts_test.go
  cmd/rpcdaemon/commands/eth_api.go
  cmd/rpcdaemon/commands/eth_api_test.go
  cmd/rpcdaemon/commands/eth_block.go
  cmd/rpcdaemon/commands/eth_block_test.go
  cmd/rpcdaemon/commands/eth_callMany_test.go
  cmd/rpcdaemon/commands/eth_call_test.go
  cmd/rpcdaemon/commands/eth_filters_test.go
  cmd/rpcdaemon/commands/eth_mining_test.go
  cmd/rpcdaemon/commands/eth_subscribe_test.go
  cmd/rpcdaemon/commands/eth_system_test.go
  cmd/rpcdaemon/commands/send_transaction_test.go
  cmd/rpcdaemon/main.go
  cmd/rpcdaemon/rpcdaemontest/test_util.go
  cmd/rpcdaemon/rpcservices/engine_backend.go
  cmd/rpcdaemon/rpcservices/eth_backend.go
  cmd/sentry/sentry/sentry_multi_client.go
  eth/backend.go
  eth/stagedsync/stage_finish.go
  eth/stagedsync/stage_headers.go
  ethdb/privateapi/all.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
  turbo/engineapi/engine_helpers/constants.go
  turbo/engineapi/engine_helpers/fork_validator.go
  turbo/engineapi/engine_helpers/request_list.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_test.go
  turbo/rpchelper/interface.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock_sentry.go
  turbo/stages/sentry_mock_test.go
  turbo/stages/stageloop.go
Labels: consensus-separation

#7838 No need to ApplyDAOHardFork in sys calls
  core/blockchain.go
Labels: gnosis-chain

#7867 Add new Gnosis boot nodes
  params/bootnodes.go
Labels: gnosis-chain

#7874 Use EIP-4844 constants from erigon-lib
  cmd/sentinel/sentinel/service/start.go
  core/types/blob_tx_wrapper.go
  core/types/transaction_test.go
  crypto/kzg/kzg.go
  go.mod
  go.sum
  params/protocol_params.go
Labels: dencun

#7885 core/vm: move TSTORE,TLOAD to correct opcode nums
  core/vm/jump_table.go
  core/vm/opcodes.go
Labels: dencun

#7887 core/vm: implement EIP-5656, mcopy instruction
  core/vm/eips.go
  core/vm/gas_table.go
  core/vm/instructions_test.go
  core/vm/jump_table.go
  core/vm/memory.go
  core/vm/memory_table.go
  core/vm/memory_test.go
  core/vm/opcodes.go
Labels: dencun

#7890 Fix Gnosis sync from scratch
  consensus/aura/aura.go
Labels: gnosis-chain

#7937 EIP-4844: Rename "data gas" to "blob gas"
  accounts/abi/bind/backends/simulated.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_header.go
  cl/cltypes/eth1_header_test.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/transition/impl/eth2/utils.go
  cmd/integration/commands/state_domains.go
  cmd/state/commands/erigon4.go
  cmd/state/commands/opcode_tracer.go
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  consensus/misc/eip4844.go
  core/blockchain.go
  core/chain_makers.go
  core/error.go
  core/evm.go
  core/gaspool.go
  core/genesis_write.go
  core/state_processor.go
  core/state_transition.go
  core/types/blob_tx.go
  core/types/blob_tx_wrapper.go
  core/types/block.go
  core/types/gen_genesis.go
  core/types/genesis.go
  core/types/legacy_tx.go
  core/types/transaction.go
  core/types/transaction_marshalling.go
  core/types/transaction_test.go
  core/vm/evmtypes/evmtypes.go
  eth/stagedsync/stage_mining_exec.go
  eth/tracers/internal/tracetest/calltrace_test.go
  eth/tracers/internal/tracetest/prestate_test.go
  eth/tracers/tracers_test.go
  go.mod
  go.sum
  interfaces.go
  params/protocol_params.go
  tests/state_test_util.go
  turbo/adapter/ethapi/api.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_experimental.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/execution/eth1/block_building.go
  turbo/execution/eth1/eth1_utils/grpc.go
  turbo/jsonrpc/eth_api.go
  turbo/jsonrpc/eth_block.go
  turbo/jsonrpc/eth_call.go
  turbo/jsonrpc/eth_callMany.go
  turbo/jsonrpc/eth_receipts.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/otterscan_generic_tracer.go
  turbo/jsonrpc/otterscan_search_trace.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
  turbo/jsonrpc/tracing.go
  turbo/transactions/call.go
  turbo/transactions/tracing.go
Labels: dencun

#7940 Update EIP-2537 and EIP-4844 precompile addresses
  core/vm/contracts.go
  core/vm/runtime/runtime_test.go
Labels: dencun

#7943 eip-4844: hive tests: RLP decode order and newPayloadV3 to expect versionedHashes
  cl/phase1/execution_client/execution_client_direct.go
  core/types/blob_tx_wrapper.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_experimental.go
  turbo/engineapi/interface.go
Labels: dencun

#7944 Fix TestBlobTxWrappedEncodeDecode
  core/types/blob_tx_wrapper.go
Labels: dencun

#7946 EIP-4844: Verify expectedBlobVersionedHashes
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_experimental.go
Labels: dencun

#7947 EIP-4844: rename "data hash" to "blob hash"
  accounts/abi/bind/backends/simulated.go
  core/evm.go
  core/state_transition.go
  core/types/blob_tx.go
  core/types/blob_tx_wrapper.go
  core/types/legacy_tx.go
  core/types/transaction.go
  core/types/transaction_marshalling.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  core/vm/opcodes.go
  interfaces.go
  turbo/adapter/ethapi/api.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_experimental.go
  turbo/execution/eth1/block_building.go
  turbo/jsonrpc/eth_receipts.go
Labels: dencun
