Repository erigontech/erigon, pull requests merged in 2023-08, with the labels that each got.

#7952 EIP-4788: set nonce of beacon root history address to nonzero
  consensus/misc/eip4788.go
Labels: dencun

#7955 Fix newPayload parentBeaconBlockRoot check
  turbo/engineapi/engine_server.go
Labels: dencun

#7953 Introduce VerifyAbsenceOfCancunHeaderFields
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  consensus/misc/eip4844.go
Labels: dencun

#7963 dencun-devnet: --trusted-setup-file flag support
  cmd/utils/flags.go
  core/vm/contracts.go
  crypto/kzg/kzg.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
Labels: dencun

#7964 Replace --override.shanghaiTime flag with --override.cancun
  cmd/utils/flags.go
  core/genesis_write.go
  crypto/kzg/kzg.go
  eth/backend.go
  eth/ethconfig/config.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
Labels: dencun

#7969 Support engine_forkchoiceUpdatedV3 with ParentBeaconBlockRoot (EIP-4788)
  README.md
  cl/phase1/execution_client/rpc_helper/methods.go
  cmd/rpcdaemon/README.md
  core/block_builder_parameters.go
  eth/stagedsync/stage_mining_create_block.go
  go.mod
  go.sum
  rpc/errors.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/block_building.go
Labels: dencun

#7976 Implement EIP-6780: SELFDESTRUCT only in same transaction
  core/state/intra_block_state.go
  core/state/state_object.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  core/vm/instructions.go
  core/vm/jump_table.go
Labels: dencun

#7985 hive: minor fixes (EIP-4788)
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/execution/eth1/eth1_utils/grpc.go
Labels: dencun

#7997 Add parentBeaconBlockRoot to RPCMarshalHeader (EIP-4788)
  turbo/adapter/ethapi/api.go
Labels: dencun

#7999 Call InitializeBlockExecution in SpawnMiningExecStage (EIP-4788)
  cmd/state/exec3/state.go
  cmd/state/exec3/state_recon.go
  consensus/aura/aura.go
  consensus/aura/aura_test.go
  consensus/bor/bor.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  core/blockchain.go
  eth/stagedsync/stage_mining_exec.go
  turbo/jsonrpc/trace_filtering.go
  turbo/transactions/tracing.go
Labels: dencun

#8001 Add enough blob gas for block building (EIP-4844)
  cmd/state/exec3/state_recon.go
  eth/stagedsync/stage_mining_exec.go
Labels: dencun

#8002 Fix CopyTxs for BlobTxWrapper (EIP-4844)
  core/types/block.go
  core/types/block_test.go
  turbo/builder/latest_block_built.go
Labels: dencun

#7993 Added gnosis fields and removed body gap.
  cmd/sentinel/sentinel/handshake/handshake.go
  go.mod
  go.sum
  turbo/engineapi/engine_block_downloader/block_downloader.go
  turbo/engineapi/engine_block_downloader/core.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/execution/eth1/eth1_utils/grpc.go
  turbo/execution/eth1/inserters.go
Labels: gnosis-chain

#8010 Fix JSON marshalling of BlobsBundleV1 (EIP-4844)
  turbo/engineapi/engine_types/jsonrpc.go
Labels: dencun

#7989 Don't call AuRa Initialize after The Merge
  consensus/merge/merge.go
Labels: gnosis-chain

#8055 Revert "EIP-4788: set nonce of beacon root history address to nonzero…
  consensus/misc/eip4788.go
Labels: dencun

#8056 p2p: fix RLPx disconnect message decoding
  cmd/observer/observer/handshake.go
  p2p/peer.go
  p2p/transport.go
  p2p/transport_test.go
Labels: polygon

#8038 EIP-4788 v2 (no precompile)
  consensus/bor/bor.go
  consensus/merge/merge.go
  consensus/misc/eip4788.go
  consensus/misc/eip4788_test.go
  core/blockchain.go
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/evm.go
  core/vm/operations_acl.go
  params/protocol_params.go
  tests/exec_spec_test.go
Labels: dencun

#8074 Skip failing TestBlockchainEIP
  tests/block_test.go
Labels: dencun

#8062 sync: revert flawed dropUselessPeers logic and alleviate its issues
  cmd/integration/commands/stages.go
  cmd/sentry/sentry/sentry_multi_client.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  turbo/cli/default_flags.go
  turbo/stages/mock/mock_sentry.go
Labels: polygon

#8077 bor: more mumbai bootnodes
  params/bootnodes.go
Labels: polygon

#8096 Bor mining benchmark
  .gitignore
  consensus/bor/bor.go
  consensus/bor/heimdall/span/spanner.go
  consensus/bor/heimdall/span/testValidators.go
  eth/backend.go
  eth/stagedsync/stage_mining_exec.go
  go.mod
  go.sum
  params/networkname/network_name.go
  tests/bor/helper/miner.go
  tests/bor/mining_test.go
  tests/bor/testdata/genesis_2val.json
Labels: polygon
