Repository erigontech/erigon, pull requests merged in 2023-02, with the labels that each got.

#6760 Don't panic on some AuRa transactions in the past
  consensus/aura/aura.go
Labels: gnosis-chain

#6766 Fix hive after merging eth/68 PR
  cmd/erigon-el/backend/backend.go
  cmd/sentry/sentry/sentry_grpc_server.go
  eth/backend.go
Labels: cancun

#6768 added process Voluntary Exit
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/getters.go
  cmd/erigon-cl/core/state/mutators.go
  cmd/erigon-cl/core/state/mutators_test.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/transition/operations.go
  cmd/erigon-cl/core/transition/operations_test.go
  cmd/erigon-cl/core/transition/process_slashings.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/erigon-cl/core/transition/process_sync_aggregate.go
  cmd/erigon-cl/core/transition/processing.go
  cmd/erigon-cl/core/transition/processing_test.go
Labels: erigon-cl

#6785 Validate params of GetPayloadBodiesByHash and ByRange
  cmd/rpcdaemon/commands/engine_api.go
  ethdb/privateapi/ethbackend.go
  rpc/errors.go
  rpc/handler.go
Labels: shanghai

#6792 Added Optimizations to Beacon state transition.
  cl/cltypes/eth1_data.go
  cl/utils/bytes.go
  cl/utils/crypto.go
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/accessors_test.go
  cmd/erigon-cl/core/state/mutators_test.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/state/state.go
  cmd/erigon-cl/core/transition/block_transition.go
  cmd/erigon-cl/core/transition/finalization_and_justification.go
  cmd/erigon-cl/core/transition/finalization_and_justification_test.go
  cmd/erigon-cl/core/transition/operations.go
  cmd/erigon-cl/core/transition/operations_test.go
  cmd/erigon-cl/core/transition/process_attestations.go
  cmd/erigon-cl/core/transition/process_slashings_test.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/erigon-cl/core/transition/processing.go
  cmd/erigon-cl/core/transition/processing_test.go
  cmd/erigon-cl/stages/stages_beacon_state.go
  go.mod
  go.sum
Labels: erigon-cl

#6822 Added effective balances processing
  cmd/erigon-cl/core/transition/process_effective_balance_update.go
  cmd/erigon-cl/core/transition/process_epoch_test.go
  cmd/erigon-cl/core/transition/test_data/effective_balances_expected.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/effective_balances_test_state.ssz_snappy
Labels: erigon-cl

#6823 added processing of historical roots
  cl/utils/merkle.go
  cmd/erigon-cl/core/state/root.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/transition/process_epoch_test.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/erigon-cl/core/transition/test_data/historical_roots_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/historical_roots_state_test.ssz_snappy
Labels: erigon-cl

#6832 Added processing of flag indexes updates
  cmd/erigon-cl/core/transition/process_epoch_test.go
  cmd/erigon-cl/core/transition/resets.go
  cmd/erigon-cl/core/transition/test_data/participation_flag_updates_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/participation_flag_updates_state_test.ssz_snappy
Labels: erigon-cl

#6835 Schedule Shanghai fork on Sepolia
  core/forkid/forkid_test.go
  params/chainspecs/sepolia.json
Labels: shanghai

#6838 added better tests to epoch transitions
  cl/utils/math.go
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/getters.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/transition/finalization_and_justification_test.go
  cmd/erigon-cl/core/transition/process_epoch_test.go
  cmd/erigon-cl/core/transition/process_inactivity_scores.go
  cmd/erigon-cl/core/transition/process_slashings_test.go
  cmd/erigon-cl/core/transition/resets_test.go
  cmd/erigon-cl/core/transition/test_data/eth1_data_reset_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/eth1_data_reset_state_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/inactivity_scores_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/inactivity_scores_state_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/justification_and_finality_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/justification_and_finality_state_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/randao_mixes_reset_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/randao_mixes_reset_state_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/slashings_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/slashings_reset_expected_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/slashings_reset_state_test.ssz_snappy
  cmd/erigon-cl/core/transition/test_data/slashings_state_test.ssz_snappy
Labels: erigon-cl

#6842 added epoch processing to CL
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/mutators.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/state/state.go
  cmd/erigon-cl/core/transition/process_epoch.go
  cmd/erigon-cl/core/transition/process_registry_updates.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/erigon-cl/stages/stages_beacon_state.go
Labels: erigon-cl

#6844 various optimizations to state transition and epoch in particular
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/state.go
  cmd/erigon-cl/core/transition/process_attestations.go
  cmd/erigon-cl/core/transition/process_inactivity_scores.go
  cmd/erigon-cl/core/transition/process_rewards_and_penalties.go
  cmd/erigon-cl/stages/stages_beacon_state.go
Labels: erigon-cl

#6865 Added more peer count logs
  cmd/lightclient/lightclient/checkpoint.go
Labels: lightclient

#6872 Update Chiado bootnodes
  params/bootnodes.go
Labels: gnosis-chain

#6873 [AuRa] Enable EIP-170 when EIP-3860 is enabled
  core/vm/evm.go
Labels: gnosis-chain

#6875 blockValue should use gasUsed rather than gasLimit
  cmd/erigon-el/backend/backend.go
  cmd/rpcdaemon/commands/engine_api.go
  core/types/block.go
  eth/backend.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_finish.go
  ethdb/privateapi/ethbackend.go
  turbo/builder/block_builder.go
Labels: shanghai

#6883 API in lightclient instead of gossip
  cmd/lightclient/lightclient/lightclient.go
  cmd/lightclient/lightclient/subscriber.go
Labels: lightclient, erigon-cl

#6884 added static peers flag
  cl/clparams/config.go
  cmd/sentinel/cli/cliSettings.go
  cmd/sentinel/cli/flags/defaultFlags.go
  cmd/sentinel/cli/flags/flags.go
  cmd/sentinel/sentinel/discovery.go
Labels: lightclient, erigon-cl

#6886 Chiado snapshots
  turbo/snapshotsync/snapcfg/util.go
Labels: gnosis-chain

#6788 feat: add Gnosis and Chiado to CL
  cl/clparams/config.go
  cl/clparams/config_test.go
Labels: gnosis-chain

#6893 Body downloader: fix empty withdrawals in empty bodies
  turbo/stages/bodydownload/body_algos.go
Labels: shanghai

#6920 Schedule Capella on Sepolia
  cl/clparams/config.go
Labels: lightclient, shapella

#6918 Don't use embedded CL by default for Gnosis
  cl/clparams/config.go
  cmd/utils/flags.go
Labels: gnosis-chain, lightclient

#6940 Withdrawals on Gnosis Chain
  consensus/aura/aura.go
  consensus/aura/config.go
  consensus/aura/contracts/embed.go
  consensus/aura/contracts/withdrawal.json
  consensus/serenity/serenity.go
Labels: gnosis-chain

#6949 Fixed sanity consensus tests for slots processing
  cl/clparams/config.go
  cl/cltypes/attestations.go
  cl/cltypes/checkpoint.go
  cl/cltypes/validator.go
  cl/utils/set.go
  cmd/ef-tests-cl/run.sh
  cmd/ef-tests-cl/sanity.go
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/mutators.go
  cmd/erigon-cl/core/state/mutators_test.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/transition/block_transition.go
  cmd/erigon-cl/core/transition/operations.go
  cmd/erigon-cl/core/transition/process_attestations.go
  cmd/erigon-cl/core/transition/process_slots.go
Labels: erigon-cl

#6950 added empty slots sanity tests
  cmd/ef-tests-cl/collection.go
  cmd/ef-tests-cl/sanity.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/erigon-cl/core/transition/process_slots_test.go
Labels: erigon-cl

#6957 fixed lightclient regression
  cmd/lightclient/lightclient/lightclient.go
  cmd/lightclient/lightclient/subscriber.go
Labels: lightclient

#6941 handle nil update return values without panic
  cmd/sentinel/sentinel/handlers/lightclient.go
Labels: lightclient

#6965 Added capella SSZ tests
  cl/cltypes/lightclient_test.go
  cl/cltypes/tests/light_client_bootstrap.ssz_snappy
  cl/cltypes/tests/light_client_finality.ssz_snappy
  cl/cltypes/tests/light_client_optimistic.ssz_snappy
  cl/cltypes/tests/light_client_update.ssz_snappy
  cmd/erigon-cl/core/state/ssz_test.go
  cmd/erigon-cl/core/state/tests/capella.ssz_snappy
Labels: shapella
