Repository erigontech/erigon, pull requests merged in 2023-05, with the labels that each got.

#7405 Implement EIP-1153 transient storage
  accounts/abi/bind/backends/simulated.go
  cmd/integration/commands/state_domains.go
  cmd/rpcdaemon/commands/eth_callMany.go
  cmd/rpcdaemon/commands/eth_receipts.go
  cmd/rpcdaemon/commands/otterscan_generic_tracer.go
  cmd/rpcdaemon/commands/otterscan_search_trace.go
  cmd/rpcdaemon/commands/trace_adhoc.go
  cmd/rpcdaemon/commands/trace_filtering.go
  cmd/rpcdaemon/commands/tracing.go
  cmd/state/commands/erigon4.go
  cmd/state/commands/history22.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/state.go
  cmd/state/exec3/state_recon.go
  core/blockchain.go
  core/chain_makers.go
  core/state/intra_block_state.go
  core/state/intra_block_state_test.go
  core/state/journal.go
  core/state/transient_storage.go
  core/state_transition.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  core/vm/instructions_test.go
  core/vm/opcodes.go
  core/vm/runtime/runtime.go
  eth/stagedsync/stage_mining_exec.go
  eth/state_accessor.go
  turbo/transactions/tracing.go
Labels: dencun

#7447 Caplin: fixed dereferencing
  cmd/erigon-cl/forkchoice/fork_graph/fork_graph.go
  cmd/sentinel/cli/cliSettings.go
  cmd/sentinel/cli/flags/defaultFlags.go
  cmd/sentinel/cli/flags/flags.go
Labels: erigon-cl

#7420 Deneb container changes beacon-chain
  cl/clparams/config.go
  cl/clparams/version.go
  cl/cltypes/attestations.go
  cl/cltypes/beacon_blob_side_car.go
  cl/cltypes/beacon_blob_side_car_test.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/bls_to_execution_change.go
  cl/cltypes/checkpoint.go
  cl/cltypes/clone.go
  cl/cltypes/deltas.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_data.go
  cl/cltypes/eth1_header.go
  cl/cltypes/fork.go
  cl/cltypes/historical_summary.go
  cl/cltypes/validator.go
  cmd/ef-tests-cl/consensus_tests/appendix.go
  cmd/erigon-cl/core/state/raw/ssz.go
  cmd/evm/internal/t8ntool/gen_stenv.go
  core/types/withdrawal.go
Labels: erigon-cl, dencun

#7453 Added dencun networking
  cl/cltypes/beacon_blob_side_car.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/clone.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_header.go
  cmd/ef-tests-cl/consensus_tests/appendix.go
  cmd/ef-tests-cl/consensus_tests/forks.go
  cmd/erigon-cl/core/state/raw/ssz.go
  cmd/erigon-cl/core/state/upgrade.go
  cmd/erigon-cl/core/transition/process_slots.go
  cmd/sentinel/sentinel/communication/send_request.go
  cmd/sentinel/sentinel/communication/topics.go
  cmd/sentinel/sentinel/pubsub.go
  cmd/sentinel/sentinel/service/notifiers.go
  cmd/sentinel/sentinel/service/service.go
  cmd/sentinel/sentinel/service/start.go
  go.mod
  go.sum
Labels: erigon-cl, dencun

#7473 Proper Gnosis Chain rewards in trace_block
  cmd/erigon-el/backend/backend.go
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/commands/trace_filtering.go
  cmd/rpcdaemon/commands/tracing.go
  cmd/state/commands/erigon4.go
  cmd/state/exec3/state.go
  cmd/state/exec3/state_recon.go
  consensus/aura/aura.go
  consensus/aura/aurainterfaces/interface.go
  consensus/bor/bor.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/ethash/consensus.go
  consensus/serenity/serenity.go
  core/blockchain.go
  core/genesis_write.go
  core/state_processor.go
  eth/backend.go
  eth/ethconsensusconfig/config.go
  tests/block_test_util.go
  turbo/stages/mock_sentry.go
  turbo/stages/sentry_mock_test.go
  turbo/transactions/tracing.go
Labels: gnosis-chain

#7474 Cancun cannot happen before Merge
  consensus/clique/clique.go
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
Labels: dencun

#7475 Rename Serenity consensus engine to Merge
  cl/cltypes/eth1_block.go
  cmd/erigon-el/backend/backend.go
  cmd/evm/internal/t8ntool/transition.go
  consensus/merge/merge.go
  consensus/merge/merge_test.go
  core/chain_makers.go
  core/evm.go
  core/genesis_write.go
  eth/backend.go
  eth/ethconsensusconfig/config.go
  ethdb/privateapi/ethbackend.go
Labels: proof-of-stake

#7518 Schedule Shapella on Chiado
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/chiado.json
Labels: gnosis-chain, shapella

#7514 eip-4844: vm and engine_api extensions, minor fixes/changes
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/commands/eth_receipts.go
  cmd/rpcdaemon/commands/txpool_api.go
  core/evm.go
  core/state_transition.go
  core/vm/contracts.go
  core/vm/eips.go
  core/vm/evm.go
  core/vm/jump_table.go
  go.mod
  go.sum
Labels: dencun

#7567 Skip gas limit checks for chains with gas limit contract
  consensus/aura/aura.go
  consensus/bor/bor.go
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  consensus/misc/eip1559.go
  consensus/misc/eip1559_test.go
Labels: gnosis-chain

#7575 Amend ShanghaiTime for Chiado
  params/chainspecs/chiado.json
Labels: gnosis-chain

#7576 Fix fork ID test for Chiado
  core/forkid/forkid_test.go
Labels: gnosis-chain

#7580 Fix Gnosis rewards in trace_block and trace_filter
  cmd/rpcdaemon/commands/trace_adhoc.go
  cmd/rpcdaemon/commands/trace_filtering.go
Labels: gnosis-chain
