Repository erigontech/erigon, pull requests merged in 2023-01, with the labels that each got.

#6483 Added EL <-> CL integration
  cl/cltypes/block.go
  cl/cltypes/execution_payload.go
  cmd/erigon-cl/core/rawdb/config.go
  cmd/erigon-cl/execution_client/execution_client.go
  cmd/erigon-cl/main.go
  cmd/erigon-cl/stages/stage_beacon_blocks.go
  cmd/erigon-cl/stages/stage_history_reconstruction.go
  cmd/erigon-cl/stages/stages.go
  cmd/erigon-cl/stages/stages_beacon_state.go
  cmd/erigon-el/backend/backend.go
  cmd/erigon-el/eth1/execution.go
  cmd/sentinel/cli/cliSettings.go
  cmd/sentinel/cli/flags/defaultFlags.go
  cmd/sentinel/cli/flags/flags.go
Labels: erigon-cl

#6496 Withdrawals in body downloader
  cmd/sentry/sentry/sentry_multi_client.go
  eth/protocols/eth/protocol.go
  turbo/stages/bodydownload/body_algos.go
  turbo/stages/bodydownload/body_data_struct.go
Labels: shanghai

#6504 added EL-CL insertion batches system
  cmd/erigon-cl/execution_client/execution_client.go
  cmd/erigon-cl/execution_client/insert_batch.go
  cmd/erigon-cl/stages/stage_beacon_blocks.go
  cmd/erigon-cl/stages/stage_history_reconstruction.go
  cmd/erigon-el/backend/backend.go
  cmd/erigon-el/eth1/execution.go
Labels: erigon-cl

#6520 [First PR] Removing FastSSZ and use more efficient hashing with gohashtree
  cl/cltypes/Makefile
  cl/cltypes/attestation_encoding.go
  cl/cltypes/attestations.go
  cl/cltypes/attestations_test.go
  cl/cltypes/block.go
  cl/cltypes/checkpoint.go
  cl/cltypes/checkpoint_test.go
  cl/cltypes/clone.go
  cl/cltypes/eth1_data.go
  cl/cltypes/eth1_data_test.go
  cl/cltypes/network.go
  cl/cltypes/network_encoding.go
  cl/cltypes/network_test.go
  cl/cltypes/ssz_utils/ssz.go
  cl/cltypes/types.go
  cl/cltypes/types_encoding.go
  cl/fork/fork.go
  cl/merkle_tree/chunk.go
  cl/merkle_tree/list.go
  cl/merkle_tree/merkle_root.go
  cl/merkle_tree/merkle_root_test.go
  cl/merkle_tree/primitives.go
  cl/merkle_tree/zero.go
  cl/rpc/rpc.go
  cl/utils/bytes.go
  cl/utils/bytes_test.go
  cmd/erigon-cl/core/rawdb/accessors_test.go
  cmd/erigon-cl/core/state/getters.go
  cmd/erigon-cl/core/state/root.go
  cmd/erigon-cl/core/state/state_encoding/encoding.go
  cmd/erigon-cl/core/state/state_encoding/encoding_test.go
  cmd/erigon-cl/core/state/state_encoding/participations.go
  cmd/erigon-cl/core/transition/beacon_state_utils.go
  cmd/erigon-cl/network/beacon_downloader.go
  cmd/erigon-cl/network/gossip_manager.go
  cmd/sentinel/main.go
  cmd/sentinel/sentinel/communication/ssz_snappy/encoding.go
  cmd/sentinel/sentinel/handlers/handlers.go
  cmd/sentinel/sentinel/handlers/heartbeats.go
  cmd/sentinel/sentinel/handshake/handshake.go
  cmd/sentinel/sentinel/sentinel.go
Labels: erigon-cl

#6516 Gnosis block snapshots
  go.mod
  go.sum
  turbo/snapshotsync/snapcfg/util.go
Labels: gnosis-chain

#6524 ExecutionPayloaHeader: ssz support for withdrawals root
  cl/cltypes/aggregate.go
  cl/cltypes/aggregate_test.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_header.go
  cl/cltypes/ssz_utils/ssz.go
  cl/cltypes/types.go
  cl/cltypes/types_encoding.go
  cl/cltypes/validator.go
  cl/merkle_tree/primitives.go
  cmd/erigon-cl/core/state/getters.go
  cmd/erigon-cl/core/state/root.go
  cmd/erigon-cl/core/state/root_test.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/state/state.go
  cmd/erigon-cl/core/transition/beacon_state_utils_test.go
  cmd/erigon-cl/core/transition/process_slots_test.go
  cmd/erigon-cl/network/beacon_downloader.go
  cmd/erigon-cl/network/gossip_manager.go
  cmd/erigon-cl/stages/stage_history_reconstruction.go
  core/types/block.go
Labels: shanghai, erigon-cl

#6538 added SSZ encodings for withdrawals
  core/types/withdrawal.go
  core/types/withdrawal_test.go
Labels: shanghai, erigon-cl

#6568 Switch validateAndStorePayload to Body.RawBody()
  core/types/block.go
  turbo/engineapi/fork_validator.go
  turbo/stages/bodydownload/prefetched_blocks.go
Labels: shanghai

#6578 Withdrawal amount in GWei
  cmd/erigon-el/eth1/execution.go
  consensus/serenity/serenity.go
  core/rawdb/accessors_chain_test.go
  core/types/block_test.go
  core/types/gen_withdrawal_json.go
  core/types/withdrawal.go
  core/types/withdrawal_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
  tests/block_test.go
  tests/exec_spec_test.go
Labels: shanghai

#6499 txpool changes for eip-3860
  cmd/utils/flags.go
  core/tx_pool.go
  turbo/stages/mock_sentry.go
Labels: shanghai

#6604 Allow NewPayloadV2 for pre-Shanghai blocks
  ethdb/privateapi/ethbackend.go
Labels: shanghai

#6617 Gnosis Chain in README
  README.md
Labels: gnosis-chain

#6614 Fast gossip routine for Sentinel.
  cl/cltypes/beacon_block_test.go
  cl/cltypes/lightclient.go
  cl/cltypes/network_test.go
  cl/cltypes/types.go
  cl/cltypes/types_encoding.go
  cl/cltypes/validator.go
  cmd/erigon-cl/core/state/root.go
  cmd/erigon-cl/core/state/root_test.go
  cmd/lightclient/lightclient/store.go
  cmd/lightclient/lightclient/verify.go
  cmd/lightclient/main.go
  cmd/sentinel/sentinel/communication/packet.go
  cmd/sentinel/sentinel/communication/ssz_snappy/gossip.go
  cmd/sentinel/sentinel/gossip.go
  cmd/sentinel/sentinel/pubsub.go
  cmd/sentinel/sentinel/pubsub_test.go
  cmd/sentinel/sentinel/sentinel.go
  cmd/sentinel/sentinel/service/service.go
Labels: erigon-cl

#6618 fix: payload version error return
  ethdb/privateapi/ethbackend.go
Labels: shanghai

#6638 Unify Engine API V1 & V2 methods
  cmd/lightclient/lightclient/execution.go
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/rpcservices/eth_backend.go
  ethdb/privateapi/engine_test.go
  ethdb/privateapi/ethbackend.go
  go.mod
  go.sum
  turbo/rpchelper/interface.go
Labels: shanghai

#6658 Added Historical Summary and FromBlsToExecution
  cl/cltypes/bls_to_execution_change.go
  cl/cltypes/bls_to_execution_test.go
  cl/cltypes/clone.go
  cl/cltypes/historical_summary.go
  cl/cltypes/historical_summary_test.go
  cmd/rpcdaemon/commands/otterscan_api.go
  cmd/rpcdaemon/commands/trace_filtering.go
  cmd/sentinel/main.go
Labels: lightclient, shanghai, erigon-cl

#6665 added support for Capella beacon blocks
  cl/clparams/config.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/bls_to_execution_change.go
  cl/cltypes/eth1_block.go
  cl/fork/id.go
  cmd/erigon-cl/stages/stage_history_reconstruction.go
  cmd/sentinel/sentinel/pubsub.go
Labels: lightclient, shanghai, erigon-cl

#6671 Replace INVALID_BLOCK_HASH with INVALID
  ethdb/privateapi/ethbackend.go
Labels: shanghai

#6644 engine payload bodies rpc endpoints
  cmd/rpcdaemon/commands/engine_api.go
  cmd/rpcdaemon/rpcservices/eth_backend.go
  ethdb/privateapi/ethbackend.go
  turbo/rpchelper/interface.go
Labels: shanghai

#6695 introduce engine_getCapabilities
  cmd/rpcdaemon/commands/engine_api.go
Labels: shanghai

#6699 Added checkpoints and justification bits processing (post-altair)
  cl/clparams/config.go
  cl/cltypes/justification_bits.go
  cl/cltypes/justification_bits_test.go
  cl/cltypes/participation_flags.go
  cl/cltypes/participation_flags_test.go
  cl/cltypes/validator.go
  cmd/erigon-cl/core/checkpoint.go
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/accessors_test.go
  cmd/erigon-cl/core/state/getters.go
  cmd/erigon-cl/core/state/root.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/state/ssz.go
  cmd/erigon-cl/core/state/state.go
  cmd/erigon-cl/core/state/test_util.go
  cmd/erigon-cl/core/transition/finalization_and_justification.go
  cmd/erigon-cl/core/transition/finalization_and_justification_test.go
Labels: erigon-cl

#6746 Added processing for deposits
  cl/cltypes/beacon_block_test.go
  cl/cltypes/validator.go
  cmd/erigon-cl/core/state/accessors.go
  cmd/erigon-cl/core/state/setters.go
  cmd/erigon-cl/core/transition/operations.go
  cmd/erigon-cl/core/transition/operations_test.go
Labels: erigon-cl
