Repository erigontech/erigon, pull requests merged in 2023-09, with the labels that each got.

#8004 Txpool upgrades for EIP-4844 Blob Transactions
  cmd/txpool/main.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/tx_pool.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
  turbo/shards/state_change_accumulator.go
  turbo/stages/stageloop.go
Labels: dencun

#8172 Get vote on hash
  .github/workflows/ci.yml
  .gitignore
  cmd/devnet/services/polygon/heimdall.go
  cmd/rpcdaemon/README.md
  consensus/bor/api.go
  consensus/bor/bor_test.go
  consensus/bor/heimall.go
  consensus/bor/heimdall/client.go
  consensus/bor/heimdall/metrics.go
  consensus/bor/heimdall/milestone/milestone.go
  consensus/bor/heimdallgrpc/milestone.go
  eth/backend.go
  eth/borfinality/api.go
  eth/borfinality/bor_checkpoint_verifier.go
  eth/borfinality/flags/flags.go
  eth/borfinality/generics/generics.go
  eth/borfinality/rawdb/checkpoint.go
  eth/borfinality/rawdb/milestone.go
  eth/borfinality/whitelist.go
  eth/borfinality/whitelist/checkpoint.go
  eth/borfinality/whitelist/finality.go
  eth/borfinality/whitelist/milestone.go
  eth/borfinality/whitelist/service.go
  eth/borfinality/whitelist/service_test.go
  eth/borfinality/whitelist_helpers.go
  go.mod
  go.sum
  metrics/exp.go
Labels: polygon

#8187 Milestone stage processing
  .gitignore
  cmd/integration/commands/stages.go
  cmd/utils/flags.go
  consensus/bor/api.go
  consensus/bor/bor.go
  consensus/bor/heimdall/client.go
  consensus/bor/heimdall/heimall.go
  consensus/bor/heimdallgrpc/server.go
  eth/backend.go
  eth/borfinality/flags/flags.go
  eth/borfinality/whitelist.go
  eth/borfinality/whitelist_helpers.go
  eth/ethconfig/config.go
  eth/ethconsensusconfig/config.go
  eth/stagedsync/stage_bor_heimdall.go
  turbo/cli/default_flags.go
  turbo/engineapi/engine_helpers/fork_validator.go
  turbo/jsonrpc/bor_snapshot.go
  turbo/jsonrpc/erigon_system.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/headerdownload/header_data_struct.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: polygon

#8231 Implement EIP-7516: BLOBBASEFEE opcode
  core/state_transition.go
  core/vm/eips.go
  core/vm/jump_table.go
  core/vm/opcodes.go
Labels: dencun

#8213 Txpool 4844 upgrades Part 2
  cmd/txpool/main.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/tx_pool.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
  turbo/shards/state_change_accumulator.go
  turbo/stages/stageloop.go
Labels: dencun

#8247 fix finalized api for polygon chain
  eth/borfinality/api.go
  turbo/jsonrpc/erigon_system.go
  turbo/rpchelper/helper.go
Labels: polygon

#8259 Add engine_forkchoiceUpdatedV3 to engine_exchangeCapabilities
  turbo/engineapi/engine_server.go
Labels: dencun

#8269 Verify excessBlobGas (EIP-4844)
  consensus/merge/merge.go
  consensus/misc/eip1559.go
  tests/exec_spec_test.go
Labels: dencun

#8153 Rpcdaemon: fixed few bugs in erigon_getLatestLogs
  turbo/jsonrpc/erigon_receipts.go
Labels: bug

#8302 Bor break loop onrewind
  consensus/bor/heimdall/heimall.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_headers.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: polygon

#8305 Bor fix frozen snapshot load
  cmd/silkworm_api/snapshot_idx.go
  consensus/bor/bor.go
  consensus/bor/snapshot.go
Labels: polygon

#8329 Bor mainnet bootnode update
  params/bootnodes.go
Labels: polygon
