Repository erigontech/erigon, pull requests merged in 2023-04, with the labels that each got.

#7262 eip-4844: BlobTx and its components
  core/types/blob_tx_wrapper.go
  core/types/hashing.go
  core/types/signed_blob_tx.go
  core/types/transaction.go
  crypto/kzg/kzg.go
  go.mod
  go.sum
Labels: dencun

#7292 Revert "return [] instead of null for withdrawals (#7279)"
  turbo/adapter/ethapi/api.go
Labels: shapella

#7289 eip-4844: assigned value to excessDataGas, unused packages removed
  accounts/abi/bind/backends/simulated.go
  cmd/integration/commands/state_domains.go
  cmd/rpcdaemon/commands/eth_receipts.go
  cmd/rpcdaemon/commands/otterscan_generic_tracer.go
  cmd/rpcdaemon/commands/otterscan_search_trace.go
  cmd/rpcdaemon/commands/trace_filtering.go
  cmd/rpcdaemon/commands/tracing.go
  cmd/state/commands/erigon4.go
  cmd/state/commands/history22.go
  cmd/state/commands/opcode_tracer.go
  core/blockchain.go
  core/chain_makers.go
  core/evm.go
  eth/stagedsync/stage_mining_exec.go
  go.mod
  go.sum
  turbo/transactions/call.go
Labels: dencun

#7304 Shanghai update for evm tool
  cmd/evm/internal/t8ntool/execution.go
  cmd/evm/internal/t8ntool/flags.go
  cmd/evm/internal/t8ntool/gen_stenv.go
  cmd/evm/internal/t8ntool/transition.go
  cmd/evm/t8n_test.go
  cmd/evm/testdata/26/alloc.json
  cmd/evm/testdata/26/env.json
  cmd/evm/testdata/26/exp.json
  cmd/evm/testdata/26/txs.json
Labels: shapella

#7309 Update TestMainnetFork to Capella fork ID
  cl/fork/fork_test.go
Labels: shapella

#7312 Use Aura.PosdaoTransition rather than posdaoBlock for fork ID
  core/forkid/forkid.go
  params/chainspecs/chiado.json
  params/chainspecs/gnosis.json
Labels: gnosis-chain

#7308 eip-4844: setting header's excess_data_gas, verifiying eip-4844 headers
  accounts/abi/bind/backends/simulated.go
  consensus/clique/clique.go
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
  consensus/serenity/serenity.go
  core/blockchain.go
  core/chain_makers.go
  core/genesis_write.go
  eth/stagedsync/stage_mining_exec.go
  turbo/transactions/tracing.go
Labels: dencun

#7331 Support AuRaStep & AuRaSeal in genesis JSON
  core/types/gen_genesis.go
  core/types/genesis.go
Labels: gnosis-chain

#7332 Fix nil withdrawals in eth_getBlockByHash
  turbo/snapshotsync/block_reader.go
Labels: shapella

#7328 eip-4844: extensions to compute fees for data blobs
  accounts/abi/bind/backends/simulated.go
  core/state_transition.go
  core/types/transaction.go
  interfaces.go
Labels: dencun

#7385 eip-4844: receipts to include dataGasPrice and dataGasUsed
  cmd/rpcdaemon/commands/erigon_receipts.go
  cmd/rpcdaemon/commands/eth_receipts.go
  cmd/rpcdaemon/commands/graphql_api.go
  cmd/rpcdaemon/commands/otterscan_api.go
  cmd/rpcdaemon/commands/otterscan_search_trace.go
  core/state_processor.go
Labels: dencun

#7401 adding deneb p2p containers
  cl/cltypes/beacon_blob_side_car.go
  cl/cltypes/beacon_blob_side_car_test.go
Labels: dencun
