Repository erigontech/erigon, pull requests merged in 2023-11, with the labels that each got.

#8592 devnet: configuration fixes
  cmd/devnet/accounts/accounts.go
  cmd/devnet/args/node_args.go
  cmd/devnet/args/node_args_test.go
  cmd/devnet/devnet/context.go
  cmd/devnet/devnet/network.go
  cmd/devnet/devnet/node.go
  cmd/devnet/main.go
  cmd/devnet/requests/account.go
  cmd/devnet/requests/admin.go
  cmd/devnet/requests/block.go
  cmd/devnet/requests/event.go
  cmd/devnet/requests/request_generator.go
  cmd/devnet/requests/trace.go
  cmd/devnet/requests/transaction.go
  cmd/devnet/requests/tx.go
  cmd/devnet/services/accounts/faucet.go
  cmd/devnet/services/polygon/checkpoint.go
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/devnet/services/polygon/statesync.go
  cmd/devnet/transactions/tx.go
  cmd/utils/flags.go
  consensus/bor/bor.go
  params/config.go
  rpc/http.go
  rpc/websocket.go
Labels: devnet

#8527 p2p: silkworm sentry
  cmd/integration/commands/stages.go
  cmd/sentry/main.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/ethconfig/gen_config.go
  ethstats/ethstats.go
  p2p/sentry/eth_handshake.go
  p2p/sentry/eth_handshake_test.go
  p2p/sentry/sentry_grpc_server.go
  p2p/sentry/sentry_grpc_server_test.go
  p2p/sentry/sentry_multi_client/broadcast.go
  p2p/sentry/sentry_multi_client/sentry_api.go
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  p2p/server.go
  tests/bor/helper/miner.go
  turbo/cli/default_flags.go
  turbo/silkworm/load.go
  turbo/silkworm/load_unix.go
  turbo/silkworm/load_windows.go
  turbo/silkworm/silkworm.go
  turbo/silkworm/silkworm_api.h
  turbo/silkworm/silkworm_api_bridge.h
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: silkworm

#8660 add rollback tx at GetVoteOnHash #8637
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#8661 Discovery zero refresh timer
  cl/sentinel/sentinel.go
  cmd/bootnode/main.go
  cmd/observer/observer/server.go
  erigon-lib/diagnostics/network.go
  erigon-lib/diagnostics/provider.go
  erigon-lib/diagnostics/provider_test.go
  eth/stagedsync/stage_headers.go
  p2p/dial.go
  p2p/discover/common.go
  p2p/discover/lookup.go
  p2p/discover/table.go
  p2p/discover/table_util_test.go
  p2p/discover/v4_udp.go
  p2p/discover/v4_udp_test.go
  p2p/discover/v5_udp.go
  p2p/discover/v5_udp_test.go
  p2p/peer.go
  p2p/peer_test.go
  p2p/server.go
  turbo/stages/headerdownload/header_algos.go
Labels: polygon

#8616 headerdownload: handle tie breaker for forkchoice in pow networks
  turbo/stages/headerdownload/header_algo_test.go
  turbo/stages/headerdownload/header_algos.go
Labels: polygon

#8671 bor: update mumbai bootnodes
  params/bootnodes.go
  params/bootnodes_mumbai.go
Labels: polygon

#8751 Bor proofgen tests
  cl/merkle_tree/merkle_root.go
  cmd/devnet/blocks/fees.go
  cmd/devnet/blocks/generator.go
  cmd/devnet/blocks/waiter.go
  cmd/devnet/contracts/rootreceiver.sol
  cmd/devnet/contracts/steps/subscriber.go
  cmd/devnet/requests/account.go
  cmd/devnet/requests/admin.go
  cmd/devnet/requests/block.go
  cmd/devnet/requests/event.go
  cmd/devnet/requests/nopgenerator.go
  cmd/devnet/requests/request_generator.go
  cmd/devnet/requests/trace.go
  cmd/devnet/requests/transaction.go
  cmd/devnet/requests/tx.go
  cmd/devnet/services/polygon/checkpoint.go
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  consensus/bor/bor.go
  rpc/types.go
  tests/statedb_insert_chain_transaction_test.go
  turbo/jsonrpc/eth_api.go
  turbo/jsonrpc/eth_txs.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/otterscan_search_trace.go
Labels: polygon

#8764 Bor proof findpath
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  turbo/trie/trie.go
Labels: polygon

#8675 silkworm: internal refactorings
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  turbo/cli/default_flags.go
  turbo/silkworm/silkworm.go
  turbo/silkworm/silkworm_api.h
  turbo/silkworm/silkworm_api_bridge.h
  turbo/silkworm/snapshot_types.go
Labels: silkworm

#8792 bor: don't hide `ctx.Err()`
  consensus/bor/finality/bor_verifier.go
  consensus/bor/heimdall/client.go
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#8815 Return difficulty check into bor header validation
  consensus/bor/snapshot.go
Labels: polygon

#8801 Bor: increase client timeout from 5 to 10sec (to cover remote server case)
  consensus/bor/finality/bor_verifier.go
  consensus/bor/finality/whitelist_helpers.go
  consensus/bor/heimdall/client.go
  consensus/bor/heimdallgrpc/server.go
Labels: polygon

#8037 Added TxDependency Metadata to ExtraData in Block Header in Bor for Block-STM
  consensus/bor/bor.go
  consensus/bor/snapshot.go
  core/types/block.go
  core/types/block_test.go
  erigon-lib/chain/chain_config.go
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#8820 webseed: .torrent file validation must check - fileName and hash
  erigon-lib/downloader/downloader.go
  erigon-lib/downloader/downloadercfg/downloadercfg.go
  erigon-lib/downloader/webseed.go
Labels: release-blocker

#8674 Add support for amoy testnet
  README.md
  common/paths/paths.go
  core/allocs/amoy.json
  core/forkid/forkid_test.go
  core/genesis_write.go
  core/system_contract_lookup.go
  erigon-lib/chain/networkname/network_name.go
  erigon-lib/chain/snapcfg/util.go
  eth/ethconfig/config.go
  params/bootnodes.go
  params/chainspecs/amoy.json
  params/config.go
  params/config_test.go
  turbo/node/node.go
  turbo/stages/genesis_test.go
Labels: polygon

#8829 silkworm: use silkworm-go bindings
  .github/workflows/ci.yml
  .github/workflows/test-integration-caplin.yml
  .github/workflows/test-integration.yml
  Dockerfile
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_execute.go
  go.mod
  go.sum
  turbo/cli/default_flags.go
  turbo/silkworm/load_unix.go
  turbo/silkworm/load_windows.go
  turbo/silkworm/silkworm.go
  turbo/silkworm/silkworm_api.h
  turbo/silkworm/silkworm_api_bridge.h
  turbo/silkworm/silkworm_go_devenv.sh
  turbo/silkworm/snapshot_types.go
Labels: silkworm

#8869 flags: bump default value of db.size.limit to 8TB
  cmd/utils/flags.go
Labels: polygon

#8870 silkworm: disable on arm64 Linux
  go.mod
  go.sum
Labels: silkworm
