Repository erigontech/erigon, pull requests merged in 2023-12, with the labels that each got.

#8878 FIx outstanding know header==nil errors + reduce bor heimdall logging
  consensus/bor/finality/whitelist.go
  consensus/bor/finality/whitelist_helpers.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_execute.go
Labels: polygon

#8889 flags: bump default value of db.size.limit to 12TB
  cmd/utils/flags.go
Labels: polygon

#8891 silkworm: macOS Intel library
  Makefile
  go.mod
  go.sum
Labels: silkworm

#8907 Update gnosis bootnodes
  params/bootnodes.go
Labels: gnosis

#8908 Fix snap initialization from frozen blocks
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#8893 silkworm: disable on incompatible Linux versions
  Makefile
  turbo/silkworm/silkworm_compat_check.sh
Labels: silkworm

#8955 Fix case when there are more than one matching libraries
  turbo/silkworm/silkworm_compat_check.sh
Labels: silkworm

#8229 Added a new RPC endpoint (bor_sendRawTransactionConditional) to support EIP-4337 Bundled Transactions
  core/state/intra_block_state.go
  core/state/intra_block_state_test.go
  core/types/block_test.go
  erigon-lib/common/hash.go
  erigon-lib/types/transaction_conditional.go
  erigon-lib/types/transaction_conditional_test.go
  turbo/jsonrpc/bor_api.go
  turbo/jsonrpc/bor_snapshot.go
  turbo/jsonrpc/daemon.go
Labels: polygon

#8989 borheimdall: add tests for state sync events persistence
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_bor_heimdall_test.go
  eth/stagedsync/test/harness.go
Labels: polygon

#9017 Astrid sync
  cmd/devnet/services/polygon/heimdall.go
  consensus/bor/bor_test.go
  consensus/bor/finality/whitelist_helpers.go
  consensus/bor/heimdall/client.go
  consensus/bor/heimdall/heimdall.go
  consensus/bor/heimdall/mock/heimdall_client_mock.go
  consensus/bor/heimdallgrpc/milestone.go
  polygon/sync/heimdall.go
  polygon/sync/heimdall_test.go
Labels: polygon

#9033 remove bor mainnet files
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: polygon

#9030 polygon/sync: implement header downloader
  polygon/sync/db.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/header_verifier.go
  polygon/sync/heimdall.go
  polygon/sync/heimdall_test.go
  polygon/sync/mock/db_mock.go
  polygon/sync/mock/heimdall_mock.go
  polygon/sync/mock/sentry_mock.go
  polygon/sync/peerinfo/peer_with_block_num_info.go
  polygon/sync/sentry.go
  polygon/sync/state_point.go
  polygon/sync/state_point_kind.go
  polygon/sync/state_points.go
Labels: polygon

#8940 Allow proxy paths in Heimdall URL
  consensus/bor/heimdall/client.go
Labels: polygon

#8885 Add `blocksByRange` & `blocksByRoot` P2P rpc handlers
  cl/sentinel/handlers/blocks.go
  cl/sentinel/handlers/blocks_by_range_test.go
  cl/sentinel/handlers/blocks_by_root_test.go
  cl/sentinel/handlers/handlers.go
  cl/sentinel/handlers/utils_test.go
  cl/sentinel/sentinel.go
  cl/sentinel/service/start.go
  cmd/caplin/main.go
  cmd/sentinel/main.go
  eth/backend.go
Labels: caplin

#9014 Update Polygon storage requirements
  README.md
Labels: polygon
