Repository erigontech/erigon, pull requests merged in 2023-10, with the labels that each got.

#8331 Fix some hive tests
  turbo/engineapi/engine_helpers/fork_validator.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/interface.go
  turbo/stages/headerdownload/header_data_struct.go
Labels: dencun

#8342 Added fix to allow getroothash to work with no api running
  cmd/rpcdaemon/main.go
  consensus/bor/api.go
  consensus/bor/bor.go
  consensus/bor/snapshot.go
  eth/backend.go
  turbo/jsonrpc/bor_api.go
  turbo/jsonrpc/bor_helper.go
  turbo/jsonrpc/bor_snapshot.go
  turbo/jsonrpc/daemon.go
Labels: polygon

#8364 eth, consensus/bor: handle 503 response from heimdall
  consensus/bor/heimdall/client.go
  eth/borfinality/whitelist.go
  eth/borfinality/whitelist_helpers.go
Labels: polygon

#8380 Rewind fixes
  eth/stagedsync/stage_bor_heimdall.go
  turbo/rpchelper/helper.go
Labels: polygon

#8371 Remove CalcuttaBlock in favour of BlockAlloc
  consensus/bor/bor.go
  core/system_contract_lookup.go
  core/systemcontracts/const.go
  core/systemcontracts/upgrade.go
  core/types/genesis.go
  erigon-lib/chain/chain_config.go
  params/chainspecs/bor-devnet.json
  params/chainspecs/bor-mainnet.json
  params/chainspecs/mumbai.json
Labels: polygon

#8384 fix bor.milestone flag
  cmd/utils/flags.go
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#8385 make rpc consistent with bor
  turbo/jsonrpc/bor_api.go
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#8386 add milestone metrics
  eth/borfinality/bor_checkpoint_verifier.go
  eth/borfinality/whitelist/checkpoint.go
  eth/borfinality/whitelist/milestone.go
Labels: polygon

#8391 Fix bor receipts
  turbo/jsonrpc/eth_receipts.go
  turbo/jsonrpc/eth_txs.go
Labels: polygon

#8401 Bor reduce logging verbosity
  eth/borfinality/whitelist.go
  eth/borfinality/whitelist_helpers.go
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#8407 move borfinality package out of eth
  consensus/bor/bor.go
  consensus/bor/finality/api.go
  consensus/bor/finality/bor_verifier.go
  consensus/bor/finality/flags/flags.go
  consensus/bor/finality/generics/generics.go
  consensus/bor/finality/rawdb/checkpoint.go
  consensus/bor/finality/rawdb/milestone.go
  consensus/bor/finality/whitelist.go
  consensus/bor/finality/whitelist/checkpoint.go
  consensus/bor/finality/whitelist/finality.go
  consensus/bor/finality/whitelist/milestone.go
  consensus/bor/finality/whitelist/service.go
  consensus/bor/finality/whitelist/service_test.go
  consensus/bor/finality/whitelist_helpers.go
  consensus/bor/heimdall/heimall.go
  eth/backend.go
  eth/stagedsync/stage_bor_heimdall.go
  turbo/jsonrpc/bor_snapshot.go
  turbo/jsonrpc/erigon_system.go
  turbo/rpchelper/helper.go
  turbo/stages/stageloop.go
Labels: polygon

#8414 Check hash validity before milestone rewind
  cmd/integration/commands/state_stages.go
  eth/backend.go
  eth/stagedsync/exec3.go
  eth/stagedsync/stage.go
  eth/stagedsync/stage_bodies.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_execute.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_interhashes.go
  eth/stagedsync/stage_senders.go
  eth/stagedsync/sync.go
  eth/stagedsync/sync_test.go
  turbo/execution/eth1/forkchoice.go
  turbo/stages/headerdownload/header_algos.go
  turbo/stages/stageloop.go
Labels: polygon

#8413 Bor rpc config fix
  cmd/rpcdaemon/cli/config.go
  consensus/bor/bor.go
  consensus/bor/finality/whitelist.go
  eth/stagedsync/stage_mining_finish.go
  metrics/exp.go
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#8450 cmd/sentry: remove empty headers check
  cmd/sentry/sentry/sentry_multi_client.go
Labels: polygon

#8447 Add block producer progress check
  consensus/bor/bor.go
  eth/backend.go
Labels: polygon

#8464 Configure EIP-4844 parameters for Gnosis
  accounts/abi/bind/backends/simulated.go
  cmd/state/commands/opcode_tracer.go
  consensus/merge/merge.go
  consensus/misc/eip4844.go
  core/blockchain.go
  core/chain_makers.go
  core/state_transition.go
  core/types/blob_tx_wrapper.go
  core/vm/eips.go
  erigon-lib/chain/chain_config.go
  erigon-lib/common/fixedgas/protocol.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_fuzz_test.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpooluitl/all_components.go
  eth/backend.go
  eth/stagedsync/stage_mining_exec.go
  params/chainspecs/chiado.json
  params/chainspecs/gnosis.json
  params/protocol_params.go
  tests/state_test_util.go
  turbo/engineapi/engine_server.go
  turbo/jsonrpc/eth_receipts.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: gnosis, dencun

#8488 bor initFrozenSnapshot: parallel erecover
  consensus/bor/bor.go
Labels: polygon

#8503 Use Erigon execution for memory mutations
  eth/stagedsync/stage_execute.go
Labels: silkworm

#8486 Add RPC daemon using Silkworm
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/kv/kv_interface.go
  erigon-lib/kv/mdbx/kv_mdbx.go
  erigon-lib/kv/mdbx/kv_mdbx_temporary.go
  erigon-lib/kv/remotedb/kv_remote.go
  eth/backend.go
  go.mod
  go.sum
  turbo/silkworm/silkworm.go
Labels: silkworm

#8531 Switch to official KZG ceremony trusted setup (EIP-4844)
  core/vm/testdata/precompiles/pointEvaluation.json
  erigon-lib/crypto/kzg/kzg.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
  tests/exec_spec_test.go
Labels: dencun

#8532 Gnosis Snapshot updated
  cmd/caplin/caplin1/run.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: gnosis

#8202 Move validator set snapshot computation to bor_heimdall stage
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/rpcservices/eth_backend.go
  cmd/state/exec3/state.go
  consensus/bor/bor.go
  consensus/bor/bor_test.go
  consensus/bor/heimdall/span/spanner.go
  consensus/bor/snapshot.go
  consensus/bor/span.go
  consensus/bor/valset/validator_set.go
  consensus/chain_reader.go
  consensus/consensus.go
  consensus/merge/merge_test.go
  core/chain_makers.go
  erigon-lib/tools/golangci_lint.sh
  eth/backend.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_headers.go
  turbo/services/interfaces.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/snapshotsync/freezeblocks/bor_snapshots.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: polygon

#8504 Shanghai/Agra HF
  consensus/bor/bor.go
  consensus/bor/finality/whitelist_helpers.go
  core/genesis_write.go
  core/state/intra_block_state.go
  core/state_transition.go
  core/vm/interpreter.go
  erigon-lib/chain/chain_config.go
  erigon-lib/txpool/pool.go
  params/chainspecs/bor-devnet.json
  params/chainspecs/mumbai.json
Labels: shapella, polygon

#8551 Update go-kzg-4844 to v0.7.0
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: dencun

#8553 Replace eip1559FeeCollector with burntContract
  core/state_transition.go
  erigon-lib/chain/chain_config.go
  params/chainspecs/bor-devnet.json
  params/chainspecs/bor-mainnet.json
  params/chainspecs/chiado.json
  params/chainspecs/gnosis.json
  params/chainspecs/mumbai.json
  params/config_test.go
Labels: gnosis, polygon

#8555 Fix wiring of AgraBlock into tx pool
  consensus/bor/bor.go
  core/genesis_write.go
  core/state/intra_block_state.go
  core/vm/interpreter.go
  erigon-lib/chain/chain_config.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_fuzz_test.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpooluitl/all_components.go
  turbo/stages/mock/mock_sentry.go
Labels: polygon

#8560 Numerical instead of lexicographic sorting in borKeyValueConfigHelper
  common/sorted.go
  consensus/aura/aura.go
  core/forkid/forkid.go
  erigon-lib/chain/chain_config.go
  erigon-lib/chain/chain_config_test.go
  erigon-lib/common/sorted.go
  erigon-lib/common/sorted_test.go
  turbo/execution/eth1/block_building.go
Labels: polygon

#8562 Fix panic in isAgra check for txpool
  erigon-lib/txpool/pool.go
Labels: polygon

#8538 Update Readme - gnosis size
  README.md
Labels: gnosis

#8580 Revert "Move validator set snapshot computation to bor_heimdall stage…
  cmd/integration/commands/stages.go
  cmd/rpcdaemon/rpcservices/eth_backend.go
  cmd/state/exec3/state.go
  consensus/bor/bor.go
  consensus/bor/bor_test.go
  consensus/bor/heimdall/span/spanner.go
  consensus/bor/snapshot.go
  consensus/bor/span.go
  consensus/bor/valset/validator_set.go
  consensus/chain_reader.go
  consensus/consensus.go
  consensus/merge/merge_test.go
  core/chain_makers.go
  erigon-lib/tools/golangci_lint.sh
  eth/backend.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_headers.go
  turbo/services/interfaces.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/snapshotsync/freezeblocks/bor_snapshots.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: polygon

#8499 blocksReadAheadFunc: to calc `engine.Author` in background
  eth/stagedsync/stage_execute.go
Labels: polygon

#8620 Fix Agra hf scheduling on Mumbai
  erigon-lib/chain/chain_config_test.go
  params/chainspecs/bor-devnet.json
  params/chainspecs/mumbai.json
  params/config_test.go
Labels: polygon

#8630 Mumbai: fix fork ID for Agra
  core/forkid/forkid.go
  core/forkid/forkid_test.go
Labels: shapella, polygon
