Repository erigontech/erigon, pull requests merged in 2024-09, with the labels that each got.

#11828 polygon/heimdall: make scrapper resilient to 502s
  polygon/heimdall/client.go
  polygon/heimdall/entity_fetcher.go
  polygon/heimdall/scraper.go
  polygon/heimdall/scrapper_test.go
  polygon/heimdall/service.go
Labels: polygon

#11820 adjustments to caplin peer count
  cl/sentinel/gossip.go
  cl/sentinel/libp2p_settings.go
  cl/sentinel/sentinel.go
Labels: caplin

#11833 polygon: update stagesHeadersAndFinish to check PolygonSync stage progress
  eth/integrity/no_gaps_bor_events.go
  turbo/stages/stageloop.go
Labels: polygon

#11832 Caplin: Hack for delayed fsync + do not generate snapshots if too many blocks are skipped (failsafe)
  turbo/snapshotsync/freezeblocks/caplin_snapshots.go
Labels: caplin

#11815 Caplin: Fixed bad performance on low-end consumer hardware
  cl/phase1/forkchoice/utils.go
  cl/phase1/stages/forward_sync.go
Labels: caplin

#11836 polygon/bridge: Handle overrideStateSyncRecords
  eth/stagedsync/bor_heimdall_shared.go
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
Labels: polygon

#11848 New workflow ci-cd-main-branch-docker-images.yml and changes in release workflow
  .github/workflows/ci-cd-main-branch-docker-images.yml
  .github/workflows/release.yml
  Dockerfile.release
Labels: devops

#11842 polygon: Batch fetch spans
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
  polygon/bor/bor_test.go
  polygon/heimdall/client.go
  polygon/heimdall/client_mock.go
  polygon/heimdall/entity_fetcher.go
  polygon/heimdall/entity_fetcher_test.go
  polygon/heimdall/scraper.go
  polygon/heimdall/scraper_test.go
  polygon/heimdall/service.go
  polygon/heimdall/service_test.go
  polygon/heimdall/span.go
Labels: polygon

#11863 Fix bor-heimdall stall after chaindb removal
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#11865 polygon/heimdall: service test to cover both sequential and batch fetch paths
  polygon/heimdall/client.go
  polygon/heimdall/service.go
  polygon/heimdall/service_test.go
Labels: polygon

#11867 polygon/sync: fix parent td missing when forking at the tip
  polygon/sync/canonical_chain_builder.go
  polygon/sync/canonical_chain_builder_test.go
  polygon/sync/sync.go
Labels: polygon

#11870 astrid: fix stage integration cached fork choice logic
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#11854 caplin memory usage improvement
  cl/beacon/handler/block_production.go
  cl/beacon/synced_data/synced_data.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/network/services/attestation_service.go
  cl/validator/attestation_producer/attestation_producer.go
  cl/validator/committee_subscription/committee_subscription.go
Labels: caplin

#11893 polygon/sync: ignore safe peer not found err on tip event
  polygon/p2p/message_sender.go
  polygon/sync/sync.go
Labels: polygon

#11887 astrid: stage integration fix for canonical hashes on unwinds
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#11861 use simple semaphore to limit peer connection opening
  cl/sentinel/discovery.go
Labels: caplin

#11816 Optimise aggregate and proof signature verification
  cl/beacon/handler/pool.go
  cl/beacon/handler/utils_test.go
  cl/cltypes/aggregate.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/aggregate_and_proof_service.go
  cl/phase1/network/services/aggregate_and_proof_service_test.go
  cl/phase1/network/services/interface.go
  cl/phase1/network/services/mock_services/aggregate_and_proof_service_mock.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#11902 [Polygon] Bor: Added Ahmedabad HF related configs and block number for amoy network
  params/chainspecs/amoy.json
Labels: polygon

#11901 [Polygon] Bor: Added Ahmedabad HF related configs and block number for amoy network
  params/chainspecs/amoy.json
Labels: polygon

#11693 polygon/bridge: Support Astrid bridge on standalone and privateapi server
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/main.go
  cmd/rpcdaemon/rpcdaemontest/test_util.go
  erigon-lib/chain/chain_config.go
  eth/backend.go
  ethdb/privateapi/ethbackend.go
  polygon/bor/borcfg/bor_config.go
  polygon/bridge/bridge.go
  polygon/bridge/reader.go
  polygon/heimdall/service_store.go
  polygon/polygoncommon/database.go
  turbo/jsonrpc/eth_subscribe_test.go
Labels: polygon

#11924 polygon/heimdall: Split read functions into reader
  eth/backend.go
  eth/stagedsync/stage_polygon_sync.go
  polygon/heimdall/reader.go
  polygon/heimdall/service.go
  polygon/heimdall/service_test.go
  polygon/heimdall/span_block_producers_tracker.go
Labels: polygon

#11929 polygon/sync: block downloader to not re-insert blocks behind start
  polygon/sync/block_downloader.go
  polygon/sync/block_downloader_test.go
Labels: polygon

#11931 Upgrade goreleaser-cross to 1.22.7 and alpine base image to 3.20.3
  .github/workflows/ci-cd-main-branch-docker-images.yml
  .github/workflows/release.yml
Labels: devops

#11935 trace_filter: return error at empty request
  erigon-lib/kv/rawdbv3/txnum.go
  erigon-lib/kv/stream/stream.go
  erigon-lib/kv/stream/stream_test.go
Labels: erigon3

#11927 polygon/p2p: fix p2p fetcher peer errors on chain tip
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_penalizing_test.go
  polygon/sync/sync.go
Labels: polygon

#11951 Upgrade goreleaser-cross to 1.22.7 and alpine base image version to 3.20.3
  .github/workflows/release.yml
Labels: devops, v2.60

#11944 modify EIP-3607 to accept tx type 4
  eth/stagedsync/stage_mining_exec.go
Labels: pectra

#11957 polygon/bor: fix panic in BorRoSnapshots checkpoint funcs when waypoint snapshots disabled
  turbo/snapshotsync/freezeblocks/block_reader.go
Labels: polygon

#11885 Stricter validation of EIP-7702 transactions
  core/types/authorization.go
  core/types/set_code_tx.go
  core/types/transaction.go
  core/types/transaction_signing.go
  core/vm/contracts.go
  crypto/crypto.go
  crypto/crypto_test.go
  erigon-lib/crypto/secp256k1.go
  erigon-lib/crypto/secp256k1_test.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/txpool_grpc_server.go
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  erigon-lib/types/txn.go
  erigon-lib/types/txn_test.go
Labels: pectra

#11963 polygon: Apply RoTx limit
  cmd/rpcdaemon/cli/config.go
  eth/backend.go
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
  polygon/bridge/reader.go
  polygon/heimdall/reader.go
  polygon/heimdall/service.go
  polygon/heimdall/service_store.go
  polygon/heimdall/service_test.go
  polygon/polygoncommon/database.go
Labels: polygon

#11962 rpcdaemon: Support remote `bor_*` RPC on Astrid
  cmd/rpcdaemon/cli/config.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/remoteproto/bor.pb.go
  erigon-lib/gointerfaces/remoteproto/bor_grpc.pb.go
  eth/backend.go
  ethdb/privateapi/all.go
  polygon/bor/valset/validator.go
  polygon/bridge/reader.go
  polygon/heimdall/reader.go
  polygon/heimdall/server.go
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#11969 Fix for the issues/11968
  Makefile
Labels: devops

#11940 optimise attestation signature verification
  cl/beacon/handler/pool.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/attestation_service.go
  cl/phase1/network/services/attestation_service_test.go
  cl/phase1/network/services/interface.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#11971 Improve ci-cd-main-branch-docker-images workflow
  .github/workflows/ci-cd-main-branch-docker-images.yml
  Dockerfile.release
Labels: devops

#11975 polygon: Reduce assemble function arguments
  cmd/rpcdaemon/cli/config.go
  eth/backend.go
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
  polygon/bridge/reader.go
  polygon/heimdall/reader.go
  polygon/heimdall/service.go
Labels: polygon

#11984 caplin: Wrong attestations included by block proposer
  cl/beacon/builder/client.go
  cl/beacon/handler/block_production.go
  cl/cltypes/aggregate.go
  cl/phase1/network/services/block_service.go
  cl/transition/impl/eth2/validation.go
  cl/utils/bytes.go
  cl/validator/committee_subscription/committee_subscription.go
Labels: caplin

#11954 Separate aggregate signature verification
  cl/beacon/handler/pool.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/aggregate_and_proof_service.go
  cl/phase1/network/services/aggregate_and_proof_service_test.go
  cl/phase1/network/services/attestation_service.go
  cl/phase1/network/services/attestation_service_test.go
  cl/phase1/network/services/batch_signature_verification.go
  cl/phase1/network/services/bls_to_execution_change_service.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#11996 polygon: fix more transient errors for astrid
  erigon-lib/common/errors/errors.go
  polygon/bridge/bridge.go
  polygon/heimdall/scraper.go
Labels: polygon

#11999 astrid stage: do not unwind finalized data
  cmd/integration/commands/flags.go
  cmd/integration/commands/stages.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_polygon_sync.go
  turbo/stages/stageloop.go
Labels: polygon

#11979 [Polygon] Bor: Added Ahmedabad HF related configs and block number for mainnet network
  params/chainspecs/bor-mainnet.json
Labels: polygon

#11980 [Polygon] Bor: Added Ahmedabad HF related configs and block number for mainnet network
  params/chainspecs/bor-mainnet.json
Labels: polygon

#12003 Add support for build for linux/amd64 (v1) [binaries/docker]
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile.release
Labels: devops

#12000 caplin: improvement in signature verification flow
  cl/beacon/handler/pool.go
  cl/cltypes/aggregate.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/aggregate_and_proof_service.go
  cl/phase1/network/services/attestation_service.go
  cl/phase1/network/services/batch_signature_verification.go
Labels: caplin

#12017 Fix Dockerfile for AMD64v2 case.
  Dockerfile.release
Labels: devops

#12027 Drop go 1.21 in release/2.60 - cherry pick PR 11966, 11897
  .github/workflows/ci.yml
  .github/workflows/test-integration-caplin.yml
  .github/workflows/test-integration.yml
  erigon-lib/go.mod
  go.mod
Labels: v2.60

#11992 Add support to `eth_blobBaseFee`, `eth_baseFee` and EIP4844 support to `eth_feeHistory`
  eth/gasprice/feehistory.go
  eth/gasprice/feehistory_test.go
  turbo/jsonrpc/eth_system.go
Labels: dencun

#12039 Update release workflow for release/2.60
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile.release
Labels: devops

#12040 Improve release workflow in main branch
  .github/workflows/release.yml
  .goreleaser.yml
Labels: devops

#12070 astrid: stage integration fix for connectTip error
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#12100 Attention to v-prefix. gh cli rework.
  .github/workflows/release.yml
Labels: devops

#12131 Caplin: Add switch to enable/disable static files generation
  cl/antiquary/antiquary.go
  cl/antiquary/state_antiquary_test.go
  cl/beacon/handler/utils_test.go
  cl/clparams/config.go
  cl/persistence/state/historical_states_reader/historical_states_reader_test.go
  cl/sentinel/sentinel_requests_test.go
  cmd/capcli/cli.go
  cmd/caplin/caplin1/run.go
  cmd/utils/flags.go
  turbo/cli/default_flags.go
Labels: caplin

#12135 Update EIP-7251 address
  params/protocol_params.go
  tests/exec_spec_test.go
Labels: pectra
