Repository erigontech/erigon, pull requests merged in 2024-12, with the labels that each got.

#12957 Feature/lystopad/issue 12900
  Dockerfile.release
Labels: devops

#12953 e2: reduce prune limit on chain tip
  cmd/integration/commands/stages.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_snapshots.go
  eth/stagedsync/stage_txlookup.go
  turbo/cli/flags.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
Labels: support

#12959 Define UID and GID for erigon user as well as STOPSIGNAL.
  Dockerfile.release
Labels: devops

#12958 Feature/lystopad/issue 12900 (#12957)
  Dockerfile.release
Labels: devops

#12979 engineapi: Add version-based check for requests list
  turbo/engineapi/engine_server.go
Labels: pectra

#12998 Fix bug on pre-Pectra `newPayload`
  turbo/engineapi/engine_server.go
Labels: pectra

#12802 Rework ci-cd-main-branch-docker-images.yml
  .github/workflows/ci-cd-main-branch-docker-images.yml
Labels: devops

#13023 Fix the case when workflow triggered by push request
  .github/workflows/ci-cd-main-branch-docker-images.yml
Labels: devops

#13024 Add support for building Debian packages (arm/amd) in the release workflow.
  .github/workflows/release.yml
  .github/workflows/reusable-release-build-debian-pkg.yml
Labels: devops

#13020 polygon/bridge: Return `ok` in BlockEventIdsRange
  cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
  eth/stagedsync/stage_polygon_sync.go
  polygon/bridge/mdbx_store.go
  polygon/bridge/reader.go
  polygon/bridge/snapshot_store.go
  polygon/bridge/store.go
Labels: polygon

#12847 experimental: MPT block witness for Erigon 3
  cmd/state/commands/opcode_tracer.go
  core/blockchain.go
  core/chain_makers.go
  core/state/stateless.go
  core/state/triedb_state.go
  docs/programmers_guide/witness_formal_spec.md
  docs/programmers_guide/witness_format.md
  erigon-lib/commitment/commitment.go
  erigon-lib/commitment/hex_patricia_hashed.go
  erigon-lib/commitment/hex_patricia_hashed_bench_test.go
  erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go
  erigon-lib/commitment/hex_patricia_hashed_test.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/kv/dbutils/composite_keys.go
  erigon-lib/kv/tables.go
  erigon-lib/state/domain.go
  erigon-lib/state/domain_shared.go
  erigon-lib/trie/debug.go
  erigon-lib/trie/hack.go
  erigon-lib/trie/hashbuilder.go
  erigon-lib/trie/hasher.go
  erigon-lib/trie/hasher_test.go
  erigon-lib/trie/node.go
  erigon-lib/trie/proof.go
  erigon-lib/trie/retain_list.go
  erigon-lib/trie/retain_list_builder.go
  erigon-lib/trie/retain_list_test.go
  erigon-lib/trie/stream.go
  erigon-lib/trie/structural_test.go
  erigon-lib/trie/sub_trie_loader.go
  erigon-lib/trie/trie.go
  erigon-lib/trie/trie_from_witness.go
  erigon-lib/trie/trie_root.go
  erigon-lib/trie/trie_test.go
  erigon-lib/trie/trie_witness.go
  erigon-lib/trie/witness.go
  erigon-lib/trie/witness_builder.go
  erigon-lib/trie/witness_builder_test.go
  erigon-lib/trie/witness_marshalling.go
  erigon-lib/trie/witness_operators.go
  erigon-lib/trie/witness_operators_test.go
  erigon-lib/trie/witness_stats.go
  erigon-lib/trie/witness_test.go
  erigon-lib/types/accounts/account.go
  erigon-lib/types/witness/types.go
  eth/stagedsync/stage_witness.go
  eth/stagedsync/witness_util.go
  turbo/jsonrpc/eth_call.go
  turbo/jsonrpc/trace_filtering.go
Labels: zkevm

#13042 add slot data from electra
  cl/antiquary/state_antiquary_test.go
  cl/antiquary/tests/test_data/electra/blocks_0.ssz_snappy
  cl/antiquary/tests/test_data/electra/blocks_1.ssz_snappy
  cl/antiquary/tests/test_data/electra/meta.yaml
  cl/antiquary/tests/test_data/electra/post.ssz_snappy
  cl/antiquary/tests/test_data/electra/pre.ssz_snappy
  cl/antiquary/tests/tests.go
  cl/beacon/handler/rewards.go
  cl/persistence/state/historical_states_reader/historical_states_reader.go
  cl/persistence/state/slot_data.go
  cl/persistence/state/slot_data_test.go
  cl/persistence/state/state_accessors.go
  cl/phase1/core/state/raw/getters.go
Labels: pectra

#13093 Add login to dockerhub as attempt to fix pull request limit issue.
  .github/workflows/test-kurtosis-assertoor.yml
Labels: devops

#13132 txnprovider: simplify interface and address feedback
  eth/backend.go
  eth/stagedsync/stage_mining_exec.go
  turbo/stages/mock/mock_sentry.go
  txnprovider/provider.go
  txnprovider/provider_composite.go
  txnprovider/provider_shutter.go
  txnprovider/provider_txnpool_ordered.go
  txnprovider/provider_txnpool_unordered.go
  txnprovider/shutter/pool.go
  txnprovider/txpool/pool.go
Labels: shutter

#13081 txnprovider/shutter: initial config to enable shutter
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  turbo/cli/default_flags.go
  txnprovider/shutter/config.go
  txnprovider/shutter/pool.go
Labels: shutter

#13141 Implement AuRa remoteConsensusEngine
  cmd/rpcdaemon/cli/config.go
  consensus/aura/aura.go
  consensus/aura/epoch.go
  erigon-lib/kv/helpers.go
  erigon-lib/kv/tables.go
  polygon/bor/bor.go
Labels: gnosis
