Repository erigontech/erigon, pull requests merged in 2024-03, with the labels that each got.

#9540 bor: BorStartEventID support snapshots
  cmd/rpcdaemon/rpcservices/eth_backend.go
  cmd/state/exec3/state.go
  consensus/consensus.go
  core/chain_makers.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_headers.go
  turbo/services/interfaces.go
  turbo/snapshotsync/freezeblocks/block_reader.go
Labels: polygon

#9553 Add first byte check for versioned hash
  eth/ethutils/utils.go
  turbo/engineapi/engine_server.go
Labels: dencun

#9561 Move Verkle to Osaka
  core/vm/runtime/runtime.go
  erigon-lib/chain/chain_config.go
  eth/stagedsync/default_stages.go
Labels: verkle-tree

#9500 Caplin: Added EIP4844 Full Data Avaiability
  Makefile
  cl/beacon/handler/blobs.go
  cl/beacon/handler/genesis.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/harness/blob_sidecars.yaml
  cl/beacon/handler/harness/config.yml
  cl/beacon/handler/harness_test.go
  cl/beacon/handler/test_data/blob_sidecars_1.json
  cl/beacon/handler/utils_test.go
  cl/clparams/config.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_kzgcommitment.go
  cl/cltypes/blob_sidecar.go
  cl/cltypes/solid/list_ssz.go
  cl/persistence/blob_storage/blob.go
  cl/persistence/blob_storage/blob_db.go
  cl/persistence/blob_storage/blob_db_test.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/forkchoice_mock.go
  cl/phase1/forkchoice/interface.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/forkchoice/utils.go
  cl/phase1/network/backward_beacon_downloader.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/network/blobs.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/sentinel/handlers/blobs.go
  cl/sentinel/handlers/blobs_test.go
  cl/sentinel/handlers/blocks_by_range_test.go
  cl/sentinel/handlers/blocks_by_root_test.go
  cl/sentinel/handlers/handlers.go
  cl/sentinel/handlers/heartbeats_test.go
  cl/sentinel/handlers/light_client_test.go
  cl/sentinel/sentinel.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/sentinel_requests_test.go
  cl/sentinel/service/start.go
  cl/spectest/Makefile
  cl/spectest/consensus_tests/appendix.go
  cl/spectest/consensus_tests/eip4844_proofs.go
  cl/spectest/consensus_tests/fork_choice.go
  cmd/capcli/cli.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  cmd/sentinel/main.go
  cmd/tooling/README.md
  cmd/tooling/cli.go
  cmd/tooling/main.go
  cmd/utils/flags.go
  erigon-lib/diskutils/diskutils_darwin.go
  eth/backend.go
  turbo/cli/default_flags.go
Labels: dencun, caplin

#9562 polygon/sync: refactor storage
  polygon/sync/execution_client.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/service.go
  polygon/sync/storage.go
  polygon/sync/sync.go
Labels: polygon

#9537 polygon/p2p: retry fetch headers on response timeout
  go.mod
  go.sum
  polygon/p2p/fetcher.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/message_observer.go
  polygon/p2p/service.go
  polygon/p2p/service_test.go
Labels: polygon

#9538 polygon/p2p: extract penalizing fetcher
  polygon/p2p/fetcher.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/service.go
Labels: polygon

#9579 polygon/p2p: improve message listener
  polygon/p2p/fetcher.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_observer.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/service_test.go
Labels: polygon

#9580 cl: pass context to ExecutionEngine methods
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/forkchoice_mock.go
  cl/phase1/forkchoice/interface.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/network/backward_beacon_downloader.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/spectest/consensus_tests/fork_choice.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  eth/backend.go
  turbo/app/import_cmd.go
  turbo/engineapi/engine_block_downloader/block_downloader.go
  turbo/engineapi/engine_block_downloader/body.go
  turbo/engineapi/engine_block_downloader/core.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/stages/mock/mock_sentry.go
Labels: caplin

#9576 polygon/sync: SyncToTipEvents
  polygon/p2p/fetcher.go
  polygon/p2p/message_listener.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/sync/service.go
  polygon/sync/sync.go
  polygon/sync/sync_to_tip_events.go
  polygon/sync/tip_events.go
Labels: polygon

#9596 polygon/sync: event channel
  polygon/sync/event_channel.go
  polygon/sync/event_channel_test.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
Labels: polygon

#9597 polygon/sync: handle new header hashes
  polygon/sync/sync.go
Labels: polygon

#9581 polygon/p2p: message listener to penalize for invalid rlp
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  polygon/p2p/fetcher.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_sender.go
  polygon/p2p/service.go
  polygon/p2p/service_test.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
Labels: polygon

#9588 nil ptr `bor.close()`
  turbo/snapshotsync/freezeblocks/block_snapshots.go
  turbo/snapshotsync/snapshotsync.go
Labels: polygon

#9601 polygon/p2p: use ptr for PeerId passing
  polygon/p2p/fetcher.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_sender.go
  polygon/p2p/peer_id.go
  polygon/p2p/peer_penalizer.go
  polygon/p2p/peer_sync_progress.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/p2p/service_test.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/tip_events.go
Labels: polygon

#9602 polygon/p2p: service composition
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/sync/tip_events.go
Labels: polygon

#9603 Finalize cancun/napoli HF block number for polygon mainnet
  core/forkid/forkid_test.go
  params/chainspecs/bor-devnet.json
  params/chainspecs/bor-mainnet.json
Labels: polygon

#9606 polygon/sync: remove EventChannel.pollDelay
  polygon/sync/event_channel.go
  polygon/sync/event_channel_test.go
  polygon/sync/tip_events.go
Labels: polygon

#9605 polygon/sync: ExecutionClient
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  polygon/sync/execution_client.go
  polygon/sync/sync.go
Labels: polygon

#9615 mdbx: close cursor in ListDBI method
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: release

#9626 polygon/p2p: organise tests
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_penalizing_test.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/fetcher_tracking_test.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_listener_test.go
  polygon/p2p/peer_id.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/peer_tracker_test.go
  polygon/p2p/service.go
  polygon/p2p/service_test.go
Labels: polygon

#9628 polygon/sync: fix EventChannel race condition
  polygon/sync/event_channel.go
Labels: polygon

#9619 polygon: don't use bytes after tx.Rollback()
  polygon/bor/finality/rawdb/milestone.go
  polygon/bor/snapshot.go
Labels: polygon

#9629 polygon: standardise service.run
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_listener_test.go
  polygon/p2p/peer_tracker_test.go
  polygon/p2p/service_mock.go
  polygon/sync/service.go
Labels: polygon

#9610 Caplin: Fixed races and Beacon API inconsenstincies
  cl/beacon/handler/genesis.go
  cl/beacon/handler/harness/config.yml
  cl/clparams/config.go
  cl/fork/fork.go
  cl/fork/fork_test.go
  cl/persistence/block_store.go
  cl/phase1/core/state/upgrade.go
  cl/phase1/core/state/util.go
  cl/phase1/forkchoice/on_operations.go
  cl/phase1/stages/clstages.go
  cl/sentinel/handlers/light_client.go
  cl/sentinel/peers/pool.go
  cl/sentinel/service/service.go
  cl/transition/impl/eth2/operations.go
  erigon-lib/downloader/downloader.go
  turbo/snapshotsync/snapshotsync.go
Labels: caplin

#9632 Fix reading blob transaction from PoolTransaction
  core/types/transaction.go
  erigon-lib/kv/tables.go
  erigon-lib/txpool/pool.go
Labels: dencun

#9668 Fix txpool_content for pending blob tx
  turbo/jsonrpc/eth_api.go
Labels: dencun

#9565 polygon/p2p: fetch bodies
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_errors.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_penalizing_test.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/fetcher_tracking_test.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_listener_test.go
  polygon/p2p/message_sender.go
  polygon/p2p/message_sender_test.go
  polygon/p2p/service_mock.go
Labels: polygon

#9655 Caplin: add option to disable blob pruning
  cl/clparams/config.go
  cl/freezer/.gitignore
  cl/freezer/freezer.go
  cl/freezer/freezer_test.go
  cl/freezer/fs_freezer.go
  cl/freezer/mem_freezer.go
  cl/freezer/store.go
  cl/freezer/utils.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/network/gossip_manager.go
  cl/spectest/consensus_tests/fork_choice.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  cmd/utils/flags.go
  eth/backend.go
  turbo/cli/default_flags.go
Labels: caplin

#9682 Fixed gnosis DA on Caplin
  cl/clparams/config.go
  cl/persistence/blob_storage/blob_db.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/transition/impl/eth2/validation.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#9653 GossipManager: grpc stream reconnect and wait for remote server start
  cl/phase1/network/gossip_manager.go
Labels: caplin

#9702 Caplin: added routine for missing blocks recovery
  cl/antiquary/state_antiquary.go
  cl/fork/fork_test.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/network/backward_beacon_downloader.go
  cl/phase1/stages/stage_history_download.go
  cl/sentinel/gossip.go
  erigon-lib/direct/execution_client.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/execution/execution.pb.go
  erigon-lib/gointerfaces/execution/execution_grpc.pb.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/execution/eth1/ethereum_execution.go
Labels: caplin

#9679 polygon/sync: download blocks
  cl/fork/fork_test.go
  core/types/block.go
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_errors.go
  polygon/p2p/service_mock.go
  polygon/sync/bodies_verifier.go
  polygon/sync/execution_client.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/headers_writer_mock.go
  polygon/sync/service.go
  polygon/sync/storage.go
  polygon/sync/storage_mock.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
Labels: polygon

#9681 polygon/sync: rename to block downloader tidy up
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/message_listener.go
  polygon/sync/block_downloader.go
  polygon/sync/block_downloader_test.go
  polygon/sync/service.go
  polygon/sync/sync.go
Labels: polygon

#9704 polygon/p2p: fix fetch bodies bugs
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_errors.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_penalizing_test.go
Labels: polygon

#9708 polygon/p2p: blocks verifier
  polygon/p2p/message_listener.go
  polygon/sync/blocks_verifier.go
  polygon/sync/bodies_verifier.go
Labels: polygon

#9709 Caplin: Added preparation for validator block building
  cl/beacon/handler/data_test.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/pool_test.go
  cl/beacon/handler/rewards_test.go
  cl/beacon/handler/states_test.go
  cl/beacon/handler/utils_test.go
  cl/beacon/handler/validator_registration.go
  cl/beacon/handler/validator_registration_test.go
  cl/sentinel/service/service.go
  cl/validator/validator_params/validator_params.go
  cmd/caplin/caplin1/run.go
Labels: caplin, staking

#9722 evm transaction context not correct when txn is type 3 (EIP-4844)
  turbo/jsonrpc/tracing.go
Labels: dencun

#9743 use sync.Map in gossipManager.subscriptions
  cl/sentinel/gossip.go
Labels: caplin

#9560 Include EIP-2537 precompiles into Prague
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/evm.go
  core/vm/testdata/precompiles/blsG1Add.json
  core/vm/testdata/precompiles/blsG1Mul.json
  core/vm/testdata/precompiles/blsG1MultiExp.json
  core/vm/testdata/precompiles/blsG2Add.json
  core/vm/testdata/precompiles/blsG2Mul.json
  core/vm/testdata/precompiles/blsG2MultiExp.json
  core/vm/testdata/precompiles/blsMapG1.json
  core/vm/testdata/precompiles/blsMapG2.json
  core/vm/testdata/precompiles/blsPairing.json
  crypto/bls12381/g1.go
  crypto/bls12381/g1_test.go
  crypto/bls12381/g2.go
  crypto/bls12381/g2_test.go
  params/protocol_params.go
  tests/fuzzers/bls12381/precompile_fuzzer.go
Labels: pectra

#9752 downloader: don't skip webseed if .torrent file exists (because download maybe not completed yet)
  erigon-lib/downloader/torrent_files.go
  erigon-lib/downloader/webseed.go
Labels: release

#9755 downloader: don't skip webseed if .torrent file exists (because downl…
  erigon-lib/downloader/downloader.go
  erigon-lib/downloader/torrent_files.go
  erigon-lib/downloader/webseed.go
Labels: release

#9753 RPC: close `tx.Prefix` iterator for early release memory
  core/rawdb/accessors_chain.go
  erigon-lib/kv/mdbx/kv_mdbx.go
  turbo/jsonrpc/erigon_receipts.go
  turbo/jsonrpc/eth_receipts.go
Labels: release

#9749 Update cancun fork block numbers
  core/forkid/forkid_test.go
Labels: dencun

#9759 RPC: close `tx.Prefix` iterator for early release memory
  core/rawdb/accessors_chain.go
  erigon-lib/kv/mdbx/kv_mdbx.go
  turbo/jsonrpc/erigon_receipts.go
  turbo/jsonrpc/eth_receipts.go
Labels: release

#9761 Demote downloader hash warnings
  erigon-lib/downloader/downloader.go
  params/version.go
Labels: release

#9734 Proper Caplin's subscription listen
  cl/gossip/gossip.go
  cl/sentinel/gossip.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/service/start.go
  cl/validator/attestation_producer/attestation_producer.go
Labels: caplin

#9766 Added blob sidecars snapshots for sepolia
  cl/phase1/stages/stage_history_download.go
  erigon-lib/downloader/downloader.go
  erigon-lib/downloader/downloader_grpc_server.go
  erigon-lib/downloader/snaptype/type.go
  erigon-lib/downloader/torrent_files.go
  erigon-lib/downloader/util.go
  erigon-lib/downloader/webseed.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  eth/backend.go
  eth/stagedsync/stage_snapshots.go
  go.mod
  go.sum
  turbo/snapshotsync/snapshotsync.go
Labels: dencun

#9779 Caplin: Fixed not calling FCU due to faulty blob handling
  cl/phase1/stages/clstages.go
Labels: caplin

#9794 fixed downloading of unnecessary blocks when `--caplin.backfilling`=false
  cl/phase1/stages/stage_history_download.go
Labels: caplin

#9739 polygon/sync: handle FetchHeaders errors in sync.go
  polygon/p2p/fetcher_errors.go
  polygon/sync/sync.go
Labels: polygon

#9796 Added basic block production to Caplin.
  cl/beacon/beaconhttp/beacon_response.go
  cl/beacon/handler/block_production.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/duties_attester.go
  cl/beacon/handler/duties_proposer.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/node.go
  cl/beacon/handler/test_data/blinded_block_1.json
  cl/beacon/handler/test_data/block_1.json
  cl/beacon/handler/test_data/duties_1.yaml
  cl/beacon/handler/test_data/light_client_finality_1.json
  cl/beacon/handler/test_data/light_client_optimistic_1.json
  cl/beacon/handler/test_data/light_client_update_1.json
  cl/beacon/handler/utils_test.go
  cl/beacon/handler/validators.go
  cl/beacon/middleware.go
  cl/beacon/router.go
  cl/clparams/version.go
  cl/cltypes/aggregate.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/beacon_kzgcommitment.go
  cl/cltypes/blob_sidecar.go
  cl/cltypes/clone.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_header.go
  cl/cltypes/indexed_attestation.go
  cl/cltypes/solid/checkpoint.go
  cl/cltypes/solid/hash_list.go
  cl/cltypes/solid/pending_attestation.go
  cl/cltypes/solid/uint64_raw_list.go
  cl/cltypes/testdata/block_test_gnosis_deneb.json
  cl/cltypes/testdata/block_test_gnosis_deneb.ssz
  cl/cltypes/validator.go
  cl/gossip/gossip.go
  cl/phase1/core/state/accessors.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/core/state/upgrade_test.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/stages/clstages.go
  cl/sentinel/gossip.go
  cl/sentinel/service/service.go
  cl/spectest/consensus_tests/appendix.go
  cl/spectest/consensus_tests/ssz_static.go
  cl/transition/impl/eth2/operations.go
  cl/utils/bytes.go
  cmd/caplin/caplin1/run.go
  polygon/sync/execution_client.go
  spectest/case.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
Labels: caplin, staking

#9803 Correct handling of beacon aggregates
  cl/phase1/core/state/accessors.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/network/gossip_manager.go
  cl/sentinel/gossip.go
  cl/sentinel/service/start.go
  cmd/caplin/caplin1/run.go
  cmd/sentinel/main.go
Labels: caplin

#9718 polygon/sync: block downloader limit mem usage
  erigon-lib/common/collections.go
  eth/ethconfig/estimate/esitmated_ram.go
  go.mod
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_tracking_test.go
  polygon/p2p/peer_shuffle.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/peer_tracker_test.go
  polygon/sync/block_downloader.go
  polygon/sync/block_downloader_test.go
Labels: polygon

#9818 Caplin: Fixed not calling FCU due to faulty blob handling
  cl/phase1/stages/clstages.go
Labels: release

#9820 fixed downloading of unnecessary blocks when `--caplin.backfilling`=f…
  cl/phase1/stages/stage_history_download.go
Labels: release

#9821 Proper Caplin's subscription listen
  cl/gossip/gossip.go
  cl/sentinel/gossip.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/service/start.go
  cl/validator/attestation_producer/attestation_producer.go
Labels: release

#9822 Added basic block production to Caplin
  cl/beacon/beaconhttp/beacon_response.go
  cl/beacon/handler/block_production.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/duties_attester.go
  cl/beacon/handler/duties_proposer.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/node.go
  cl/beacon/handler/test_data/blinded_block_1.json
  cl/beacon/handler/test_data/block_1.json
  cl/beacon/handler/test_data/duties_1.yaml
  cl/beacon/handler/test_data/light_client_finality_1.json
  cl/beacon/handler/test_data/light_client_optimistic_1.json
  cl/beacon/handler/test_data/light_client_update_1.json
  cl/beacon/handler/utils_test.go
  cl/beacon/handler/validators.go
  cl/beacon/middleware.go
  cl/beacon/router.go
  cl/clparams/version.go
  cl/cltypes/aggregate.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/beacon_kzgcommitment.go
  cl/cltypes/blob_sidecar.go
  cl/cltypes/clone.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_header.go
  cl/cltypes/indexed_attestation.go
  cl/cltypes/solid/checkpoint.go
  cl/cltypes/solid/hash_list.go
  cl/cltypes/solid/pending_attestation.go
  cl/cltypes/solid/uint64_raw_list.go
  cl/cltypes/testdata/block_test_gnosis_deneb.json
  cl/cltypes/testdata/block_test_gnosis_deneb.ssz
  cl/cltypes/validator.go
  cl/gossip/gossip.go
  cl/phase1/core/state/accessors.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/core/state/upgrade_test.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/stages/clstages.go
  cl/sentinel/gossip.go
  cl/sentinel/service/service.go
  cl/spectest/consensus_tests/appendix.go
  cl/spectest/consensus_tests/ssz_static.go
  cl/transition/impl/eth2/operations.go
  cl/utils/bytes.go
  cmd/caplin/caplin1/run.go
  polygon/sync/execution_client.go
  spectest/case.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
Labels: release

#9823 downloader: when torrent added to lib and metadata resolved - already…
  erigon-lib/downloader/downloader.go
Labels: release

#9824 Bump release version
  params/version.go
Labels: release

#9747 p2p/sentry: status data provider refactoring
  cmd/integration/commands/stages.go
  eth/backend.go
  p2p/sentry/sentry_multi_client/broadcast.go
  p2p/sentry/sentry_multi_client/sentry_api.go
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  p2p/sentry/status_data_provider.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_listener_test.go
  polygon/p2p/service.go
  polygon/sync/service.go
  turbo/app/import_cmd.go
  turbo/jsonrpc/eth_subscribe_test.go
  turbo/stages/bodydownload/body_algos.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/mock/sentry_mock_test.go
  turbo/stages/stageloop.go
Labels: polygon

#9833 Revert "updateForkChoice: support --sync.loop.block.limit (#9315)"
  eth/backend.go
  params/version.go
  turbo/execution/eth1/ethereum_execution.go
  turbo/execution/eth1/forkchoice.go
  turbo/stages/mock/mock_sentry.go
Labels: release

#9715 cl: atomic progress and finish fields
  cl/phase1/network/backward_beacon_downloader.go
Labels: caplin

#9575 Caplin: `ContributionAndProof` handling
  cl/cltypes/contribution.go
  cl/cltypes/sync_aggregator_selection_data.go
  cl/phase1/forkchoice/on_operations.go
  cl/phase1/forkchoice/utils.go
  cl/pool/operation_pool.go
  cl/pool/operations_pool.go
  cl/spectest/consensus_tests/appendix.go
  cl/spectest/consensus_tests/ssz_static.go
Labels: caplin

#9835 override.cancun -> override.prague
  cmd/utils/flags.go
  core/genesis_write.go
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  erigon-lib/txpool/txpooluitl/all_components.go
  eth/backend.go
  eth/ethconfig/config.go
  turbo/cli/default_flags.go
Labels: pectra

#9745 silkworm: int/ext txn split
  eth/stagedsync/stage_execute.go
  go.mod
  go.sum
  turbo/silkworm/silkworm.go
Labels: silkworm

#9837 add: napoli block for amoy network
  core/forkid/forkid_test.go
  params/chainspecs/amoy.json
Labels: polygon

#9840 Napoli block for Amoy network
  core/forkid/forkid_test.go
  params/chainspecs/amoy.json
  params/version.go
Labels: release

#9819 Heimdall simulator
  p2p/sentry/simulator/sentry_simulator.go
  p2p/sentry/simulator/syncutil.go
  polygon/heimdall/event_record.go
  polygon/heimdall/simulator/heimdall_simulator.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/snapshotsync/freezeblocks/block_snapshots.go
  turbo/snapshotsync/freezeblocks/bor_snapshots.go
Labels: polygon
