Repository erigontech/erigon, pull requests merged in 2024-06, with the labels that each got.

#10600 polygon/heimdall: fix milestone poller start to be within last 100
  polygon/heimdall/heimdall.go
Labels: polygon

#10601 stagedsync: fix error propagation in polygon sync stage
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#10581 polygon/sync: block downloader to use LoopBlockLimit
  eth/backend.go
  eth/stagedsync/stage_polygon_sync.go
  polygon/sync/block_downloader.go
  polygon/sync/block_downloader_test.go
  polygon/sync/service.go
  polygon/sync/sync.go
  turbo/stages/stageloop.go
Labels: polygon

#10599 polygon/sync: Bridge integration
  eth/stagedsync/stage_polygon_sync.go
  polygon/bridge/bridge.go
  polygon/bridge/db.go
  polygon/bridge/service.go
  polygon/sync/service.go
  polygon/sync/store.go
  turbo/cli/flags.go
  turbo/stages/stageloop.go
Labels: polygon

#10605 polygon/heimdall: batch fetch checkpoint empty return and id fixes
  polygon/heimdall/entity_fetcher.go
  polygon/heimdall/heimdall.go
Labels: polygon

#10620 protect stage_headers/bodies/senders/txnlookup from unwind behind files
  eth/stagedsync/stage_bodies.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_senders.go
  eth/stagedsync/stage_txlookup.go
Labels: erigon3

#10619 don't allow unwind behind files
  erigon-lib/state/aggregator.go
Labels: erigon3

#10618 stage_headers: fix uint underflow at parent request
  turbo/stages/headerdownload/header_algos.go
Labels: erigon3

#10628 Optimize BLOBBASEFEE
  accounts/abi/bind/backends/simulated.go
  cmd/state/exec3/trace_worker.go
  cmd/state/exec3/trace_worker2.go
  consensus/misc/eip1559.go
  core/blockchain.go
  core/evm.go
  core/genesis_write.go
  core/state_processor.go
  core/state_transition.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  eth/stagedsync/exec3.go
  eth/tracers/tracers_test.go
  tests/state_test_util.go
  turbo/jsonrpc/eth_block.go
  turbo/jsonrpc/eth_call.go
  turbo/jsonrpc/eth_callMany.go
  turbo/jsonrpc/otterscan_search_trace.go
  turbo/jsonrpc/overlay_api.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
  turbo/jsonrpc/tracing.go
  turbo/transactions/call.go
  turbo/transactions/tracing.go
Labels: dencun

#10615 polygon/bridge: Persist block maps
  erigon-lib/kv/tables.go
  polygon/bridge/bridge.go
  polygon/bridge/db.go
  polygon/bridge/service.go
Labels: polygon

#10684 e3: produce block files earlier
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: erigon3

#10682 polygon/heimdall: Fix checkpoint ID
  polygon/heimdall/checkpoint.go
  polygon/heimdall/entity.go
  polygon/heimdall/entity_fetcher.go
  polygon/heimdall/milestone.go
  polygon/heimdall/span.go
Labels: polygon

#10692 stagedsync: polygon sync stage fix invalid baseFee error
  eth/stagedsync/stage_polygon_sync.go
  turbo/execution/eth1/inserters.go
Labels: polygon

#10695 polygon/sync: fix canonical chain builder connect err due to no span in span cache
  eth/stagedsync/stage_polygon_sync.go
  polygon/heimdall/heimdall.go
  polygon/heimdall/heimdall_mock.go
  polygon/heimdall/service.go
  polygon/sync/canonical_chain_builder_factory.go
  polygon/sync/service.go
  polygon/sync/sync.go
Labels: polygon

#10793 Downloader: fix staticpeers flag
  cmd/utils/flags.go
Labels: bug

#10278 Added check for initial chain block for validator init
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#10810 Move bor_fee_log from core to polygon
  accounts/abi/bind/backends/simulated.go
  cmd/rpcdaemon/cli/config.go
  cmd/state/exec3/trace_worker.go
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/ethash/ethash.go
  consensus/merge/merge.go
  core/evm.go
  core/state_transition.go
  core/vm/evmtypes/evmtypes.go
  core/vm/runtime/env.go
  eth/tracers/internal/tracetest/calltrace_test.go
  eth/tracers/internal/tracetest/prestate_test.go
  eth/tracers/tracers_test.go
  polygon/bor/bor.go
  polygon/bor/fee_log.go
  polygon/tracer/trace_bor_state_sync_txn.go
  turbo/adapter/ethapi/api.go
  turbo/jsonrpc/eth_call.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
  turbo/transactions/call.go
  turbo/transactions/tracing.go
Labels: polygon

#10798 Downloader: fix staticpeers flag
  cmd/utils/flags.go
Labels: bug

#10843 Changing Caplin Finality Checkpoint API response to match spec
  cl/beacon/handler/states.go
  cl/beacon/handler/states_test.go
  cl/beacon/handler/test_data/states_1.yaml
Labels: caplin

#10860 Caplin: Demote annoying log
  cl/phase1/forkchoice/on_block.go
Labels: caplin

#10492 Support external mev builder
  cl/beacon/builder/client.go
  cl/beacon/builder/client_test.go
  cl/beacon/builder/interface.go
  cl/beacon/builder/mock_services/builder_client_mock.go
  cl/beacon/builder/test_data/mock_blinded_block.json
  cl/beacon/builder/test_data/mock_blinded_block_resp.json
  cl/beacon/builder/test_data/mock_header.json
  cl/beacon/builder/types.go
  cl/beacon/handler/block_production.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/test_data/blinded_block_1.json
  cl/beacon/handler/test_data/block_1.json
  cl/beacon/handler/utils_test.go
  cl/beacon/handler/validator_test.go
  cl/clparams/config.go
  cl/clparams/version.go
  cl/cltypes/aggregate.go
  cl/cltypes/beacon_block.go
  cl/cltypes/blinded_beacon_block.go
  cl/cltypes/block_production.go
  cl/cltypes/bls_to_execution_change.go
  cl/cltypes/builder.go
  cl/cltypes/eth1_block.go
  cl/cltypes/eth1_data.go
  cl/cltypes/eth1_header.go
  cl/cltypes/indexed_attestation.go
  cl/phase1/forkchoice/on_block.go
  cl/spectest/consensus_tests/operations.go
  cl/transition/impl/eth2/operations.go
  cl/transition/impl/funcmap/impl.go
  cl/transition/machine/block.go
  cl/transition/machine/helpers.go
  cl/transition/machine/machine.go
  cl/transition/machine/transition.go
  cmd/caplin/caplin1/option.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/caplincli/config.go
  cmd/caplin/caplinflags/flags.go
  cmd/caplin/main.go
  cmd/utils/flags.go
  eth/backend.go
  turbo/cli/default_flags.go
Labels: caplin, priority:high

#10914 polygon/bridge: Use store
  eth/stagedsync/stage_polygon_sync.go
  polygon/bridge/bridge.go
  polygon/bridge/db.go
  polygon/sync/service.go
  polygon/sync/store.go
Labels: polygon

#10888 polygon/heimdall: add persistence interface to heimdall service
  polygon/heimdall/entity_store.go
  polygon/heimdall/scraper.go
  polygon/heimdall/service.go
  polygon/heimdall/service_store.go
  polygon/sync/service.go
Labels: polygon

#10916 Avoid unnecessary uint -> int casting on big.Int construction
  accounts/abi/bind/backends/simulated_test.go
  cl/cltypes/eth1_block.go
  cmd/devnet/contracts/steps/subscriber.go
  cmd/devnet/services/polygon/checkpoint.go
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/evm/internal/t8ntool/transition.go
  core/vm/runtime/runtime_test.go
  eth/stagedsync/stage_bodies_test.go
  eth/stagedsync/testutil.go
  polygon/bor/finality/whitelist/service_test.go
  polygon/sync/canonical_chain_builder_test.go
  tests/difficulty_test_util.go
  tests/state_test_util.go
  turbo/execution/eth1/eth1_utils/grpc.go
  turbo/jsonrpc/eth_block.go
  turbo/jsonrpc/eth_callMany.go
  turbo/jsonrpc/eth_mining_test.go
Labels: good-practices

#10851 Caplin: Added Blob Sidecar PastFinalization Check
  cl/phase1/network/services/blob_sidecar_service.go
Labels: caplin

#10910 Add EIP-7251 consolidation requests support
  consensus/merge/merge.go
  consensus/misc/eip7002.go
  consensus/misc/eip7251.go
  core/types/consolidation_request.go
  core/types/encdec_test.go
  core/types/request.go
  core/types/withdrawal_request.go
  params/protocol_params.go
  tests/exec_spec_test.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: pectra

#10850 Caplin: Self-recover snapshots gap
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/execution_engine_mock.go
  cl/phase1/execution_client/interface.go
  cl/phase1/stages/stage_history_download.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/execution/eth1/getters.go
Labels: caplin

#10876 retire bor files: don't stop after first iteration
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: polygon

#10951 Rename tx to txn for `transaction` obj (part 3/3)
  cl/persistence/format/snapshot_format/getters/execution_snapshot.go
  cmd/hack/hack.go
  core/state/intra_block_state.go
  core/state/txtask.go
  core/tracing/hooks.go
  core/types/blob_tx_wrapper.go
  core/types/block.go
  core/types/block_test.go
  erigon-lib/rlp/encode.go
  erigon-lib/state/domain.go
  erigon-lib/state/domain_test.go
  erigon-lib/state/history.go
  erigon-lib/state/inverted_index.go
  erigon-lib/txpool/fetch_test.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_senders.go
  ethstats/ethstats.go
  tests/bor/mining_test.go
  tests/statedb_insert_chain_transaction_test.go
  turbo/adapter/ethapi/api.go
  turbo/execution/eth1/block_building.go
  turbo/jsonrpc/eth_filters.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/otterscan_contract_creator.go
  turbo/jsonrpc/otterscan_generic_tracer.go
  turbo/jsonrpc/otterscan_search_trace.go
  turbo/jsonrpc/otterscan_transaction_by_sender_and_nonce.go
  turbo/jsonrpc/overlay_api.go
  turbo/jsonrpc/send_transaction_test.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
  turbo/jsonrpc/trace_types.go
  turbo/jsonrpc/tracing.go
  turbo/jsonrpc/txpool_api.go
  turbo/mock/txpool.go
  turbo/rpchelper/filters_test.go
  turbo/stages/blockchain_test.go
Labels: good-practices
