Repository erigontech/erigon, pull requests merged in 2024-02, with the labels that each got.

#9354 Added Full Lightclient Server support
  cl/beacon/beacontest/harness.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/data_test.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/harness/lightclient.yml
  cl/beacon/handler/harness_test.go
  cl/beacon/handler/lightclient.go
  cl/beacon/handler/pool.go
  cl/beacon/handler/test_data/blinded_block_1.json
  cl/beacon/handler/test_data/block_1.json
  cl/beacon/handler/test_data/light_client_bootstrap_1.json
  cl/beacon/handler/test_data/light_client_finality_1.json
  cl/beacon/handler/test_data/light_client_optimistic_1.json
  cl/beacon/handler/test_data/light_client_update_1.json
  cl/clparams/config.go
  cl/cltypes/clone.go
  cl/cltypes/light_client.go
  cl/cltypes/lightclient_utils/lightclient.go
  cl/cltypes/network.go
  cl/cltypes/network_test.go
  cl/cltypes/solid/hash_list.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/fork_graph/interface.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/forkchoice_mock.go
  cl/phase1/forkchoice/interface.go
  cl/sentinel/communication/topics.go
  cl/sentinel/handlers/blocks.go
  cl/sentinel/handlers/blocks_by_range_test.go
  cl/sentinel/handlers/blocks_by_root_test.go
  cl/sentinel/handlers/handlers.go
  cl/sentinel/handlers/heartbeats.go
  cl/sentinel/handlers/light_client.go
  cl/sentinel/handlers/light_client_test.go
  cl/sentinel/sentinel.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/sentinel_requests_test.go
  cl/sentinel/service/start.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  cmd/sentinel/main.go
  erigon-lib/kv/tables.go
  eth/backend.go
Labels: caplin

#9367 eth/stagedsync: fix span fetch logic for span 0 and 1
  eth/stagedsync/bor_heimdall_shared.go
  eth/stagedsync/stage_bor_heimdall_test.go
  polygon/bor/bor.go
  polygon/bor/span_id.go
Labels: polygon

#9368 eth/stagedsync: minor code style cleanup of stage_bor_heimdall.go
  eth/stagedsync/stage_bor_heimdall.go
Labels: polygon

#9169 silkworm: libmdbx version check
  eth/backend.go
  go.mod
  go.sum
Labels: silkworm

#9395 polygon/sync: cleanup waypoint naming
  polygon/heimdall/waypoint.go
  polygon/sync/accumulated_headers_verifier.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
Labels: polygon

#9409 Schedule Dencun on mainnet
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/mainnet.json
Labels: dencun

#9412 silkworm: dev env using local silkworm-go
  turbo/silkworm/silkworm_go_devenv.sh
Labels: silkworm

#9406 Add totalBlobPoolLimit flag
  cmd/txpool/main.go
  cmd/utils/flags.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  eth/ethconfig/tx_pool.go
  turbo/cli/default_flags.go
Labels: dencun

#9411 bor-mainnet: remove lost files after 50.5M
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: polygon

#9393 [Caplin Archive node]: full sepolia read experiment bug fixes
  cl/antiquary/state_antiquary.go
  cl/clstages/clstages.go
  cl/persistence/state/epoch_data.go
  cl/persistence/state/epoch_data_test.go
  cl/persistence/state/historical_states_reader/historical_states_reader.go
  cl/persistence/state/historical_states_reader/historical_states_reader_test.go
  cl/persistence/state/slot_data.go
  cl/persistence/state/slot_data_test.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/on_operations.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/stages/clstages.go
  rpc/http.go
Labels: caplin

#9413 Hive: Do not validate payload attributes if nil or syncing and pre-cancun check
  turbo/engineapi/engine_server.go
Labels: dencun

#9425 bor event reader: stop snaps iteration earlier
  turbo/snapshotsync/freezeblocks/block_reader.go
Labels: polygon

#9433 Schedule Dencun for Gnosis
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/gnosis.json
Labels: gnosis, dencun

#9414 [Caplin] More efficient Archive format
  cl/antiquary/antiquary.go
  cl/antiquary/state_antiquary.go
  cl/antiquary/state_antiquary_test.go
  cl/antiquary/tests/tests.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/utils_test.go
  cl/clparams/config.go
  cl/persistence/base_encoding/primitives_test.go
  cl/persistence/base_encoding/uint64_diff.go
  cl/persistence/beacon_indicies/indicies.go
  cl/persistence/block_saver.go
  cl/persistence/block_saver_test.go
  cl/persistence/block_store.go
  cl/persistence/interface.go
  cl/persistence/raw_block_saver.go
  cl/persistence/state/historical_states_reader/historical_states_reader.go
  cl/persistence/state/historical_states_reader/historical_states_reader_test.go
  cl/persistence/state/slot_data.go
  cl/persistence/state/state_accessors.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/forkchoice_mock.go
  cl/phase1/forkchoice/interface.go
  cl/phase1/forkchoice/on_attestation.go
  cl/phase1/main.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/sentinel/gossip.go
  cl/sentinel/handlers/blocks.go
  cl/sentinel/handlers/blocks_by_range_test.go
  cl/sentinel/handlers/blocks_by_root_test.go
  cl/sentinel/handlers/handlers.go
  cl/sentinel/handlers/utils_test.go
  cl/sentinel/sentinel.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/sentinel_requests_test.go
  cl/sentinel/service/notifiers.go
  cl/sentinel/service/start.go
  cl/utils/bytes.go
  cmd/capcli/cli.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  cmd/tooling/cli.go
  erigon-lib/kv/tables.go
  eth/backend.go
  go.mod
  go.sum
  turbo/snapshotsync/freezeblocks/beacon_block_reader.go
  turbo/snapshotsync/freezeblocks/caplin_snapshots.go
Labels: caplin

#9421 Caplin: Added prebuffering to execution blocks
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cmd/capcli/cli.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
Labels: caplin

#9453 silkworm: seg compressor fuzz test
  erigon-lib/compress/compress.go
  erigon-lib/compress/silkworm_seg_fuzz_test.go
Labels: silkworm

#9457 Prevents DDOS attempts on the Beacon API.
  cl/beacon/handler/attestation_rewards.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/committees.go
  cl/beacon/handler/data_test.go
  cl/beacon/handler/duties_attester.go
  cl/beacon/handler/duties_proposer.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/harness/lighthouse.yml
  cl/beacon/handler/harness_test.go
  cl/beacon/handler/lighthouse.go
  cl/beacon/handler/test_data/harness_inclusion_global_1.json
  cl/beacon/handler/test_data/harness_inclusion_local_1.json
  cl/beacon/handler/validators.go
  cl/beacon/router.go
  cl/beacon/synced_data/synced_data.go
  cl/persistence/base_encoding/primitives_test.go
  cl/persistence/base_encoding/uint64_diff.go
  cl/persistence/state/historical_states_reader/historical_states_reader.go
  cl/phase1/forkchoice/fork_graph/diff_storage/diff_storage.go
  cl/phase1/forkchoice/fork_graph/diff_storage/diff_storage_test.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/fork_graph/interface.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/forkchoice_mock.go
  cl/phase1/forkchoice/interface.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/stages/clstages.go
  cl/sentinel/service/service.go
  go.mod
Labels: caplin

#9458 Made caplin endpoints flaggable and added documentation to the README.
  README.md
  cl/beacon/beacon_router_configuration/cfg.go
  cl/beacon/beaconhttp/api.go
  cl/beacon/handler/attestation_rewards.go
  cl/beacon/handler/events.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/utils_test.go
  cl/beacon/handler/validators.go
  cl/beacon/router.go
  cl/beacon/validatorapi/get.go
  cl/beacon/validatorapi/handler.go
  cl/beacon/validatorapi/helpers.go
  cl/beacon/validatorapi/post.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/fork_graph/fork_graph_test.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/utils.go
  cl/spectest/consensus_tests/fork_choice.go
  cmd/caplin-regression/regression/tester.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/caplincli/config.go
  cmd/caplin/caplinflags/flags.go
  cmd/caplin/main.go
  cmd/utils/flags.go
Labels: caplin

#9462 Added benchmarking tool for Beacon API's endpoints
  Dockerfile
  Dockerfile.debian
  Makefile
  README.md
  cl/antiquary/state_antiquary.go
  cl/beacon/beacon_router_configuration/cfg.go
  cl/beacon/handler/attestation_rewards.go
  cl/beacon/router.go
  cl/beacon/synced_data/synced_data.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/on_operations.go
  cl/phase1/network/backward_beacon_downloader.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/spectest/consensus_tests/fork_choice.go
  cl/spectest/consensus_tests/rewards.go
  cl/transition/impl/eth2/operations.go
  cmd/capcli/cli.go
  cmd/caplin-regression/.gitignore
  cmd/caplin-regression/Makefile
  cmd/caplin-regression/README.md
  cmd/caplin-regression/main.go
  cmd/caplin-regression/regression/reader.go
  cmd/caplin-regression/regression/tester.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#9399 polygon/p2p: implement download headers
  erigon-lib/direct/sentry_client.go
  erigon-lib/direct/sentry_client_mock.go
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  polygon/p2p/downloader.go
  polygon/p2p/message_broadcaster.go
  polygon/p2p/message_listener.go
  polygon/p2p/message_observer.go
  polygon/p2p/peer_id.go
  polygon/p2p/peer_penalizer.go
  polygon/p2p/peer_sync_progress.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/p2p/service_test.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/peer_with_block_num_info.go
  polygon/sync/sentry.go
  polygon/sync/sentry_mock.go
  polygon/sync/storage.go
Labels: polygon

#9310 Caplin: blob storage
  cl/clparams/config.go
  cl/cltypes/blob_sidecar.go
  cl/persistence/blob_storage/blob.go
  cl/persistence/blob_storage/blob_db_test.go
  cl/phase1/forkchoice/on_block.go
  cl/spectest/consensus_tests/appendix.go
  go.mod
Labels: dencun, caplin

#9467 polygon/sync: refactor HeaderStore
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/headers_writer_mock.go
  polygon/sync/storage.go
  polygon/sync/storage_mock.go
Labels: polygon

#9473 remove bor events after 46M
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: release

#9474 mainnet: remove beacon after 8M
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: release

#9477 Caplin: Added `BlobSidecar` network support
  cl/cltypes/network.go
  cl/cltypes/network_test.go
  cl/gossip/gossip.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/rpc/rpc.go
  cl/sentinel/service/notifiers.go
  cl/sentinel/service/service.go
  cl/sentinel/service/start.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/downloader/downloader.pb.go
  erigon-lib/gointerfaces/execution/execution.pb.go
  erigon-lib/gointerfaces/remote/ethbackend.pb.go
  erigon-lib/gointerfaces/remote/kv.pb.go
  erigon-lib/gointerfaces/sentinel/sentinel.pb.go
  erigon-lib/gointerfaces/sentry/sentry.pb.go
  erigon-lib/gointerfaces/txpool/mining.pb.go
  erigon-lib/gointerfaces/txpool/txpool.pb.go
  erigon-lib/gointerfaces/types/types.pb.go
Labels: caplin

#9488 snapshots: fix filesByRange (#9472)
  erigon-lib/downloader/snaptype/type.go
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: release

#9471 Dont append full wrapped blobtx to filters
  core/types/transaction.go
  core/types/transaction_test.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/testdata.go
  erigon-lib/types/txn.go
  turbo/rpchelper/filters.go
Labels: dencun

#9469 Caplin: Store blobs to DB
  cl/antiquary/antiquary.go
  cl/antiquary/state_antiquary.go
  cl/antiquary/tests/tests.go
  cl/beacon/handler/utils_test.go
  cl/persistence/blob_storage/blob.go
  cl/persistence/blob_storage/blob_db_test.go
  cl/persistence/state/historical_states_reader/historical_states_reader.go
  cl/sentinel/sentinel_requests_test.go
  cmd/capcli/cli.go
  cmd/caplin/caplin1/run.go
  cmd/caplin/main.go
  cmd/tooling/cli.go
  erigon-lib/common/datadir/dirs.go
  erigon-lib/kv/tables.go
  eth/backend.go
  go.mod
Labels: caplin

#9495 Caplin: Fixed race condition in block downloading
  cl/phase1/network/backward_beacon_downloader.go
  cl/phase1/stages/clstages.go
  cl/phase1/stages/stage_history_download.go
  cl/transition/impl/eth2/operations.go
  cmd/capcli/cli.go
Labels: caplin

#9487 bor-mainnet: 53m blocks - without event/spans
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: polygon

#9516 silkworm: make install FAQ
  README.md
Labels: silkworm

#9461 polygon/p2p: implement peer tracker
  polygon/p2p/fetcher.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/message_listener.go
  polygon/p2p/peer_sync_progress.go
  polygon/p2p/peer_sync_progress_test.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/p2p/service_test.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
Labels: polygon

#9520 polygon/sync: use header downloader interface
  polygon/p2p/peer_sync_progress.go
  polygon/p2p/peer_sync_progress_test.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/sync.go
Labels: polygon

#9478 polygon/sync: span updates
  polygon/heimdall/heimdall.go
  polygon/heimdall/heimdall_mock.go
  polygon/heimdall/heimdall_no_store.go
  polygon/heimdall/heimdall_no_store_mock.go
  polygon/sync/service.go
  polygon/sync/spans_cache.go
  polygon/sync/sync.go
  polygon/sync/sync_to_tip_events.go
Labels: polygon
