Repository erigontech/erigon, pull requests merged in 2024-07, with the labels that each got.

#10934 polygon/bridge: Execution integration
  cmd/integration/commands/stages.go
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/merge/merge.go
  core/blockchain.go
  eth/backend.go
  eth/ethconsensusconfig/config.go
  eth/stagedsync/exec3.go
  eth/stagedsync/stage_polygon_sync.go
  eth/stagedsync/stagedsynctest/harness.go
  polygon/bor/bor.go
  polygon/bor/bor_test.go
  polygon/bridge/bridge.go
  polygon/bridge/db.go
  polygon/sync/service.go
  polygon/sync/store.go
  polygon/sync/store_mock.go
  polygon/sync/sync.go
  turbo/stages/stageloop.go
Labels: polygon

#10941 polygon/bridge: Add bridge tests
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
  polygon/bridge/db.go
Labels: polygon

#10978 tests: Undo skip EIP-7685 spec tests
  tests/exec_spec_test.go
Labels: pectra

#10983 polygon: Fix type mismatch during check
  polygon/bor/bor.go
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
  polygon/bridge/db.go
Labels: polygon

#10994 polygon: Fix interface nil check
  eth/backend.go
  polygon/bor/bor.go
Labels: polygon

#10963 engineapi: Add pectra engine api changes
  cl/phase1/execution_client/execution_client_rpc.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/engineapi/interface.go
Labels: pectra

#11029 params: update amoy bootnodes
  params/bootnodes.go
  params/bootnodes_amoy.go
Labels: polygon, astrid

#11037 dl: discover webseeds even if this file type is prohibited by .lock
  erigon-lib/downloader/webseed.go
Labels: erigon3

#11003 Improve & fix several bugs as caplin paired with lodestar
  cl/aggregation/pool_impl.go
  cl/beacon/beaconhttp/beacon_response.go
  cl/beacon/handler/block_production.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/validators.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_kzgcommitment.go
  cl/cltypes/block_production.go
  cl/cltypes/eth1_block.go
  cl/cltypes/solid/list_ssz.go
  cl/phase1/network/services/attestation_service.go
  cl/ssz/decode.go
  cl/validator/committee_subscription/committee_subscription.go
Labels: caplin

#11056 Caplin: Fixed backward downloader on Holesky
  cl/phase1/stages/stage_history_download.go
Labels: caplin

#10812 Implement EIP-7702: set code tx
  accounts/abi/bind/backends/simulated.go
  cmd/evm/internal/t8ntool/transition.go
  core/state/intra_block_state.go
  core/state_transition.go
  core/types/access_list_tx.go
  core/types/authorization.go
  core/types/blob_tx.go
  core/types/blob_tx_wrapper.go
  core/types/dynamic_fee_tx.go
  core/types/encdec_test.go
  core/types/legacy_tx.go
  core/types/receipt.go
  core/types/set_code_tx.go
  core/types/transaction.go
  core/types/transaction_marshalling.go
  core/types/transaction_signing.go
  core/vm/evmtypes/evmtypes.go
  core/vm/runtime/runtime.go
  erigon-lib/common/fixedgas/protocol.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  erigon-lib/types/txn.go
  interfaces.go
  params/protocol_params.go
  rlp/encode.go
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/address_from_set_code.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/ext_code_on_set_code.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/self_code_on_set_code.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_call_set_code.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_invalid_authorization_tuple.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_multiple_valid_authorization_tuples_first_invalid_same_signer.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_multiple_valid_authorization_tuples_same_signer.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_to_account_deployed_in_same_tx.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_to_contract_creator.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_to_self_caller.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_to_self_destruct.json
  tests/execution-spec-tests/prague/eip7702_eoa_code_tx/eoa_code_txs/set_code_to_sstore.json
  tests/transaction_test_util.go
  turbo/jsonrpc/eth_api.go
Labels: pectra

#11152 Caplin: Added POST `Validators`
  cl/beacon/handler/handler.go
  cl/beacon/handler/validators.go
Labels: caplin

#11058 Caplin: Optimization and Parallelization of processes and reduction of Goroutines
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk_fs.go
  cl/phase1/forkchoice/fork_graph/interface.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/network/services/constants.go
  cl/phase1/stages/clstages.go
  cl/sentinel/discovery.go
  cl/sentinel/gossip.go
  cl/sentinel/sentinel.go
  cl/sentinel/sentinel_gossip_test.go
  cl/sentinel/service/start.go
  cl/transition/impl/eth2/operations.go
Labels: caplin, priority:high

#10923 refine ProcessBlock and ProcessBlindedBlock
  cl/beacon/handler/block_production.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_blinded.go
  cl/cltypes/beacon_block_interface.go
  cl/cltypes/block_production.go
  cl/transition/machine/block.go
  experiment/main.go
Labels: caplin

#11191 engineapi: Fix req list check
  turbo/engineapi/engine_server.go
Labels: pectra

#11215 Caplin: Remove TmpDB from `BlockCollector`
  cl/phase1/execution_client/block_collector/block_collector.go
  erigon-lib/etl/collector.go
Labels: caplin

#11218 post validator balances
  cl/beacon/handler/handler.go
  cl/beacon/handler/validators.go
  experiment/main.go
Labels: caplin

#11196 eth/stagedsync: polygon sync stage to use new heimdall service
  eth/backend.go
  eth/stagedsync/stage_polygon_sync.go
  polygon/heimdall/closed_range.go
  polygon/heimdall/entity_store.go
  turbo/stages/stageloop.go
Labels: polygon

#11235 txpool changes for set_code_tx support
  cmd/txpool/main.go
  core/types/encdec_test.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_fuzz_test.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpoolutil/all_components.go
  erigon-lib/types/txn.go
  erigon-lib/types/txn_test.go
  eth/backend.go
  turbo/stages/mock/mock_sentry.go
Labels: pectra

#11250 Caplin: Add support for beacon snapshots (also stops relying on Engine API)
  cl/clparams/config.go
  cl/clparams/initial_state/initial_state.go
  core/snaptype/block_types.go
  erigon-lib/chain/snapcfg/util.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  eth/backend.go
  go.mod
  go.sum
  params/chainspecs/holesky.json
  turbo/snapshotsync/snapshotsync.go
Labels: caplin

#11234 Wire OverridePragueTime into txpool
  cmd/utils/flags.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  erigon-lib/txpool/txpoolutil/all_components.go
Labels: pectra

#11319 diagnostics: syncstats lock issue
  erigon-lib/diagnostics/snapshots.go
  erigon-lib/diagnostics/snapshots_download.go
  erigon-lib/diagnostics/snapshots_indexing.go
  erigon-lib/diagnostics/snapshots_test.go
  erigon-lib/diagnostics/utils.go
  erigon-lib/diagnostics/utils_test.go
Labels: do-not-merge

#11301 Caplin: Added electra config support
  cl/clparams/config.go
Labels: pectra, caplin

#11222 block files: don't compress 1k and 10k files
  erigon-lib/state/appendable.go
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: priority:high, erigon3, complexity:low

#11340 polygon: move valset logic inside valset package
  polygon/bor/bor.go
  polygon/bor/snapshot.go
  polygon/bor/valset/validator_set.go
Labels: polygon

#11341 polygon/heimdall: add observer options
  polygon/heimdall/service.go
  polygon/heimdall/service_observer_options.go
  polygon/sync/tip_events.go
Labels: polygon

#11320 polygon/bridge: Fix bridge crash at chain tip
  polygon/bridge/db.go
Labels: polygon

#11346 core/types: Fix JSON (un)marshalling of request types
  core/types/consolidation_request.go
  core/types/deposit_request.go
  core/types/withdrawal_request.go
Labels: pectra

#11382 polygon/bridge: Set correct time limit
  polygon/bridge/bridge.go
  polygon/bridge/bridge_test.go
Labels: polygon

#11397 polygon/bridge: Set last event ID
  polygon/bridge/bridge.go
  polygon/bridge/db.go
Labels: polygon

#11348 polygon: sync stage fix blockRangeEntitiesFromBlockNum
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#11390 Remove support for Mumbai
  README.md
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/heimdall_test.go
  common/paths/paths.go
  core/allocs/mumbai.json
  core/forkid/forkid_test.go
  core/genesis_write.go
  core/system_contract_lookup.go
  erigon-lib/chain/networkname/network_name.go
  erigon-lib/chain/snapcfg/util.go
  eth/stagedsync/stage_bor_heimdall.go
  p2p/sentry/simulator/simulator_test.go
  params/bootnodes.go
  params/bootnodes_mumbai.go
  params/chainspecs/mumbai.json
  params/config.go
  params/config_test.go
  polygon/bor/snaptype/types.go
  polygon/bridge/bridge_test.go
  turbo/node/node.go
  turbo/snapshotsync/freezeblocks/block_snapshots_test.go
  turbo/stages/genesis_test.go
Labels: polygon

#11096 Caplin: Introduced cached merkle tree
  cl/cltypes/solid/hash_list.go
  cl/cltypes/solid/uint64_raw_list.go
  cl/cltypes/solid/uint64_vector.go
  cl/cltypes/solid/uint64slice_byte.go
  cl/cltypes/solid/uint64slice_byte_test.go
  cl/cltypes/solid/validator_set.go
  cl/merkle_tree/hasher.go
  cl/merkle_tree/merkle_root.go
  cl/merkle_tree/merkle_tree.go
  cl/merkle_tree/merkle_tree_test.go
  cl/phase1/core/state/raw/hashing.go
  cl/spectest/Makefile
Labels: caplin

#11407 astrid: fix for polygon sync stage bor events nil ptr
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#11399 polygon/heimdall: Add `ok` to output
  eth/stagedsync/stage_polygon_sync.go
  polygon/heimdall/entity_store.go
  polygon/heimdall/service.go
  turbo/snapshotsync/freezeblocks/block_reader.go
Labels: polygon
