Repository erigontech/erigon, pull requests merged in 2024-10, with the labels that each got.

#12142 rpc: Move Astrid snapshot reader
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#12148 polygon: fix bor_heimdall stage unwinding due to event processed blocks table
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#12173 polygon/heimdall: add ErrServiceUnavailable transient err
  polygon/bridge/bridge.go
  polygon/heimdall/service.go
Labels: polygon

#12202 polygon/sync: block downloader to handle possible gaps between last checkpoint and first milestone
  polygon/heimdall/checkpoint.go
  polygon/heimdall/milestone.go
  polygon/heimdall/reader.go
  polygon/heimdall/service.go
  polygon/sync/block_downloader.go
  polygon/sync/block_downloader_test.go
  polygon/sync/waypoint_reader.go
  polygon/sync/waypoint_reader_mock.go
Labels: polygon

#12177 astrid: stage integration to communicate execution errs back
  eth/stagedsync/stage_polygon_sync.go
  polygon/sync/execution_client.go
  polygon/sync/sync.go
Labels: polygon

#12166 turbo: remove duplicate log
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: imp2

#12224 polygon/sync,p2p: chain tip block fetch improvements
  polygon/p2p/fetcher_base.go
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_config.go
  polygon/p2p/fetcher_errors.go
  polygon/p2p/fetcher_penalizing.go
  polygon/p2p/fetcher_penalizing_test.go
  polygon/p2p/fetcher_tracking.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/sync/block_downloader_test.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
Labels: polygon

#12239 astrid: stage integration fix for no-op fcu
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#12221 Preserve requests nil-ness in (un)marshalling
  core/types/request.go
Labels: pectra

#12253 Bump gqlparser to 2.5.16 in the release/2.60 branch.
  go.mod
  go.sum
Labels: v2.60

#12261 e2: Fix state root calculation for EIP-7702 accounts with storage
  turbo/trie/trie_root.go
Labels: pectra

#12258 Preserve requests nil-ness in (un)marshalling
  core/types/request.go
Labels: pectra

#12269 polygon/sync: avoid dropping milestone events
  polygon/sync/event_channel.go
  polygon/sync/event_channel_test.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
  polygon/sync/tip_events_test.go
Labels: polygon

#12236 qa-tests: add tip-tracking for Gnosis on Erigon 3
  .github/workflows/qa-tip-tracking-gnosis.yml
Labels: gnosis

#12138 Flatten EIP-7002 withdrawal requests encoding
  consensus/misc/eip7002.go
  core/types/encdec_test.go
  core/types/request.go
  core/types/withdrawal_request.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/typesproto/types.pb.go
  params/protocol_params.go
  tests/exec_spec_test.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: pectra

#12167 Flatten EIP-7251 Consolidation Requests encoding
  consensus/misc/eip7251.go
  core/types/consolidation_request.go
  core/types/encdec_test.go
  core/types/request.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/typesproto/types.pb.go
  params/protocol_params.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: pectra

#12279 polygon/sync: improvements to composite tip events channel
  polygon/sync/event_channel.go
  polygon/sync/event_channel_test.go
  polygon/sync/tip_events.go
  polygon/sync/tip_events_test.go
Labels: polygon

#12315 Add early return in `ComputeTxEnv` for state sync transactions
  turbo/transactions/tracing.go
Labels: polygon

#12317 borcfg: GetStateReceiverContract returns common.Address
  erigon-lib/chain/chain_config.go
  eth/ethconsensusconfig/config.go
  eth/stagedsync/stagedsynctest/harness.go
  polygon/bor/borcfg/bor_config.go
  polygon/bor/state_receiver.go
  polygon/bridge/bridge.go
  polygon/bridge/reader.go
  polygon/tracer/trace_bor_state_sync_txn.go
Labels: polygon

#12316 Add early return in `ComputeTxEnv` for state sync transactions
  turbo/transactions/tracing.go
Labels: polygon

#12313 polygon/sync,p2p: astrid devp2p block announcements
  eth/stagedsync/stage_polygon_sync.go
  p2p/sentry/sentry_grpc_server.go
  polygon/p2p/message_sender.go
  polygon/p2p/message_sender_test.go
  polygon/p2p/peer_event_registrar.go
  polygon/p2p/peer_event_registrar_mock.go
  polygon/p2p/peer_tracker.go
  polygon/p2p/peer_tracker_test.go
  polygon/p2p/publisher.go
  polygon/p2p/publisher_test.go
  polygon/p2p/service.go
  polygon/p2p/service_mock.go
  polygon/sync/execution_client.go
  polygon/sync/sync.go
  polygon/sync/tip_events.go
Labels: polygon

#12296 Do not cancel in progress jobs in case of 'main' branch.
  .github/workflows/ci.yml
Labels: devops

#12029 fix: err msg for eth_callMany
  turbo/jsonrpc/eth_callMany.go
Labels: v2.60

#12096 Removing gasPrice check in UnmarshalJson of dynamicFeeTx
  core/types/transaction_marshalling.go
Labels: v2.60

#12330 Do not cancel in progress jobs for 'main' and latest release branches.
  .github/workflows/ci.yml
Labels: devops

#12331 Rework release workflow for release/2.60 branch
  .github/workflows/release.yml
  Dockerfile.release
Labels: devops, v2.60

#12345 polygon/bridge: fix BorTxLookup encoding discrepancy
  polygon/bridge/db.go
Labels: polygon

#12347 astrid: fix ReportBadHeaderPoS nil ptr in standalone
  eth/stagedsync/exec3.go
  eth/stagedsync/stage_execute.go
  eth/stagedsync/stage_senders.go
Labels: polygon

#12364 rpcdaemon: Add missing flag
  turbo/jsonrpc/tracing.go
  turbo/transactions/tracing.go
Labels: polygon

#12359 rpcdaemon: Fix missing data in Bor receipts
  turbo/jsonrpc/receipts/bor_receipts_generator.go
Labels: polygon

#12365 rpcdaemon: Support Astrid on `debug_*` endpoints
  polygon/bridge/reader.go
  polygon/tracer/trace_bor_state_sync_txn.go
  turbo/jsonrpc/erigon_receipts.go
  turbo/jsonrpc/eth_api.go
  turbo/jsonrpc/eth_receipts.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/tracing.go
Labels: polygon

#12371 Introduce GOAMD64 variable with default=v2 for AMD64 arch.
  Makefile
Labels: devops, performance

#12373 e2: rpcd to not open file before download complete
  cmd/rpcdaemon/cli/config.go
  cmd/rpcdaemon/main.go
  core/rawdb/accessors_metadata.go
  eth/backend.go
Labels: v2.60

#12375 e2: don't reopen files when new created
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: v2.60

#12360 turbo/jsonrpc: correction in fetching validatorByte in bor_snapshot.go
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#12374 e2: up `bls` dep to support clang16
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: v2.60

#12352 Add workflow for docker image removal.
  .github/workflows/docker-image-remove.yml
Labels: devops

#12397 Update docker-image-remove.yml
  .github/workflows/docker-image-remove.yml
Labels: devops

#12400 dbg: env var for heap profile output file path
  erigon-lib/common/dbg/experiments.go
Labels: polygon

#12404 headerdownload: fix OOM due to inifinitely growing children in link
  turbo/stages/headerdownload/header_algos.go
Labels: polygon

#12405 headerdownload: fix OOM due to inifinitely growing children in link
  turbo/stages/headerdownload/header_algos.go
Labels: polygon

#12408 rpcdaemon: Set correct tx index when generating Bor receipts
  turbo/jsonrpc/receipts/bor_receipts_generator.go
Labels: polygon

#12369 Rename requestsRoot to requestsHash in block header
  cmd/evm/internal/t8ntool/execution.go
  cmd/evm/internal/t8ntool/gen_stenv.go
  cmd/evm/internal/t8ntool/transition.go
  consensus/clique/verifier.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  core/genesis_write.go
  core/types/block.go
  core/types/gen_genesis.go
  core/types/gen_header_json.go
  core/types/genesis.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/executionproto/execution.pb.go
  polygon/bor/bor.go
  tests/block_test_util.go
  tests/gen_btheader.go
  turbo/adapter/ethapi/api.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/execution/eth1/eth1_utils/grpc.go
  turbo/stages/bodydownload/body_algos.go
Labels: pectra

#12370 Remove EIP-7685 requests from body, block and exeution payload
  cl/cltypes/beacon_block_test.go
  cl/phase1/execution_client/block_collector/block_collector.go
  cl/phase1/execution_client/execution_client_direct.go
  cmd/evm/internal/t8ntool/execution.go
  cmd/evm/internal/t8ntool/gen_stenv.go
  cmd/evm/internal/t8ntool/transition.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/historical_trace_worker.go
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  core/blockchain.go
  core/chain_makers.go
  core/genesis_write.go
  core/rawdb/accessors_chain.go
  core/rawdb/accessors_chain_test.go
  core/rawdb/accessors_indexes_test.go
  core/types/block.go
  core/types/block_test.go
  core/types/encdec_test.go
  eth/protocols/eth/protocol.go
  eth/stagedsync/exec3.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_mining_finish.go
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  polygon/bor/bor.go
  polygon/p2p/message_listener_test.go
  tests/statedb_insert_chain_transaction_test.go
  turbo/adapter/ethapi/api.go
  turbo/engineapi/engine_block_downloader/block_downloader.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/block_building.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/execution/eth1/eth1_utils/grpc.go
  turbo/execution/eth1/eth1_utils/grpc_test.go
  turbo/execution/eth1/getters.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/stages/bodydownload/body_algos.go
Labels: pectra

#12337 Engine API and type changes for flat requests in Pectra
  cmd/rpcdaemon/cli/config.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/state.go
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  consensus/misc/eip7002.go
  consensus/misc/eip7251.go
  core/blockchain.go
  core/chain_makers.go
  core/state/txtask.go
  core/types/block.go
  core/types/consolidation_request.go
  core/types/deposit_request.go
  core/types/eip7685_requests.go
  core/types/encdec_test.go
  core/types/request.go
  core/types/withdrawal_request.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/executionproto/execution.pb.go
  erigon-lib/gointerfaces/typesproto/types.pb.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  polygon/bor/bor.go
  polygon/bor/fake.go
  tests/exec_spec_test.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
  turbo/engineapi/interface.go
  turbo/execution/eth1/block_building.go
  turbo/stages/bodydownload/body_algos.go
  turbo/stages/bodydownload/body_data_struct.go
Labels: pectra

#12425 Don't pass requests to consensus Finalize
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/historical_trace_worker.go
  cmd/state/exec3/state.go
  cmd/state/exec3/state_recon.go
  consensus/aura/aura.go
  consensus/clique/clique.go
  consensus/consensus.go
  consensus/ethash/consensus.go
  consensus/merge/merge.go
  core/blockchain.go
  core/chain_makers.go
  core/state/txtask.go
  eth/stagedsync/stage_mining_exec.go
  polygon/bor/bor.go
  polygon/bor/fake.go
Labels: pectra

#12426 Remove remnants of requests from block body downloader
  p2p/sentry/sentry_multi_client/sentry_multi_client.go
  turbo/stages/bodydownload/body_algos.go
  turbo/stages/bodydownload/body_data_struct.go
Labels: pectra

#12388 Simplify EIP-6110 Deposit requests
  consensus/merge/merge.go
  consensus/misc/eip6110.go
  core/types/deposit_request.go
  core/types/eip7685_requests.go
  core/types/encdec_test.go
Labels: pectra

#12436 rpcdaemon: Get state at end of the block when generating Bor receipts
  turbo/jsonrpc/receipts/bor_receipts_generator.go
Labels: polygon

#12416 Modify EIP-7702 Txn impl per pectra-devnet-4 specs
  core/state_transition.go
  core/types/authorization.go
  erigon-lib/common/fixedgas/protocol.go
  tests/exec_spec_test.go
Labels: pectra

#12435 rpcdaemon: Remove spanProducersReader from snapshot
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#12465 engineapi: Fix json unmarshal issue
  turbo/engineapi/engine_server.go
  turbo/engineapi/interface.go
Labels: pectra

#12441 optimise a.blsToExecutionChangeService.ProcessMessage with async sign…
  cl/beacon/handler/pool.go
  cl/beacon/handler/utils_test.go
  cl/cltypes/bls_to_execution_change.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/batch_signature_verification.go
  cl/phase1/network/services/bls_to_execution_change_service.go
  cl/phase1/network/services/bls_to_execution_change_service_test.go
  cl/phase1/network/services/global_mock_test.go
  cl/phase1/network/services/interface.go
  cl/phase1/network/services/mock_services/bls_to_execution_change_service_mock.go
  cmd/caplin/caplin1/run.go
Labels: caplin

#12492 Use cache only for main and latest two release branches.
  .github/workflows/test-integration-caplin.yml
Labels: devops

#12487 engine: Remove engine_getPayloadBodiesBy{Hash|Range}V2
  turbo/engineapi/engine_server.go
  turbo/engineapi/interface.go
Labels: pectra

#12526 params: Update depositContractAddress field in json's
  params/chainspecs/chiado.json
  params/chainspecs/gnosis.json
  params/chainspecs/holesky.json
  params/chainspecs/mainnet.json
  params/chainspecs/sepolia.json
Labels: pectra

#12559 trace API: commit state changes from InitializeBlockExecution
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
Labels: dencun

#12544 Fix multiple hive/EEST issues + wait condition loop before sending SYNCING
  consensus/merge/merge.go
  consensus/misc/eip6110.go
  consensus/misc/eip7002.go
  consensus/misc/eip7251.go
  core/types/block.go
  eth/ethconfig/gen_config.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/block_building.go
Labels: pectra
