Repository erigontech/erigon, pull requests merged in 2024-11, with the labels that each got.

#12506 Bor Mainnet dns discovery
  eth/backend.go
  eth/discovery.go
  p2p/sentry/sentry_grpc_server.go
  p2p/server.go
  params/bootnodes.go
Labels: polygon

#12588 Fix bug with sending empty requests list in pectra-devnet-4
  eth/stagedsync/stage_mining_finish.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: pectra

#12606 Fix bug with sending empty requests list in pectra-devnet-4 (#12588)
  eth/stagedsync/stage_mining_finish.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: pectra

#12599 workflows: Add ethereum/eest separate workflow
  .github/workflows/test-hive-eest.yml
  Makefile
Labels: pectra

#12574 EIP-4844-pectra (collect blob gas fee)
  core/state_transition.go
  erigon-lib/chain/chain_config.go
Labels: gnosis, pectra

#12614 workflows: Add ethereum/eest separate workflow (#12599)
  .github/workflows/test-hive-eest.yml
  Makefile
Labels: pectra

#12582 Re-added missing astrid flags to UnwindHeimdall
  polygon/bor/bordb/prune.go
Labels: polygon, imp1

#12658 Sync GIT_TAG with main branch
  Makefile
Labels: devops

#12685 polygon: tidy up proto import aliases
  polygon/bor/bor_test.go
  polygon/p2p/fetcher_base_test.go
  polygon/p2p/fetcher_penalizing_test.go
  polygon/p2p/fetcher_tracking_test.go
  polygon/p2p/message_listener_test.go
  polygon/p2p/message_sender.go
  polygon/p2p/peer_penalizer.go
Labels: polygon

#12716 cl: fix chiado
  cl/clparams/config.go
  cl/phase1/core/checkpoint_sync/remote_checkpoint_sync.go
Labels: shutter

#12721 Create git tag before release build, small cosmetic changes.
  .github/workflows/release.yml
Labels: devops

#12724 Bump builder image to 1.23.3-alpine3.20
  .github/workflows/ci-cd-main-branch-docker-images.yml
Labels: devops

#12686 polygon/heimdall: tidy client naming
  Makefile
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/heimdall_test.go
  cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
  cmd/integration/commands/stages.go
  erigon-lib/Makefile
  eth/backend.go
  eth/ethconsensusconfig/config.go
  eth/stagedsync/bor_heimdall_shared.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_polygon_sync.go
  eth/stagedsync/stagedsynctest/harness.go
  polygon/bor/bor.go
  polygon/bor/bor_internal_test.go
  polygon/bor/finality/whitelist.go
  polygon/bor/finality/whitelist_helpers.go
  polygon/bridge/service_test.go
  polygon/heimdall/client.go
  polygon/heimdall/client_http.go
  polygon/heimdall/client_http_test.go
  polygon/heimdall/client_mock.go
  polygon/heimdall/event_fetch_test.go
  polygon/heimdall/http_client_mock.go
  polygon/heimdall/http_request_handler.go
  polygon/heimdall/http_request_handler_mock.go
  polygon/heimdall/service.go
  polygon/heimdall/service_test.go
  polygon/heimdall/snapshots.go
  turbo/jsonrpc/bor_api_test.go
  turbo/stages/stageloop.go
Labels: polygon

#12782 polygon: fix linter
  eth/stagedsync/stage_polygon_sync.go
Labels: polygon

#12800 cl: fix caplin interop with lighthouse vc on gnosis
  cl/clparams/config.go
  eth/stagedsync/stages/sync_mode.go
Labels: gnosis, caplin, shutter

#12804 Block building fixes found for large deposit requests set
  consensus/merge/merge.go
  consensus/misc/eip6110.go
  turbo/builder/block_builder.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/block_building.go
Labels: pectra

#12807 Cherry pick PR12658 & PR12721 form release/2.60
  .github/workflows/release.yml
  Makefile
Labels: devops

#12844 Fix init cmd aura seal signature import
  core/genesis_write.go
  core/types/gen_aura_seal.go
  core/types/gen_genesis.go
  core/types/genesis.go
Labels: gnosis, pectra

#12831 txnprovider: introduce txnprovider concept into block production
  cmd/integration/commands/stages.go
  cmd/integration/commands/state_stages.go
  cmd/txpool/main.go
  core/types/transaction.go
  eth/backend.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_mining_finish.go
  turbo/stages/mock/mock_sentry.go
  txnprovider/provider.go
  txnprovider/provider_composite.go
  txnprovider/provider_shutter.go
  txnprovider/provider_txnpool_ordered.go
  txnprovider/provider_txnpool_unordered.go
  txnprovider/shutter/pool.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_mock.go
  txnprovider/txpool/pool_test.go
  txnprovider/txpool/txpool_grpc_server.go
  txnprovider/txpool/txpoolutil/all_components.go
Labels: shutter

#12904 Update ci-cd-main-branch-docker-images.yml
  .github/workflows/ci-cd-main-branch-docker-images.yml
Labels: devops
