Repository erigontech/erigon, pull requests merged in 2024-01, with the labels that each got.

#9116 Schedule Dencun for Görli
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/goerli.json
Labels: dencun

#9117 polygon/sync: canonical chain builder
  cmd/devnet/networks/devnet_bor.go
  cmd/devnet/services/polygon/heimdall.go
  cmd/rpcdaemon/cli/config.go
  consensus/bor/bor.go
  consensus/bor/bor_test.go
  consensus/bor/borcfg/bor_config.go
  consensus/bor/borcfg/bor_config_test.go
  consensus/bor/heimdall/span/span_id.go
  consensus/bor/heimdall/span/span_id_test.go
  consensus/bor/heimdall/span/spanner.go
  consensus/bor/snapshot.go
  consensus/bor/valset/validator_set.go
  consensus/misc/eip1559.go
  core/forkid/forkid.go
  core/rawdb/accessors_metadata.go
  core/system_contract_lookup.go
  erigon-lib/chain/chain_config.go
  erigon-lib/common/collections.go
  erigon-lib/txpool/txpooluitl/all_components.go
  eth/ethconfig/config.go
  eth/ethconsensusconfig/config.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_bor_heimdall_test.go
  eth/stagedsync/stage_txlookup.go
  eth/stagedsync/stagedsynctest/chain_configs.go
  eth/stagedsync/stagedsynctest/harness.go
  params/config.go
  polygon/sync/canonical_chain_builder.go
  polygon/sync/canonical_chain_builder_test.go
  polygon/sync/difficulty.go
  polygon/sync/difficulty_test.go
  polygon/sync/heimdall.go
  polygon/sync/mock/canonical_chain_builder_mock.go
  tests/bor/helper/miner.go
  turbo/jsonrpc/bor_helper.go
  turbo/jsonrpc/bor_snapshot.go
  turbo/jsonrpc/eth_block.go
  turbo/snapshotsync/freezeblocks/dump_test.go
Labels: polygon

#9145 bor: BorConfig setup fix
  cmd/devnet/devnet/node.go
  cmd/integration/commands/stages.go
  cmd/state/commands/check_change_sets.go
  eth/backend.go
  eth/ethconfig/config.go
Labels: polygon

#9146 stagedsync: implement bor span for chain reader and fix loggers
  consensus/clique/snapshot_test.go
  core/block_validator_test.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_bodies.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_mining_finish.go
Labels: polygon

#9137 polygon/sync: canonical chain builder unit tests
  polygon/sync/canonical_chain_builder_test.go
  polygon/sync/difficulty.go
  polygon/sync/difficulty_test.go
Labels: polygon

#9149 stagedsync: fix bor heimdall mining flow
  consensus/bor/bor.go
  eth/backend.go
  eth/stagedsync/bor_heimdall_shared.go
  eth/stagedsync/default_stages.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_mining_bor_heimdall.go
  eth/stagedsync/stagebuilder.go
  eth/stagedsync/stages/stages.go
Labels: polygon

#9180 remotedbserver: add support for bor snapshots
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/kv/mdbx/kv_abstract_test.go
  erigon-lib/kv/remotedbserver/mock/snapshots_mock.go
  erigon-lib/kv/remotedbserver/remotedbserver.go
  erigon-lib/kv/remotedbserver/remotedbserver_test.go
  erigon-lib/tools.go
  eth/backend.go
  turbo/stages/mock/mock_sentry.go
Labels: polygon

#9182 bor: fix for TestMiningBenchmark
  eth/backend.go
Labels: polygon

#9184 Schedule Dencun for Chiado
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/chiado.json
Labels: gnosis, dencun

#9183 devnet: fix infinite recursion & enable TestStateSync & TestCallContract integration tests
  cmd/devnet/devnet/context.go
  cmd/devnet/tests/bor/devnet_test.go
  cmd/devnet/tests/generic/devnet_test.go
Labels: polygon

#9188 Fix DenebForkEpoch for Chiado
  cl/clparams/config.go
Labels: gnosis, dencun

#9212 Mumbai uploader regression fixes
  eth/stagedsync/stage_bor_heimdall.go
  turbo/app/snapshots_cmd.go
Labels: polygon

#9217 caplin state_antiqate: reduce worst case ram limit
  cl/antiquary/state_antiquary.go
Labels: caplin

#9093 Deneb integration to Caplin
  cl/abstract/beacon_state.go
  cl/clparams/config.go
  cl/cltypes/eth1_header.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/forkchoice/on_operations.go
  cl/spectest/Makefile
  cl/transition/impl/eth2/operations.go
  cl/transition/impl/eth2/statechange/process_registry_updates.go
Labels: dencun, caplin

#9021 Removed the check for milestoneID in the GetVoteOnHash()
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#9220 Don't run pos downloader or engine api for bor
  eth/backend.go
Labels: polygon

#9224 polygon: refactor header validations for reuse in sync
  polygon/bor/bor.go
  polygon/bor/snapshot.go
  polygon/sync/canonical_chain_builder.go
  polygon/sync/header_validator.go
  turbo/jsonrpc/bor_snapshot.go
Labels: polygon

#9219 Fix startup sync for txpool processing for bor block production
  cmd/txpool/main.go
  consensus/misc/eip1559.go
  erigon-lib/chain/chain_config.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_fuzz_test.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpooluitl/all_components.go
  eth/backend.go
  eth/stagedsync/stage_execute.go
  turbo/shards/state_change_accumulator.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/snapshotsync/freezeblocks/block_snapshots.go
  turbo/stages/mock/mock_sentry.go
Labels: polygon

#9229 polygon/sync: span updates
  polygon/sync/canonical_chain_builder.go
  polygon/sync/canonical_chain_builder_test.go
  polygon/sync/difficulty.go
  polygon/sync/difficulty_test.go
  polygon/sync/header_time_validator.go
  polygon/sync/spans_cache.go
Labels: polygon

#9232 polygon/sync: move PeersWithBlockNumInfo and mocks, refactor bor.GetRootHash
  polygon/bor/bor.go
  polygon/sync/canonical_chain_builder.go
  polygon/sync/canonical_chain_builder_mock.go
  polygon/sync/db.go
  polygon/sync/db_mock.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/header_verifier.go
  polygon/sync/heimdall.go
  polygon/sync/heimdall_mock.go
  polygon/sync/peer_with_block_num_info.go
  polygon/sync/sentry.go
  polygon/sync/sentry_mock.go
  polygon/sync/state_point_headers_verifier.go
Labels: polygon

#9230 polygon/heimdall: drop GRPC support
  cmd/devnet/args/node_args.go
  cmd/devnet/main.go
  cmd/devnet/networks/devnet_bor.go
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/heimdall_test.go
  cmd/devnet/services/polygon/statesync.go
  cmd/devnet/tests/context.go
  cmd/integration/commands/flags.go
  cmd/integration/commands/stages.go
  cmd/utils/flags.go
  eth/backend.go
  eth/ethconfig/config.go
  go.mod
  go.sum
  polygon/heimdall/heimdall.go
  polygon/heimdall/heimdallgrpc/checkpoint.go
  polygon/heimdall/heimdallgrpc/client.go
  polygon/heimdall/heimdallgrpc/milestone.go
  polygon/heimdall/heimdallgrpc/server.go
  polygon/heimdall/heimdallgrpc/span.go
  polygon/heimdall/heimdallgrpc/state_sync.go
  turbo/cli/default_flags.go
Labels: polygon

#9231 e35: gnosis support
  cmd/state/exec3/state.go
  core/state/txtask.go
  eth/stagedsync/exec3.go
Labels: gnosis

#9251 Update TestGoerliForkDigest after Dencun
  cl/fork/fork_test.go
Labels: dencun, caplin

#8975 Implement PIP-33: Napoli Hardfork
  core/forkid/forkid.go
  core/types/block_test.go
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/evm.go
  core/vm/interpreter.go
  core/vm/jump_table.go
  core/vm/testdata/precompiles/p256Verify.json
  crypto/secp256r1/publickey.go
  crypto/secp256r1/verifier.go
  erigon-lib/chain/chain_config.go
  erigon-lib/txpool/pool.go
  params/protocol_params.go
  polygon/bor/bor.go
  polygon/bor/borcfg/bor_config.go
Labels: polygon

#9255 Schedule Dencun for Sepolia & Holešky
  cl/clparams/config.go
  core/forkid/forkid_test.go
  params/chainspecs/holesky.json
  params/chainspecs/sepolia.json
Labels: dencun

#9272 Added Holesky network to Caplin
  cl/clparams/config.go
  eth/backend.go
Labels: caplin

#9258 events endpoint
  cl/beacon/beaconevents/emitter.go
  cl/beacon/beaconhttp/api.go
  cl/beacon/beaconhttp/beacon_response.go
  cl/beacon/handler/attestation_rewards.go
  cl/beacon/handler/blocks.go
  cl/beacon/handler/builder.go
  cl/beacon/handler/committees.go
  cl/beacon/handler/duties_attester.go
  cl/beacon/handler/duties_proposer.go
  cl/beacon/handler/duties_sync.go
  cl/beacon/handler/forkchoice.go
  cl/beacon/handler/genesis.go
  cl/beacon/handler/headers.go
  cl/beacon/handler/liveness.go
  cl/beacon/handler/pool.go
  cl/beacon/handler/rewards.go
  cl/beacon/handler/states.go
  cl/beacon/handler/validators.go
  cl/beacon/router.go
  cl/beacon/rw.go
  cl/beacon/validatorapi/get.go
  cl/beacon/validatorapi/handler.go
  cl/beacon/validatorapi/helpers.go
  cl/beacon/validatorapi/post.go
  cl/cltypes/clone.go
  cl/cltypes/sync_aggregator_selection_data.go
  cl/gossip/gossip.go
  cl/phase1/forkchoice/fork_choice_test.go
  cl/phase1/forkchoice/forkchoice.go
  cl/phase1/forkchoice/on_operations.go
  cl/phase1/forkchoice/utils.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/stages/clstages.go
  cl/pool/operations_pool.go
  cl/sentinel/gossip.go
  cl/sentinel/service/start.go
  cl/spectest/consensus_tests/fork_choice.go
  cmd/caplin-regression/regression/tester.go
  cmd/caplin/caplin1/run.go
  go.mod
  go.sum
Labels: caplin

#9257 Caplin: Fixed EL<->CL communication for Deneb
  cl/persistence/block_saver_test.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/execution_client/execution_client_rpc.go
  cl/phase1/execution_client/interface.go
  cl/phase1/forkchoice/on_block.go
  cl/transition/impl/eth2/operations.go
  cl/transition/impl/eth2/utils.go
  cl/transition/impl/funcmap/impl.go
  cl/transition/machine/block.go
  cl/transition/machine/machine.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/gointerfaces/execution/execution.pb.go
  eth/backend.go
  turbo/engineapi/engine_block_downloader/core.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/eth1_chain_reader.go/chain_reader.go
  turbo/execution/eth1/inserters.go
Labels: dencun, caplin

#9280 Fixed chain stall caplin
  cl/antiquary/state_antiquary.go
  cl/phase1/forkchoice/on_block.go
Labels: caplin

#9267 turbo/jsonrpc: add support for bor state sync event tx tracing in debug API
  cmd/release/main.go
  eth/tracers/api.go
  polygon/bor/statefull/processor.go
  polygon/tracer/bor_state_sync_txn_tracer.go
  polygon/tracer/trace_bor_state_sync_txn.go
  turbo/jsonrpc/tracing.go
  turbo/snapshotsync/freezeblocks/block_reader.go
  turbo/transactions/tracing.go
Labels: polygon

#9275 turbo/jsonrpc: fix GetBlockTransactionCountByNumber & ByHash for blocks with bor state sync event txn
  turbo/jsonrpc/eth_block.go
Labels: polygon

#9284 Unbound variable error in silkworm_compat_check
  turbo/silkworm/silkworm_compat_check.sh
Labels: silkworm

#9285 use right function
  cl/phase1/stages/clstages.go
Labels: caplin

#9286 Add tests
  cl/beacon/beaconevents/emitter.go
  cl/beacon/beaconevents/emitter_test.go
  cl/beacon/validatorapi/get.go
Labels: caplin

#9282 Caplin: Better Errors
  cl/phase1/stages/clstages.go
Labels: caplin

#9291 devnet: skip TestStateSync until fixed (#9290)
  cmd/devnet/tests/bor_devnet_test.go
Labels: polygon, devnet

#9277 e2 mumbai 45m
  cl/persistence/block_saver_test.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
Labels: polygon

#9302 polygon/sync: fix implementations naming conventions
  polygon/sync/canonical_chain_builder.go
  polygon/sync/difficulty.go
  polygon/sync/difficulty_test.go
  polygon/sync/header_time_validator.go
  polygon/sync/header_validator.go
  polygon/sync/heimdall.go
Labels: polygon

#9293 silkworm: recreate tx batch and disable read-ahead in block execution
  eth/stagedsync/stage_execute.go
Labels: silkworm

#9276 turbo/jsonrpc: add support for bor state sync txn in Trace API endpoints
  core/rawdb/bor_receipts.go
  core/types/bor_receipt.go
  eth/stagedsync/stage_execute.go
  polygon/tracer/trace_bor_state_sync_txn.go
  rpc/handler.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_api.go
  turbo/jsonrpc/trace_filtering.go
  turbo/jsonrpc/tracing.go
  turbo/transactions/tracing.go
Labels: polygon

#9312 eth, polygon/bor: fix fetch span logic for devnets
  eth/stagedsync/bor_heimdall_shared.go
  eth/stagedsync/stage_bor_heimdall_test.go
  polygon/bor/bor.go
  polygon/bor/span_id.go
Labels: polygon

#9337 integration/commands: add unwind feature for bor heimdall cmd
  cmd/integration/commands/stages.go
Labels: polygon

#9340 core: log marshalled receipts upon receipt hash mismatch err in dbg mode
  core/blockchain.go
  erigon-lib/common/dbg/experiments.go
  eth/ethutils/receipt.go
  turbo/jsonrpc/erigon_receipts.go
  turbo/jsonrpc/eth_receipts.go
  turbo/jsonrpc/graphql_api.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/otterscan_search_trace.go
Labels: polygon

#9345 add napoli block
  core/forkid/forkid_test.go
  params/chainspecs/mumbai.json
Labels: polygon

#9346 Mumbai: add Napoli block
  core/forkid/forkid_test.go
  params/chainspecs/mumbai.json
  params/version.go
Labels: release

#9341 integration/commands: minor - use errorf without printf in stageBorHeimdall cmd
  cmd/integration/commands/stages.go
Labels: polygon

#9342 Bor waypoints
  cmd/devnet/services/polygon/checkpoint.go
  cmd/devnet/services/polygon/heimdall.go
  cmd/devnet/services/polygon/heimdall_test.go
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  erigon-lib/kv/tables.go
  eth/stagedsync/bor_heimdall_shared.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_bor_heimdall_test.go
  eth/stagedsync/stagedsynctest/harness.go
  polygon/bor/bor.go
  polygon/bor/bor_test.go
  polygon/bor/finality/whitelist.go
  polygon/bor/finality/whitelist_helpers.go
  polygon/bor/spanner.go
  polygon/bor/spanner_mock.go
  polygon/heimdall/checkpoint.go
  polygon/heimdall/client.go
  polygon/heimdall/client_mock.go
  polygon/heimdall/client_test.go
  polygon/heimdall/heimdall.go
  polygon/heimdall/heimdall_mock.go
  polygon/heimdall/heimdall_test.go
  polygon/heimdall/http_client_mock.go
  polygon/heimdall/milestone.go
  polygon/heimdall/span.go
  polygon/heimdall/span_id.go
  polygon/heimdall/span_id_test.go
  polygon/heimdall/storage.go
  polygon/heimdall/storage_mock.go
  polygon/heimdall/waypoint.go
  polygon/sync/accumulated_headers_verifier.go
  polygon/sync/canonical_chain_builder_test.go
  polygon/sync/header_downloader.go
  polygon/sync/header_downloader_test.go
  polygon/sync/heimdall.go
  polygon/sync/heimdall_mock.go
  polygon/sync/heimdall_test.go
  polygon/sync/spans_cache.go
  polygon/sync/state_point.go
  polygon/sync/state_point_kind.go
  polygon/sync/state_points.go
  polygon/sync/storage.go
  polygon/sync/storage_mock.go
Labels: polygon

#9344 bor snaps: gen bor snaps, if they are behind block snaps
  turbo/snapshotsync/freezeblocks/block_snapshots.go
Labels: polygon

#9352 Updated sepolia fork digest in tests
  cl/fork/fork_test.go
Labels: dencun
