Repository erigontech/erigon, pull requests merged in 2025-01, with the labels that each got.

#13308 caplin: Use `HandleEndpointFunc` for `node` endpoints
  cl/beacon/beaconhttp/api.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/node.go
Labels: caplin

#13333 caplin: Fix `nil` panic during error handling
  cl/beacon/beaconhttp/api.go
Labels: caplin

#13335 rpcdaemon: Set miner on `eth_getBlockByNumber` on Polygon
  turbo/jsonrpc/eth_block.go
Labels: polygon

#13336 rpcdaemon: Set miner on `eth_getBlockByNumber` on Polygon
  turbo/jsonrpc/eth_block.go
Labels: polygon

#13351 polygon: astrid fix --no-downloader issue due to bridge snapshot store bug
  polygon/bridge/snapshot_store.go
Labels: polygon

#13361 polygon: keep devp2p max peers default to 100 as before
  cmd/utils/flags.go
Labels: polygon

#13069 Update addresses for EIPs 7002 and 7251
  .github/workflows/ci.yml
  .github/workflows/test-integration-caplin.yml
  .github/workflows/test-integration-erigon.yml
  params/protocol_params.go
Labels: pectra

#13306 shutter: listen for decryption keys
  cmd/utils/flags.go
  eth/backend.go
  turbo/cli/default_flags.go
  txnprovider/shutter/.gitignore
  txnprovider/shutter/Makefile
  txnprovider/shutter/config.go
  txnprovider/shutter/decryption_keys_listener.go
  txnprovider/shutter/decryption_keys_processor.go
  txnprovider/shutter/decryption_keys_validator.go
  txnprovider/shutter/decryption_keys_validator_test.go
  txnprovider/shutter/internal/testhelpers/collecting_log_handler.go
  txnprovider/shutter/internal/testhelpers/decryption_keys_mock_data.go
  txnprovider/shutter/pool.go
  txnprovider/shutter/proto/serialization.go
  txnprovider/shutter/proto/serialization_test.go
  txnprovider/shutter/proto/shutter.pb.go
  txnprovider/shutter/proto/shutter.proto
Labels: shutter

#13408 Update addresses for EIPs 7002 and 7251 (#13069)
  .github/workflows/ci.yml
  .github/workflows/test-integration-caplin.yml
  .github/workflows/test-integration.yml
  params/protocol_params.go
Labels: pectra

#13425 [automation] Backup of erigonQA dashboard - 14 Jan 2025
  dashboards/erigonQA/erigonQA.internal.json
  dashboards/erigonQA/history/20250114.tar.gz
Labels: backups

#13435 [automation] Backup of erigon_custom_metrics dashboard - 14 Jan 2025
  dashboards/erigon_custom_metrics/erigon_custom_metrics.internal.json
  dashboards/erigon_custom_metrics/history/20250114.tar.gz
Labels: backups

#13106 Implement EXTCODE* changes for pdn-5
  core/state/intra_block_state.go
  core/state_transition.go
  core/types/authorization.go
  core/types/encdec_test.go
  core/types/transaction_marshalling.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  core/vm/instructions.go
  core/vm/operations_acl.go
  params/protocol_params.go
Labels: pectra

#13452 backend: fix interface conversion: chain.BorConfig is nil panic
  eth/backend.go
Labels: polygon

#13346 core/vm: BLS gas changes for pectra-devnet-5 per EIP-2537
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/testdata/precompiles/blsG1Add.json
  core/vm/testdata/precompiles/blsG1Mul.json
  core/vm/testdata/precompiles/blsG1MultiExp.json
  core/vm/testdata/precompiles/blsG2Add.json
  core/vm/testdata/precompiles/blsG2Mul.json
  core/vm/testdata/precompiles/blsG2MultiExp.json
  core/vm/testdata/precompiles/blsMapG2.json
  core/vm/testdata/precompiles/blsPairing.json
  core/vm/testdata/precompiles/fail-blsG1Mul.json
  core/vm/testdata/precompiles/fail-blsG2Mul.json
  params/protocol_params.go
  tests/exec_spec_test.go
  tests/fuzzers/bls12381/precompile_fuzzer.go
Labels: pectra

#13296 caplin on mekong devnet-4
  cl/clparams/config.go
  cl/cltypes/beacon_block.go
  cl/cltypes/beacon_block_test.go
  cl/cltypes/beacon_kzgcommitment_test.go
  cl/cltypes/eth1_block.go
  cl/cltypes/execution_requests.go
  cl/cltypes/solid/attestation.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/core/state/util.go
  cl/phase1/execution_client/block_collector/block_collector.go
  cl/phase1/execution_client/execution_client_direct.go
  cl/phase1/forkchoice/fork_graph/fork_graph_disk.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/network/blobs.go
  cl/phase1/network/gossip_manager.go
  cl/phase1/network/services/attestation_service_test.go
  cl/phase1/stages/chain_tip_sync.go
  cl/phase1/stages/forward_sync.go
  cl/rpc/rpc.go
  cl/sentinel/communication/topics.go
  cl/sentinel/handlers/blobs.go
  cl/sentinel/handlers/handlers.go
  cl/sentinel/httpreqresp/server.go
  cl/sentinel/service/service.go
  cl/transition/impl/eth2/operations.go
  cl/transition/impl/eth2/validation.go
  cl/transition/machine/block.go
  cl/utils/eth_clock/ethereum_clock.go
  cmd/utils/flags.go
  turbo/cli/default_flags.go
  turbo/execution/eth1/inserters.go
Labels: pectra, caplin

#13464 core/vm: Small fix
  core/vm/contracts_test.go
Labels: pectra

#13426 Implement EIP-7691 blob gas price changes for pdn-5
  accounts/abi/bind/backends/simulated.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/state.go
  consensus/merge/merge.go
  consensus/misc/eip1559.go
  consensus/misc/eip4844.go
  core/blockchain.go
  core/chain_makers.go
  core/evm.go
  erigon-lib/chain/chain_config.go
  eth/ethutils/receipt.go
  eth/gasprice/feehistory.go
  eth/stagedsync/stage_mining_exec.go
  tests/state_test_util.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/inserters.go
  turbo/jsonrpc/eth_system.go
  turbo/jsonrpc/receipts/receipts_generator.go
  turbo/stages/stageloop.go
  txnprovider/txpool/assemble.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_test.go
Labels: pectra

#13467 Make secondsPerSlot available in chain config
  consensus/misc/eip1559.go
  erigon-lib/chain/chain_config.go
  eth/gasprice/feehistory.go
  turbo/jsonrpc/eth_block.go
  turbo/jsonrpc/eth_system.go
  turbo/stages/stageloop.go
Labels: pectra

#13469 core/vm: BLS gas changes for pectra-devnet-5 per EIP-2537 (#13346)
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/testdata/precompiles/blsG1Add.json
  core/vm/testdata/precompiles/blsG1Mul.json
  core/vm/testdata/precompiles/blsG1MultiExp.json
  core/vm/testdata/precompiles/blsG2Add.json
  core/vm/testdata/precompiles/blsG2Mul.json
  core/vm/testdata/precompiles/blsG2MultiExp.json
  core/vm/testdata/precompiles/blsMapG2.json
  core/vm/testdata/precompiles/blsPairing.json
  core/vm/testdata/precompiles/fail-blsG1Mul.json
  core/vm/testdata/precompiles/fail-blsG2Mul.json
  params/protocol_params.go
  tests/exec_spec_test.go
  tests/fuzzers/bls12381/precompile_fuzzer.go
Labels: pectra

#13481 Fix floor gas for create and enable spec tests
  erigon-lib/common/fixedgas/intrinsic_gas.go
  tests/exec_spec_test.go
Labels: pectra

#13511 rpcdaemon: Set zero gas used for state sync receipts
  turbo/jsonrpc/receipts/bor_receipts_generator.go
Labels: polygon

#13516 engineapi: fix req root mismatch upon `newPayload`
  Makefile
  turbo/engineapi/engine_server.go
Labels: pectra

#13517 MIN_EPOCHS_FOR_BLOBS_SIDECARS_REQUEST -> MIN_EPOCHS_FOR_BLOB_SIDECARS…
  cl/clparams/config.go
  cl/phase1/stages/forward_sync.go
Labels: caplin

#13527 [automation] Backup of erigon_custom_metrics dashboard - 22 Jan 2025
  dashboards/erigon_custom_metrics/erigon_custom_metrics.internal.json
  dashboards/erigon_custom_metrics/history/20250122.tar.gz
Labels: backups

#13520 polygon/bridge: fix process new blocks gaps
  cmd/devnet/services/polygon/heimdallsim/heimdall_simulator.go
  eth/stagedsync/stage_polygon_sync.go
  polygon/bridge/mdbx_store.go
  polygon/bridge/service.go
  polygon/bridge/store.go
  polygon/sync/sync.go
Labels: polygon

#13443 EIP-7840: Add blob schedule to EL config files
  core/types/blob_tx_wrapper.go
  erigon-lib/chain/chain_config.go
  erigon-lib/chain/chain_config_test.go
  erigon-lib/common/fixedgas/protocol.go
  params/chainspecs/chiado.json
  params/chainspecs/gnosis.json
  params/chainspecs/holesky.json
  params/chainspecs/mainnet.json
  params/chainspecs/sepolia.json
  params/config_test.go
  txnprovider/txpool/assemble.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_test.go
Labels: pectra

#13554 contracts: add direct contract backend
  cmd/rpcdaemon/cli/config.go
  contracts/backend.go
  eth/backend.go
  rpc/handler.go
  rpc/subscription.go
  turbo/jsonrpc/eth_api.go
  txnprovider/shutter/pool.go
Labels: shutter

#13574 core: Fix signature mismatch issues due to authorization encoding
  core/state_transition.go
  core/types/authorization_test.go
Labels: pectra

#13575 Unify jsonrpc.RPCTransaction & ethapi.RPCTransaction
  cmd/devnet/blocks/checks.go
  cmd/devnet/blocks/waiter.go
  cmd/devnet/contracts/util.go
  cmd/devnet/requests/block.go
  cmd/devnet/requests/nopgenerator.go
  cmd/devnet/requests/request_generator.go
  cmd/devnet/requests/transaction.go
  cmd/devnet/services/polygon/proofgenerator.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  cmd/evm/internal/t8ntool/transition.go
  turbo/adapter/ethapi/api.go
  turbo/jsonrpc/eth_api.go
  turbo/jsonrpc/eth_txs.go
  turbo/jsonrpc/otterscan_api.go
  turbo/jsonrpc/otterscan_search_trace.go
  turbo/jsonrpc/otterscan_search_v3.go
  turbo/jsonrpc/txpool_api.go
Labels: pectra

#13472 Caplin electra devnet-5
  cl/antiquary/tests/test_data/electra/blocks_0.ssz_snappy
  cl/antiquary/tests/test_data/electra/blocks_1.ssz_snappy
  cl/antiquary/tests/test_data/electra/meta.yaml
  cl/antiquary/tests/test_data/electra/post.ssz_snappy
  cl/antiquary/tests/test_data/electra/pre.ssz_snappy
  cl/clparams/config.go
  cl/cltypes/beacon_block.go
  cl/cltypes/execution_requests.go
  cl/cltypes/solid/deposits.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/core/state/shuffling/shuffling.go
  cl/phase1/core/state/upgrade.go
  cl/phase1/forkchoice/on_block.go
  cl/phase1/network/beacon_downloader.go
  cl/phase1/network/services/blob_sidecar_service.go
  cl/phase1/network/services/block_service.go
  cl/rpc/rpc.go
  cl/sentinel/service/service.go
  cl/sentinel/service/start.go
  cl/spectest/Makefile
  cl/transition/impl/eth2/operations.go
  cl/transition/impl/eth2/statechange/process_pending_consolidations.go
  eth/ethutils/utils.go
Labels: pectra, caplin

#13566 New beacon api for electra
  cl/aggregation/mock_services/aggregation_pool_mock.go
  cl/aggregation/pool.go
  cl/aggregation/pool_impl.go
  cl/beacon/handler/handler.go
  cl/beacon/handler/pool.go
  cl/beacon/handler/validators.go
Labels: pectra, caplin

#13583 Implement EIP-7691 blob gas price changes for pdn-5 (#13426)
  accounts/abi/bind/backends/simulated.go
  cmd/devnet/services/polygon/proofgenerator_test.go
  cmd/state/commands/opcode_tracer.go
  cmd/state/exec3/state.go
  consensus/merge/merge.go
  consensus/misc/eip1559.go
  consensus/misc/eip4844.go
  core/blockchain.go
  core/chain_makers.go
  core/evm.go
  core/state_processor.go
  core/state_transition.go
  core/vm/eips.go
  core/vm/evmtypes/evmtypes.go
  erigon-lib/chain/chain_config.go
  erigon-lib/txpool/pool.go
  erigon-lib/txpool/pool_fuzz_test.go
  erigon-lib/txpool/pool_test.go
  erigon-lib/txpool/txpoolutil/all_components.go
  eth/ethutils/receipt.go
  eth/gasprice/feehistory.go
  eth/stagedsync/exec3.go
  eth/stagedsync/stage_mining_exec.go
  eth/tracers/tracers_test.go
  tests/state_test_util.go
  turbo/engineapi/engine_server.go
  turbo/execution/eth1/inserters.go
  turbo/jsonrpc/eth_block.go
  turbo/jsonrpc/eth_call.go
  turbo/jsonrpc/eth_callMany.go
  turbo/jsonrpc/eth_receipts.go
  turbo/jsonrpc/eth_system.go
  turbo/jsonrpc/otterscan_generic_tracer.go
  turbo/jsonrpc/otterscan_search_trace.go
  turbo/jsonrpc/overlay_api.go
  turbo/jsonrpc/trace_adhoc.go
  turbo/jsonrpc/trace_filtering.go
  turbo/jsonrpc/tracing.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
  turbo/transactions/call.go
  turbo/transactions/tracing.go
Labels: pectra

#13584 Fix floor gas for create and enable spec tests (#13481)
  erigon-lib/txpool/txpoolcfg/txpoolcfg.go
  tests/exec_spec_test.go
Labels: pectra

#13615 core/types: Rename V to yParity in JsonAuthorization
  core/types/transaction_marshalling.go
Labels: pectra

#13625 execution: Fix request append out of range in block building
  turbo/execution/eth1/block_building.go
Labels: pectra

#13624 kz4844: pass blobs by ref
  cl/persistence/blob_storage/blob_db.go
  cl/phase1/network/services/blob_sidecar_service.go
  core/types/blob_tx_wrapper.go
  core/types/typestest/test_data.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  go.mod
  go.sum
  txnprovider/txpool/pool.go
Labels: dencun

#13630 TxPool: added check dynamic transactions gas fee
  core/types/dynamic_fee_tx.go
  turbo/jsonrpc/send_transaction.go
  turbo/jsonrpc/send_transaction_test.go
  turbo/stages/mock/mock_sentry.go
Labels: block-building, l1el

#13640 polygon/sync: retry ufc on busy response
  polygon/sync/execution_client.go
  polygon/sync/service.go
Labels: polygon
