Repository erigontech/erigon, pull requests merged in 2025-02, with the labels that each got.

#13647 shutter: add eon tracker
  eth/backend.go
  txnprovider/shutter/block_listener.go
  txnprovider/shutter/config.go
  txnprovider/shutter/decryption_keys_listener.go
  txnprovider/shutter/decryption_keys_validator.go
  txnprovider/shutter/decryption_keys_validator_test.go
  txnprovider/shutter/eon_tracker.go
  txnprovider/shutter/internal/testhelpers/eon_tracker_mock.go
  txnprovider/shutter/internal/testhelpers/mockgen.go
  txnprovider/shutter/internal/testhelpers/slot_calculator_mock.go
  txnprovider/shutter/pool.go
  txnprovider/shutter/slot_calculator.go
  txnprovider/shutter/state_changes_client.go
Labels: shutter

#13639 params: Update addresses to nicer looking for devnet-6
  params/protocol_params.go
Labels: pectra

#13638 Remove extra logic for EXTCODE* wrt 7702
  core/vm/instructions.go
Labels: pectra

#13704 [automation] Backup of erigonQA dashboard - 05 Feb 2025
  dashboards/erigonQA/erigonQA.internal.json
Labels: backups

#13703 [automation] Backup of erigon_custom_metrics dashboard - 05 Feb 2025
  dashboards/erigon_custom_metrics/erigon_custom_metrics.internal.json
Labels: backups

#13698 engineapi: Add request ascending order check
  turbo/engineapi/engine_server.go
Labels: l1el

#13731 polygon: Add Cloudflare transient err
  polygon/heimdall/client_http.go
Labels: polygon

#13795 rpcdaemon: Don't set miner
  turbo/jsonrpc/eth_block.go
Labels: polygon

#13799 rpcdaemon: Don't set miner
  turbo/jsonrpc/eth_block.go
Labels: polygon

#13798 rpcdaemon: Don't set miner
  turbo/jsonrpc/eth_block.go
Labels: polygon
