Repository erigontech/erigon, pull requests merged in 2025-05, with the labels that each got.

#14834 workflows: Temp disable 7702 invalidation test on kurtosis
  .github/workflows/kurtosis/pectra.io
Labels: Pectra

#14843 EIP-7892: Blob Parameter Only Hardforks
  cmd/devnet/networks/devnet_bor.go
  cmd/integration/commands/stages.go
  cmd/integration/commands/state_stages.go
  core/block_validator_test.go
  core/genesis_write.go
  erigon-lib/chain/chain_config.go
  erigon-lib/chain/chain_config_test.go
  erigon-lib/chain/params/protocol.go
  erigon-lib/common/collections.go
  eth/backend.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_bodies.go
  eth/stagedsync/stage_bor_heimdall.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_mining_finish.go
  eth/stagedsync/stage_snapshots.go
  eth/stagedsync/stagedsynctest/chain_configs.go
  eth/stagedsync/stagedsynctest/harness.go
  execution/consensus/clique/snapshot_test.go
  execution/consensus/misc/eip1559_test.go
  go.mod
  go.sum
  params/config.go
  params/config_test.go
  polygon/bor/borcfg/bor_config.go
  tests/init_test.go
  turbo/snapshotsync/freezeblocks/dump_test.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
  txnprovider/shutter/block_building_integration_test.go
  txnprovider/txpool/assemble.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_test.go
Labels: FUSAKA

#14925 Fix failing test
  cl/sentinel/sentinel_gossip_test.go
Labels: Pectra

#14803 ethapi: Add `blobVersionedHashes` to `callArgs`
  erigon-lib/types/transaction.go
  rpc/ethapi/api.go
Labels: Dencun

#14910 Caplin: Fix misc issues after electra
  cl/aggregation/pool_test.go
  cl/beacon/beaconevents/model.go
  cl/beacon/beaconevents/operation_feed.go
  cl/beacon/handler/pool.go
  cl/cltypes/solid/attestation.go
  cl/cltypes/solid/bitlist.go
  cl/cltypes/solid/bitlist_test.go
  cl/phase1/core/state/cache_accessors.go
  cl/phase1/network/services/attestation_service.go
  cl/phase1/network/services/sync_committee_messages_service.go
  cl/phase1/network/services/sync_contribution_service.go
  cl/validator/sync_contribution_pool/sync_contribution_pool.go
Labels: Pectra, caplin

#12907 [DO-NOT-MERGE] .ef optimization experiments
  cmd/integration/commands/idx_optimize.go
  cmd/integration/commands/idx_verify.go
  erigon-lib/recsplit/eliasfano32/rebased_elias_fano.go
  erigon-lib/recsplit/multiencseq/sequence_builder.go
  erigon-lib/recsplit/multiencseq/sequence_builder_test.go
  erigon-lib/recsplit/multiencseq/sequence_reader.go
  erigon-lib/recsplit/multiencseq/sequence_reader_test.go
  erigon-lib/recsplit/simpleseq/simple_sequence.go
  erigon-lib/recsplit/simpleseq/simple_sequence_test.go
  erigon-lib/state/aggregator.go
  erigon-lib/state/domain.go
  erigon-lib/state/history.go
  erigon-lib/state/history_stream.go
  erigon-lib/state/history_test.go
  erigon-lib/state/integrity.go
  erigon-lib/state/inverted_index.go
  erigon-lib/state/inverted_index_stream.go
  erigon-lib/state/inverted_index_test.go
  erigon-lib/state/merge.go
  erigon-lib/state/merge_test.go
  erigon-lib/state/version_schema.go
Labels: do-not-merge

#14969 Update kurtosis test LH version
  .github/workflows/kurtosis/pectra.io
  .github/workflows/kurtosis/regular-assertoor.io
  Makefile
Labels: Pectra

#14968 txpool: allow higher nonce in pool with existing SetcodeTxn
  .github/workflows/kurtosis/eip7702-test.io
  .github/workflows/kurtosis/pectra.io
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_test.go
  txnprovider/txpool/pool_txn_parser.go
  txnprovider/txpool/pool_txn_parser_test.go
Labels: Pectra

#15093 Implement EIP-7883: ModExp Gas Cost Increase
  core/state_transition.go
  core/vm/contracts.go
  core/vm/contracts_test.go
  core/vm/evm.go
  core/vm/testdata/precompiles/modexp_eip7883.json
  erigon-lib/common/math/big.go
  polygon/aa/aa_gas.go
  rpc/ethapi/api.go
Labels: FUSAKA

#15148 Implement EIP-7823: Set upper bounds for MODEXP
  core/vm/contracts.go
  core/vm/contracts_test.go
Labels: FUSAKA

#15261 Polygon Bhilai Fork Updates
  cmd/integration/commands/flags.go
  cmd/utils/flags.go
  core/vm/contracts.go
  core/vm/evm.go
  core/vm/interpreter.go
  core/vm/jump_table.go
  erigon-lib/chain/chain_config.go
  erigon-lib/chain/params/protocol.go
  eth/backend.go
  eth/ethconfig/config.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stagedsynctest/harness.go
  execution/consensus/misc/eip1559.go
  p2p/forkid/forkid.go
  params/mining.go
  polygon/bor/bor.go
  polygon/bor/borcfg/bor_config.go
  tests/bor/helper/miner.go
  txnprovider/txpool/assemble.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_test.go
Labels: Pectra

#15067 EIP-7892: Blob Parameter Only Hardforks - 2nd attempt
  cmd/devnet/networks/devnet_bor.go
  cmd/evm/internal/t8ntool/flags.go
  cmd/integration/commands/stages.go
  cmd/integration/commands/state_stages.go
  cmd/utils/flags.go
  core/block_validator_test.go
  core/genesis_write.go
  erigon-lib/chain/chain_config.go
  erigon-lib/chain/chain_config_test.go
  erigon-lib/chain/params/protocol.go
  erigon-lib/common/collections.go
  eth/backend.go
  eth/stagedsync/chain_reader.go
  eth/stagedsync/stage_bodies.go
  eth/stagedsync/stage_headers.go
  eth/stagedsync/stage_mining_create_block.go
  eth/stagedsync/stage_mining_exec.go
  eth/stagedsync/stage_mining_finish.go
  eth/stagedsync/stage_snapshots.go
  eth/stagedsync/stagedsynctest/chain_configs.go
  execution/consensus/clique/snapshot_test.go
  execution/consensus/misc/eip1559_test.go
  execution/testutil/forks.go
  go.mod
  go.sum
  params/config.go
  params/config_test.go
  polygon/bor/borcfg/bor_config.go
  tests/block_test_util.go
  tests/difficulty_test.go
  tests/init_test.go
  tests/state_test_util.go
  tests/transaction_test_util.go
  turbo/snapshotsync/freezeblocks/dump_test.go
  turbo/stages/mock/mock_sentry.go
  turbo/stages/stageloop.go
  txnprovider/shutter/block_building_integration_test.go
  txnprovider/txpool/assemble.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_fuzz_test.go
  txnprovider/txpool/pool_test.go
  txnprovider/txpool/txpoolcfg/txpoolcfg.go
Labels: FUSAKA
