Repository erigontech/erigon, pull requests merged in 2025-06, with the labels that each got.

#15222 Add EngineAPI and Txpool changes for Fusaka
  erigon-db/go.mod
  erigon-db/go.sum
  erigon-lib/crypto/kzg/go_eth_kzg.go
  erigon-lib/go.mod
  erigon-lib/go.sum
  erigon-lib/types/blob_test_util.go
  erigon-lib/types/blob_tx_wrapper.go
  erigon-lib/types/transaction_test.go
  execution/eth1/block_building.go
  go.mod
  go.sum
  p2p/go.mod
  p2p/go.sum
  turbo/stages/mock/mock_sentry.go
  txnprovider/txpool/pool.go
  txnprovider/txpool/pool_mock.go
  txnprovider/txpool/pool_test.go
  txnprovider/txpool/pool_txn_parser.go
  txnprovider/txpool/pool_txn_parser_test.go
  txnprovider/txpool/senders.go
  txnprovider/txpool/txpool_grpc_server.go
Labels: FUSAKA

#15420 engineapi, txpool: implement getBlobsV2
  erigon-lib/types/blob_test_util.go
  turbo/engineapi/engine_api_methods.go
  turbo/engineapi/engine_server.go
  turbo/engineapi/engine_server_test.go
  turbo/engineapi/engine_types/jsonrpc.go
Labels: FUSAKA

#15555 Change `bn256Add` to use consensys gnark-bn254 lib
  core/vm/contracts.go
  go.mod
  go.sum
Labels: performance

#15520 core/vm: Add EIP-7883 changes
  core/vm/contracts.go
Labels: FUSAKA

#15661 core/vm: avoid unnecessary malloc in opCLZ
  core/vm/eips.go
Labels: performance, FUSAKA

#15763 txpool: Bump default txpool blob limits
  txnprovider/txpool/txpoolcfg/txpoolcfg.go
Labels: FUSAKA
